
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 20 2026 02:16:15 KST (Aug 19 2026 17:16:15 UTC)

// Verification Directory fv/aer_improved_cutthrough 

module aer_improved_cutthrough(clk, rst_n, src_req_async,
     src_ack_async, out_addr, out_valid, out_ready);
  input clk, rst_n, out_ready;
  input [15:0] src_req_async;
  output [15:0] src_ack_async;
  output [3:0] out_addr;
  output out_valid;
  wire clk, rst_n, out_ready;
  wire [15:0] src_req_async;
  wire [15:0] src_ack_async;
  wire [3:0] out_addr;
  wire out_valid;
  wire [1:0] \local_rr_q[0] ;
  wire [1:0] \local_rr_q[1] ;
  wire [1:0] \local_rr_q[3] ;
  wire [1:0] \local_rr_q[2] ;
  wire [15:0] pending_q;
  wire [1:0] group_rr_q;
  wire [15:0] req_sync_q;
  wire [15:0] req_meta_q;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_257;
  DFFRX1 \local_rr_q_reg[0][1] (.RN (rst_n), .CK (clk), .D (n_234), .Q
       (n_82), .QN (\local_rr_q[0] [1]));
  DFFRX1 \local_rr_q_reg[1][1] (.RN (rst_n), .CK (clk), .D (n_236), .Q
       (n_60), .QN (\local_rr_q[1] [1]));
  DFFRX1 \local_rr_q_reg[3][1] (.RN (rst_n), .CK (clk), .D (n_233), .Q
       (n_88), .QN (\local_rr_q[3] [1]));
  DFFRX1 \local_rr_q_reg[2][1] (.RN (rst_n), .CK (clk), .D (n_237), .Q
       (n_53), .QN (\local_rr_q[2] [1]));
  DFFRHQX1 \pending_q_reg[4] (.RN (rst_n), .CK (clk), .D (n_224), .Q
       (pending_q[4]));
  DFFRHQX1 \pending_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_229), .Q
       (pending_q[2]));
  DFFRHQX1 \pending_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_228), .Q
       (pending_q[0]));
  DFFRHQX1 \pending_q_reg[6] (.RN (rst_n), .CK (clk), .D (n_226), .Q
       (pending_q[6]));
  DFFRHQX1 \pending_q_reg[10] (.RN (rst_n), .CK (clk), .D (n_222), .Q
       (pending_q[10]));
  DFFRHQX1 \pending_q_reg[14] (.RN (rst_n), .CK (clk), .D (n_232), .Q
       (pending_q[14]));
  DFFRHQX1 \pending_q_reg[8] (.RN (rst_n), .CK (clk), .D (n_220), .Q
       (pending_q[8]));
  DFFRHQX1 \pending_q_reg[12] (.RN (rst_n), .CK (clk), .D (n_231), .Q
       (pending_q[12]));
  MXI2X1 g10005__2398(.S0 (n_207), .B (n_235), .A (\local_rr_q[2] [1]),
       .Y (n_237));
  MXI2X1 g10007__5107(.S0 (n_200), .B (\local_rr_q[1] [1]), .A (n_235),
       .Y (n_236));
  MXI2X1 g10006__6260(.S0 (n_202), .B (\local_rr_q[0] [1]), .A (n_235),
       .Y (n_234));
  MXI2X1 g10008__4319(.S0 (n_205), .B (n_235), .A (\local_rr_q[3] [1]),
       .Y (n_233));
  DFFRHQX1 \pending_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_214), .Q
       (pending_q[3]));
  DFFRHQX1 \pending_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_218), .Q
       (pending_q[1]));
  DFFRHQX1 \pending_q_reg[5] (.RN (rst_n), .CK (clk), .D (n_211), .Q
       (pending_q[5]));
  DFFRHQX1 \pending_q_reg[7] (.RN (rst_n), .CK (clk), .D (n_210), .Q
       (pending_q[7]));
  DFFRHQX1 \pending_q_reg[9] (.RN (rst_n), .CK (clk), .D (n_209), .Q
       (pending_q[9]));
  DFFRHQX1 \pending_q_reg[15] (.RN (rst_n), .CK (clk), .D (n_212), .Q
       (pending_q[15]));
  DFFRHQX1 \pending_q_reg[11] (.RN (rst_n), .CK (clk), .D (n_216), .Q
       (pending_q[11]));
  DFFRHQX1 \pending_q_reg[13] (.RN (rst_n), .CK (clk), .D (n_217), .Q
       (pending_q[13]));
  AOI21XL g10019__8428(.A0 (n_225), .A1 (n_230), .B0 (n_66), .Y
       (n_232));
  AOI21XL g10023__5526(.A0 (n_223), .A1 (n_230), .B0 (n_64), .Y
       (n_231));
  AOI21XL g10024__6783(.A0 (n_221), .A1 (n_227), .B0 (n_71), .Y
       (n_229));
  AOI21XL g10025__3680(.A0 (n_219), .A1 (n_227), .B0 (n_69), .Y
       (n_228));
  DFFRX1 \local_rr_q_reg[2][0] (.RN (rst_n), .CK (clk), .D (n_208), .Q
       (n_92), .QN (\local_rr_q[2] [0]));
  DFFRX1 \local_rr_q_reg[3][0] (.RN (rst_n), .CK (clk), .D (n_206), .Q
       (n_62), .QN (\local_rr_q[3] [0]));
  AOI21XL g10029__1617(.A0 (n_225), .A1 (n_227), .B0 (n_56), .Y
       (n_226));
  AOI21XL g10028__2802(.A0 (n_223), .A1 (n_227), .B0 (n_55), .Y
       (n_224));
  AOI21XL g10015__1705(.A0 (n_221), .A1 (n_230), .B0 (n_52), .Y
       (n_222));
  AOI21XL g10030__5122(.A0 (n_219), .A1 (n_230), .B0 (n_54), .Y
       (n_220));
  DFFRX1 \local_rr_q_reg[1][0] (.RN (rst_n), .CK (clk), .D (n_201), .Q
       (n_91), .QN (\local_rr_q[1] [0]));
  DFFRHQX1 \local_rr_q_reg[0][0] (.RN (rst_n), .CK (clk), .D (n_203),
       .Q (\local_rr_q[0] [0]));
  AOI21XL g10026__8246(.A0 (n_219), .A1 (n_213), .B0 (n_70), .Y
       (n_218));
  AOI21XL g10021__7098(.A0 (n_223), .A1 (n_215), .B0 (n_65), .Y
       (n_217));
  AOI21XL g10020__6131(.A0 (n_221), .A1 (n_215), .B0 (n_57), .Y
       (n_216));
  DFFRHQX1 \out_addr_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_199), .Q
       (out_addr[0]));
  AOI21XL g10016__1881(.A0 (n_221), .A1 (n_213), .B0 (n_67), .Y
       (n_214));
  AOI21XL g10031__5115(.A0 (n_225), .A1 (n_215), .B0 (n_63), .Y
       (n_212));
  AOI21XL g10027__7482(.A0 (n_223), .A1 (n_213), .B0 (n_61), .Y
       (n_211));
  AOI21XL g10017__4733(.A0 (n_225), .A1 (n_213), .B0 (n_59), .Y
       (n_210));
  AOI21XL g10018__6161(.A0 (n_219), .A1 (n_215), .B0 (n_58), .Y
       (n_209));
  MXI2XL g10045__9315(.S0 (n_207), .B (n_204), .A (\local_rr_q[2] [0]),
       .Y (n_208));
  MXI2XL g10046__9945(.S0 (n_205), .B (n_204), .A (\local_rr_q[3] [0]),
       .Y (n_206));
  OAI2BB2XL g10048__2883(.A0N (\local_rr_q[0] [0]), .A1N (n_202), .B0
       (n_204), .B1 (n_202), .Y (n_203));
  MXI2XL g10049__2346(.S0 (n_200), .B (\local_rr_q[1] [0]), .A (n_204),
       .Y (n_201));
  AOI22X1 g10032__1666(.A0 (n_193), .A1 (n_204), .B0 (n_192), .B1
       (n_198), .Y (n_235));
  OAI2BB2XL g10047__7410(.A0N (out_addr[0]), .A1N (n_197), .B0 (n_198),
       .B1 (n_197), .Y (n_199));
  NOR2X1 g10050__6417(.A (n_204), .B (n_195), .Y (n_227));
  DFFRHQX1 \out_addr_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_194), .Q
       (out_addr[1]));
  NOR2X1 g10053__5477(.A (n_204), .B (n_196), .Y (n_230));
  NOR2X1 g10051__2398(.A (n_198), .B (n_196), .Y (n_215));
  NOR2X1 g10054__5107(.A (n_198), .B (n_195), .Y (n_213));
  OAI2BB2XL g10033__6260(.A0N (out_addr[1]), .A1N (n_197), .B0 (n_193),
       .B1 (n_197), .Y (n_194));
  INVX1 g10055(.A (n_198), .Y (n_204));
  NOR2X1 g10034__4319(.A (n_192), .B (n_191), .Y (n_219));
  NOR2X1 g10036__8428(.A (n_192), .B (n_190), .Y (n_223));
  AOI211X1 g10056__5526(.A0 (n_141), .A1 (\local_rr_q[0] [0]), .B0
       (n_189), .C0 (n_142), .Y (n_198));
  NOR2X1 g10035__6783(.A (n_193), .B (n_191), .Y (n_221));
  NOR2X1 g10037__3680(.A (n_193), .B (n_190), .Y (n_225));
  INVX1 g10041(.A (n_193), .Y (n_192));
  AOI211X1 g10042__1617(.A0 (n_188), .A1 (n_169), .B0 (n_187), .C0
       (n_170), .Y (n_193));
  OAI2BB1X1 g10058__2802(.A0N (\local_rr_q[3] [0]), .A1N (n_188), .B0
       (n_186), .Y (n_189));
  NAND4X1 g10052__1705(.A (n_185), .B (n_182), .C (n_151), .D (n_154),
       .Y (n_187));
  AOI211X1 g10059__5122(.A0 (n_156), .A1 (\local_rr_q[3] [0]), .B0
       (n_184), .C0 (n_173), .Y (n_186));
  NOR4X1 g10057__8246(.A (n_181), .B (n_163), .C (n_180), .D (n_159),
       .Y (n_185));
  OR4X2 g10060__7098(.A (n_175), .B (n_177), .C (n_168), .D (n_162), .Y
       (n_184));
  DFFRHQX1 \group_rr_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_183), .Q
       (group_rr_q[1]));
  INVX1 g10063(.A (n_178), .Y (n_183));
  AOI22X1 g10071__6131(.A0 (n_139), .A1 (n_112), .B0 (n_165), .B1
       (n_179), .Y (n_182));
  OAI222XL g10062__1881(.A0 (n_172), .A1 (n_6), .B0 (n_171), .B1 (n_5),
       .C0 (n_158), .C1 (n_174), .Y (n_181));
  OAI21XL g10066__5115(.A0 (n_176), .A1 (n_179), .B0 (n_149), .Y
       (n_180));
  AOI211XL g10067__7482(.A0 (n_197), .A1 (group_rr_q[1]), .B0 (n_143),
       .C0 (n_207), .Y (n_178));
  AOI21X1 g10070__4733(.A0 (n_164), .A1 (n_176), .B0 (n_92), .Y
       (n_177));
  AOI21X1 g10064__6161(.A0 (n_157), .A1 (n_174), .B0 (\local_rr_q[0]
       [0]), .Y (n_175));
  AOI21X1 g10065__9315(.A0 (n_172), .A1 (n_171), .B0 (n_91), .Y
       (n_173));
  OAI32X1 g10068__9945(.A0 (n_166), .A1 (n_167), .A2 (\local_rr_q[2]
       [1]), .B0 (n_155), .B1 (n_169), .Y (n_170));
  AOI211XL g10072__2883(.A0 (n_153), .A1 (n_167), .B0 (n_166), .C0
       (\local_rr_q[2] [0]), .Y (n_168));
  INVX1 g10091(.A (n_164), .Y (n_165));
  OAI33X1 g10069__2346(.A0 (n_140), .A1 (n_148), .A2 (\local_rr_q[0]
       [1]), .B0 (n_160), .B1 (n_161), .B2 (\local_rr_q[1] [1]), .Y
       (n_163));
  AOI211XL g10076__1666(.A0 (n_101), .A1 (n_161), .B0 (n_160), .C0
       (\local_rr_q[1] [0]), .Y (n_162));
  NOR2BXL g10073__7410(.AN (n_158), .B (n_157), .Y (n_159));
  NAND3BX1 g10098__6417(.AN (n_150), .B (n_152), .C (n_167), .Y
       (n_164));
  DFFRHQX1 \out_addr_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_135), .Q
       (out_addr[3]));
  INVX1 g10080(.A (n_155), .Y (n_156));
  NAND4BXL g10079__5477(.AN (n_153), .B (n_152), .C (n_167), .D
       (\local_rr_q[2] [1]), .Y (n_154));
  OR4X2 g10077__2398(.A (n_160), .B (n_147), .C (n_145), .D (n_60), .Y
       (n_151));
  NAND4X1 g10082__5107(.A (n_152), .B (n_150), .C (n_167), .D (n_97),
       .Y (n_176));
  NOR2X1 g10087__6260(.A (n_166), .B (n_197), .Y (n_207));
  NAND4X1 g10074__4319(.A (n_144), .B (n_102), .C (n_148), .D
       (\local_rr_q[0] [1]), .Y (n_149));
  NAND3BX1 g10096__8428(.AN (n_100), .B (n_146), .C (n_161), .Y
       (n_172));
  NAND3BX1 g10094__5526(.AN (n_147), .B (n_146), .C (n_145), .Y
       (n_171));
  NAND3BX1 g10099__6783(.AN (n_138), .B (n_144), .C (n_148), .Y
       (n_174));
  INVX1 g10081(.A (n_200), .Y (n_143));
  AOI211XL g10078__3680(.A0 (n_111), .A1 (n_96), .B0 (n_137), .C0
       (\local_rr_q[3] [0]), .Y (n_142));
  AOI21X1 g10092__1617(.A0 (n_103), .A1 (n_148), .B0 (n_140), .Y
       (n_141));
  NAND3X1 g10083__2802(.A (n_139), .B (n_136), .C (n_99), .Y (n_155));
  NAND3X1 g10097__1705(.A (n_144), .B (n_138), .C (n_98), .Y (n_157));
  NOR3X1 g10095__5122(.A (n_137), .B (n_136), .C (n_110), .Y (n_188));
  DFFRHQX1 \out_addr_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_130), .Q
       (out_addr[2]));
  INVX1 g10107(.A (n_152), .Y (n_166));
  INVXL g10090(.A (n_133), .Y (n_135));
  NOR2X1 g10085__8246(.A (n_137), .B (n_197), .Y (n_205));
  NAND2X1 g10088__7098(.A (n_146), .B (n_134), .Y (n_200));
  NAND2X1 g10086__6131(.A (n_144), .B (n_134), .Y (n_202));
  INVX1 g10100(.A (n_137), .Y (n_139));
  INVX1 g10102(.A (n_144), .Y (n_140));
  INVX1 g10101(.A (n_146), .Y (n_160));
  AOI22X1 g10093__1881(.A0 (n_131), .A1 (n_134), .B0 (n_197), .B1
       (out_addr[3]), .Y (n_133));
  NAND2X1 g10103__5115(.A (n_132), .B (n_129), .Y (n_195));
  NOR2X1 g10111__7482(.A (n_132), .B (n_191), .Y (n_152));
  DFFRX1 \group_rr_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_128), .Q
       (n_109), .QN (group_rr_q[0]));
  NAND2X1 g10104__4733(.A (n_131), .B (n_191), .Y (n_137));
  NOR2X1 g10105__6161(.A (n_131), .B (n_190), .Y (n_146));
  OAI2BB2X1 g10108__9315(.A0N (out_addr[2]), .A1N (n_197), .B0 (n_190),
       .B1 (n_197), .Y (n_130));
  NAND2X1 g10110__9945(.A (n_131), .B (n_129), .Y (n_196));
  NOR2X1 g10106__2883(.A (n_131), .B (n_191), .Y (n_144));
  OAI22XL g10109__2346(.A0 (n_191), .A1 (n_197), .B0 (n_134), .B1
       (group_rr_q[0]), .Y (n_128));
  INVX1 g10112(.A (n_131), .Y (n_132));
  OAI21XL g10113__1666(.A0 (n_126), .A1 (n_124), .B0 (n_119), .Y
       (n_131));
  INVX1 g10114(.A (n_191), .Y (n_190));
  OAI2BB2X1 g10115__7410(.A0N (group_rr_q[0]), .A1N (n_127), .B0
       (n_127), .B1 (group_rr_q[0]), .Y (n_191));
  AOI21X1 g10116__6417(.A0 (n_121), .A1 (n_125), .B0 (n_117), .Y
       (n_126));
  DFFRHQX1 out_valid_q_reg(.RN (rst_n), .CK (clk), .D (n_123), .Q
       (out_valid));
  INVX1 g10120(.A (n_197), .Y (n_134));
  AOI21X1 g10118__5477(.A0 (n_125), .A1 (n_120), .B0 (n_124), .Y
       (n_127));
  NAND2XL g10119__2398(.A (n_129), .B (n_122), .Y (n_123));
  NAND2BX1 g10122__5107(.AN (n_122), .B (n_129), .Y (n_197));
  MXI2X1 g10121__6260(.S0 (n_120), .B (group_rr_q[1]), .A (n_114), .Y
       (n_121));
  NOR3X1 g10125__4319(.A (n_120), .B (n_115), .C (n_118), .Y (n_122));
  OAI21XL g10123__8428(.A0 (n_116), .A1 (group_rr_q[1]), .B0 (n_119),
       .Y (n_124));
  AOI21X1 g10124__5526(.A0 (n_118), .A1 (n_257), .B0 (n_117), .Y
       (n_125));
  NAND2BX1 g10129__6783(.AN (n_113), .B (n_116), .Y (n_120));
  AND2X2 g10126__3680(.A (n_115), .B (n_114), .Y (n_117));
  NAND2X1 g10127__1617(.A (n_113), .B (group_rr_q[1]), .Y (n_119));
  AOI22X1 g10131__2802(.A0 (n_105), .A1 (group_rr_q[0]), .B0 (n_106),
       .B1 (n_109), .Y (n_116));
  OAI31X1 g10128__1705(.A0 (n_111), .A1 (n_110), .A2 (n_88), .B0
       (n_95), .Y (n_112));
  OAI21XL g10130__5122(.A0 (n_108), .A1 (n_109), .B0 (n_107), .Y
       (n_115));
  OAI22X1 g10132__8246(.A0 (n_108), .A1 (group_rr_q[0]), .B0 (n_107),
       .B1 (n_109), .Y (n_113));
  OAI2BB1X1 g10133__7098(.A0N (group_rr_q[0]), .A1N (n_106), .B0
       (n_104), .Y (n_118));
  INVX1 g10138(.A (n_104), .Y (n_105));
  INVX1 g10134(.A (n_102), .Y (n_103));
  NAND2BX1 g10139__6131(.AN (n_145), .B (n_100), .Y (n_101));
  NAND2X1 g10137__1881(.A (n_161), .B (n_100), .Y (n_147));
  NAND2BX1 g10135__5115(.AN (n_99), .B (n_136), .Y (n_111));
  NOR2BX1 g10136__7482(.AN (n_138), .B (n_98), .Y (n_102));
  NAND2BX1 g10140__4733(.AN (n_97), .B (n_150), .Y (n_153));
  INVXL g10143(.A (n_110), .Y (n_96));
  NOR3X1 g10145__6161(.A (n_84), .B (n_81), .C (n_75), .Y (n_107));
  NAND3BX1 g10144__9315(.AN (n_87), .B (n_145), .C (n_73), .Y (n_106));
  NOR3X1 g10141__9945(.A (n_85), .B (n_93), .C (n_94), .Y (n_104));
  NOR3X1 g10142__2883(.A (n_83), .B (n_89), .C (n_90), .Y (n_108));
  OAI2BB1X1 g10147__2346(.A0N (\local_rr_q[3] [1]), .A1N (n_76), .B0
       (n_95), .Y (n_110));
  AOI22X1 g10149__1666(.A0 (n_94), .A1 (\local_rr_q[0] [1]), .B0
       (n_93), .B1 (n_82), .Y (n_138));
  AOI21X1 g10148__7410(.A0 (n_74), .A1 (n_92), .B0 (n_80), .Y (n_150));
  AOI21X1 g10146__6417(.A0 (n_72), .A1 (n_91), .B0 (n_86), .Y (n_100));
  AOI22X1 g10150__5477(.A0 (n_90), .A1 (\local_rr_q[3] [1]), .B0
       (n_89), .B1 (n_88), .Y (n_136));
  AOI22X1 g10151__2398(.A0 (n_87), .A1 (\local_rr_q[1] [0]), .B0
       (n_86), .B1 (n_91), .Y (n_161));
  INVX1 g10154(.A (n_98), .Y (n_85));
  INVX1 g10158(.A (n_97), .Y (n_84));
  INVX1 g10157(.A (n_99), .Y (n_83));
  AOI22X1 g10152__5107(.A0 (n_78), .A1 (\local_rr_q[0] [1]), .B0
       (n_79), .B1 (n_82), .Y (n_148));
  AOI22X1 g10153__6260(.A0 (n_81), .A1 (\local_rr_q[2] [0]), .B0
       (n_80), .B1 (n_92), .Y (n_167));
  NAND2X1 g10155__4319(.A (n_77), .B (n_88), .Y (n_95));
  NOR2X1 g10156__8428(.A (n_79), .B (n_78), .Y (n_98));
  NOR2X1 g10159__5526(.A (n_77), .B (n_76), .Y (n_99));
  AOI21X1 g10160__6783(.A0 (n_75), .A1 (n_92), .B0 (n_74), .Y (n_97));
  AOI2BB1X1 g10161__3680(.A0N (n_73), .A1N (\local_rr_q[1] [0]), .B0
       (n_72), .Y (n_145));
  OAI21XL g10168__1617(.A0 (n_71), .A1 (n_68), .B0 (n_70), .Y (n_94));
  OAI21XL g10163__2802(.A0 (n_69), .A1 (n_68), .B0 (n_67), .Y (n_93));
  OAI21XL g10164__1705(.A0 (n_66), .A1 (\local_rr_q[3] [0]), .B0
       (n_65), .Y (n_90));
  OAI21XL g10165__5122(.A0 (n_64), .A1 (\local_rr_q[3] [0]), .B0
       (n_63), .Y (n_89));
  OAI22X1 g10166__8246(.A0 (n_66), .A1 (n_62), .B0 (n_63), .B1
       (\local_rr_q[3] [0]), .Y (n_77));
  OAI22X1 g10167__7098(.A0 (n_64), .A1 (n_62), .B0 (n_65), .B1
       (\local_rr_q[3] [0]), .Y (n_76));
  OAI22X1 g10162__6131(.A0 (n_71), .A1 (\local_rr_q[0] [0]), .B0
       (n_67), .B1 (n_68), .Y (n_79));
  OAI22X1 g10175__1881(.A0 (n_69), .A1 (\local_rr_q[0] [0]), .B0
       (n_70), .B1 (n_68), .Y (n_78));
  OAI22X1 g10170__5115(.A0 (n_61), .A1 (n_60), .B0 (n_59), .B1
       (\local_rr_q[1] [1]), .Y (n_86));
  OAI22X1 g10171__7482(.A0 (n_58), .A1 (n_53), .B0 (n_57), .B1
       (\local_rr_q[2] [1]), .Y (n_80));
  OAI22X1 g10172__4733(.A0 (n_56), .A1 (n_60), .B0 (n_55), .B1
       (\local_rr_q[1] [1]), .Y (n_72));
  OAI22X1 g10173__6161(.A0 (n_55), .A1 (n_60), .B0 (n_56), .B1
       (\local_rr_q[1] [1]), .Y (n_87));
  OAI22X1 g10174__9315(.A0 (n_54), .A1 (n_53), .B0 (n_52), .B1
       (\local_rr_q[2] [1]), .Y (n_81));
  OAI22X1 g10169__9945(.A0 (n_52), .A1 (n_53), .B0 (n_54), .B1
       (\local_rr_q[2] [1]), .Y (n_74));
  DFFRHQX1 \ack_q_reg[8] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (src_ack_async[8]));
  DFFRHQX1 \ack_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_29), .Q
       (src_ack_async[2]));
  DFFRHQX1 \ack_q_reg[15] (.RN (rst_n), .CK (clk), .D (n_48), .Q
       (src_ack_async[15]));
  DFFRHQX1 \ack_q_reg[13] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (src_ack_async[13]));
  DFFRHQX1 \ack_q_reg[6] (.RN (rst_n), .CK (clk), .D (n_39), .Q
       (src_ack_async[6]));
  DFFRHQX1 \ack_q_reg[7] (.RN (rst_n), .CK (clk), .D (n_27), .Q
       (src_ack_async[7]));
  DFFRHQX1 \ack_q_reg[5] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (src_ack_async[5]));
  DFFRHQX1 \ack_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (src_ack_async[1]));
  DFFRHQX1 \ack_q_reg[4] (.RN (rst_n), .CK (clk), .D (n_23), .Q
       (src_ack_async[4]));
  NAND2X1 g10177__2883(.A (n_57), .B (n_58), .Y (n_75));
  DFFRHQX1 \ack_q_reg[9] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (src_ack_async[9]));
  DFFRHQX1 \ack_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (src_ack_async[0]));
  DFFRHQX1 \ack_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_50), .Q
       (src_ack_async[3]));
  DFFRHQX1 \ack_q_reg[10] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (src_ack_async[10]));
  DFFRHQX1 \ack_q_reg[12] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (src_ack_async[12]));
  DFFRHQX1 \ack_q_reg[11] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (src_ack_async[11]));
  AND2X2 g10176__2346(.A (n_59), .B (n_61), .Y (n_73));
  DFFRHQX1 \ack_q_reg[14] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (src_ack_async[14]));
  AOI21XL g10223__1666(.A0 (n_20), .A1 (pending_q[1]), .B0 (n_3), .Y
       (n_51));
  AOI21XL g10225__7410(.A0 (n_49), .A1 (pending_q[3]), .B0 (n_8), .Y
       (n_50));
  AOI21X1 g10194__6417(.A0 (n_38), .A1 (req_sync_q[6]), .B0
       (pending_q[6]), .Y (n_56));
  AOI21X1 g10195__5477(.A0 (n_28), .A1 (req_sync_q[2]), .B0
       (pending_q[2]), .Y (n_71));
  AOI21X1 g10196__2398(.A0 (n_49), .A1 (req_sync_q[3]), .B0
       (pending_q[3]), .Y (n_67));
  AOI21X1 g10197__5107(.A0 (n_42), .A1 (req_sync_q[0]), .B0
       (pending_q[0]), .Y (n_69));
  AOI21X1 g10198__6260(.A0 (n_26), .A1 (req_sync_q[7]), .B0
       (pending_q[7]), .Y (n_59));
  AOI21X1 g10199__4319(.A0 (n_24), .A1 (req_sync_q[5]), .B0
       (pending_q[5]), .Y (n_61));
  AOI21X1 g10200__8428(.A0 (n_22), .A1 (req_sync_q[4]), .B0
       (pending_q[4]), .Y (n_55));
  AOI21X1 g10201__5526(.A0 (n_34), .A1 (req_sync_q[11]), .B0
       (pending_q[11]), .Y (n_57));
  AOI21X1 g10202__6783(.A0 (n_40), .A1 (req_sync_q[9]), .B0
       (pending_q[9]), .Y (n_58));
  AOI21X1 g10203__3680(.A0 (n_30), .A1 (req_sync_q[10]), .B0
       (pending_q[10]), .Y (n_52));
  AOI21X1 g10204__1617(.A0 (n_36), .A1 (req_sync_q[8]), .B0
       (pending_q[8]), .Y (n_54));
  AOI21X1 g10205__2802(.A0 (n_44), .A1 (req_sync_q[13]), .B0
       (pending_q[13]), .Y (n_65));
  AOI21X1 g10206__1705(.A0 (n_32), .A1 (req_sync_q[14]), .B0
       (pending_q[14]), .Y (n_66));
  AOI21X1 g10207__5122(.A0 (n_47), .A1 (req_sync_q[15]), .B0
       (pending_q[15]), .Y (n_63));
  AOI21XL g10224__8246(.A0 (n_47), .A1 (pending_q[15]), .B0 (n_7), .Y
       (n_48));
  AOI21XL g10222__7098(.A0 (n_21), .A1 (pending_q[12]), .B0 (n_12), .Y
       (n_46));
  AOI21XL g10210__6131(.A0 (n_44), .A1 (pending_q[13]), .B0 (n_14), .Y
       (n_45));
  AOI21XL g10211__1881(.A0 (n_42), .A1 (pending_q[0]), .B0 (n_2), .Y
       (n_43));
  AOI21XL g10212__5115(.A0 (n_40), .A1 (pending_q[9]), .B0 (n_9), .Y
       (n_41));
  AOI21XL g10213__7482(.A0 (n_38), .A1 (pending_q[6]), .B0 (n_15), .Y
       (n_39));
  AOI21XL g10214__4733(.A0 (n_36), .A1 (pending_q[8]), .B0 (n_4), .Y
       (n_37));
  AOI21XL g10215__6161(.A0 (n_34), .A1 (pending_q[11]), .B0 (n_11), .Y
       (n_35));
  AOI21XL g10216__9315(.A0 (n_32), .A1 (pending_q[14]), .B0 (n_18), .Y
       (n_33));
  AOI21XL g10217__9945(.A0 (n_30), .A1 (pending_q[10]), .B0 (n_13), .Y
       (n_31));
  AOI21XL g10218__2883(.A0 (n_28), .A1 (pending_q[2]), .B0 (n_10), .Y
       (n_29));
  AOI21XL g10219__2346(.A0 (n_26), .A1 (pending_q[7]), .B0 (n_16), .Y
       (n_27));
  AOI21XL g10220__1666(.A0 (n_24), .A1 (pending_q[5]), .B0 (n_17), .Y
       (n_25));
  AOI21XL g10221__7410(.A0 (n_22), .A1 (pending_q[4]), .B0 (n_19), .Y
       (n_23));
  AOI21X1 g10208__6417(.A0 (n_21), .A1 (req_sync_q[12]), .B0
       (pending_q[12]), .Y (n_64));
  AOI21X1 g10209__5477(.A0 (n_20), .A1 (req_sync_q[1]), .B0
       (pending_q[1]), .Y (n_70));
  INVX1 g10246(.A (req_sync_q[4]), .Y (n_19));
  INVX1 g10226(.A (req_sync_q[14]), .Y (n_18));
  INVX1 g10228(.A (req_sync_q[5]), .Y (n_17));
  INVX1 g10229(.A (req_sync_q[7]), .Y (n_16));
  INVX1 g10230(.A (req_sync_q[6]), .Y (n_15));
  INVX1 g10232(.A (req_sync_q[13]), .Y (n_14));
  INVX1 g10233(.A (req_sync_q[10]), .Y (n_13));
  INVX1 g10234(.A (req_sync_q[12]), .Y (n_12));
  INVX1 g10251(.A (req_sync_q[11]), .Y (n_11));
  INVX1 g10235(.A (req_sync_q[2]), .Y (n_10));
  INVX1 g10248(.A (req_sync_q[9]), .Y (n_9));
  INVX1 g10249(.A (req_sync_q[3]), .Y (n_8));
  INVX1 g10250(.A (req_sync_q[15]), .Y (n_7));
  INVXL g10252(.A (n_5), .Y (n_6));
  INVX1 g10247(.A (req_sync_q[8]), .Y (n_4));
  INVX1 g10231(.A (req_sync_q[1]), .Y (n_3));
  INVX1 g10227(.A (req_sync_q[0]), .Y (n_2));
  INVX1 g10253(.A (n_257), .Y (n_114));
  DFFRHQX1 \req_sync_q_reg[14] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[14]), .Q (req_sync_q[14]));
  DFFRHQX1 \req_sync_q_reg[0] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[0]), .Q (req_sync_q[0]));
  DFFRHQX1 \req_sync_q_reg[5] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[5]), .Q (req_sync_q[5]));
  DFFRHQX1 \req_sync_q_reg[6] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[6]), .Q (req_sync_q[6]));
  DFFRHQX1 \req_sync_q_reg[13] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[13]), .Q (req_sync_q[13]));
  DFFRHQX1 \req_sync_q_reg[12] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[12]), .Q (req_sync_q[12]));
  DFFRHQX1 \req_sync_q_reg[4] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[4]), .Q (req_sync_q[4]));
  DFFRHQX1 \req_sync_q_reg[9] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[9]), .Q (req_sync_q[9]));
  DFFRHQX1 \req_sync_q_reg[3] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[3]), .Q (req_sync_q[3]));
  DFFRHQX1 \req_sync_q_reg[15] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[15]), .Q (req_sync_q[15]));
  DFFRHQX1 \req_sync_q_reg[1] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[1]), .Q (req_sync_q[1]));
  AOI22XL g10261__2398(.A0 (\local_rr_q[1] [1]), .A1 (\local_rr_q[1]
       [0]), .B0 (n_91), .B1 (n_60), .Y (n_5));
  OAI22X1 g10262__5107(.A0 (\local_rr_q[0] [0]), .A1 (n_82), .B0
       (n_68), .B1 (\local_rr_q[0] [1]), .Y (n_158));
  AOI22X1 g10263__6260(.A0 (\local_rr_q[2] [1]), .A1 (\local_rr_q[2]
       [0]), .B0 (n_53), .B1 (n_92), .Y (n_179));
  AOI22X1 g10260__8428(.A0 (\local_rr_q[3] [0]), .A1 (\local_rr_q[3]
       [1]), .B0 (n_62), .B1 (n_88), .Y (n_169));
  DFFRHQX1 \req_sync_q_reg[11] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[11]), .Q (req_sync_q[11]));
  DFFRHQX1 \req_sync_q_reg[8] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[8]), .Q (req_sync_q[8]));
  DFFRHQX1 \req_sync_q_reg[2] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[2]), .Q (req_sync_q[2]));
  DFFRHQX1 \req_sync_q_reg[10] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[10]), .Q (req_sync_q[10]));
  DFFRHQX1 \req_sync_q_reg[7] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[7]), .Q (req_sync_q[7]));
  DFFRHQX1 \req_meta_q_reg[0] (.RN (rst_n), .CK (clk), .D
       (src_req_async[0]), .Q (req_meta_q[0]));
  DFFRHQX1 \req_meta_q_reg[10] (.RN (rst_n), .CK (clk), .D
       (src_req_async[10]), .Q (req_meta_q[10]));
  DFFRHQX1 \req_meta_q_reg[6] (.RN (rst_n), .CK (clk), .D
       (src_req_async[6]), .Q (req_meta_q[6]));
  DFFRHQX1 \req_meta_q_reg[15] (.RN (rst_n), .CK (clk), .D
       (src_req_async[15]), .Q (req_meta_q[15]));
  DFFRHQX1 \req_meta_q_reg[3] (.RN (rst_n), .CK (clk), .D
       (src_req_async[3]), .Q (req_meta_q[3]));
  DFFRHQX1 \req_meta_q_reg[9] (.RN (rst_n), .CK (clk), .D
       (src_req_async[9]), .Q (req_meta_q[9]));
  DFFRHQX1 \req_meta_q_reg[12] (.RN (rst_n), .CK (clk), .D
       (src_req_async[12]), .Q (req_meta_q[12]));
  DFFRHQX1 \req_meta_q_reg[14] (.RN (rst_n), .CK (clk), .D
       (src_req_async[14]), .Q (req_meta_q[14]));
  DFFRHQX1 \req_meta_q_reg[8] (.RN (rst_n), .CK (clk), .D
       (src_req_async[8]), .Q (req_meta_q[8]));
  DFFRHQX1 \req_meta_q_reg[7] (.RN (rst_n), .CK (clk), .D
       (src_req_async[7]), .Q (req_meta_q[7]));
  DFFRHQX1 \req_meta_q_reg[5] (.RN (rst_n), .CK (clk), .D
       (src_req_async[5]), .Q (req_meta_q[5]));
  DFFRHQX1 \req_meta_q_reg[4] (.RN (rst_n), .CK (clk), .D
       (src_req_async[4]), .Q (req_meta_q[4]));
  DFFRHQX1 \req_meta_q_reg[11] (.RN (rst_n), .CK (clk), .D
       (src_req_async[11]), .Q (req_meta_q[11]));
  DFFRHQX1 \req_meta_q_reg[1] (.RN (rst_n), .CK (clk), .D
       (src_req_async[1]), .Q (req_meta_q[1]));
  DFFRHQX1 \req_meta_q_reg[13] (.RN (rst_n), .CK (clk), .D
       (src_req_async[13]), .Q (req_meta_q[13]));
  DFFRHQX1 \req_meta_q_reg[2] (.RN (rst_n), .CK (clk), .D
       (src_req_async[2]), .Q (req_meta_q[2]));
  NAND2BX1 g10281__5526(.AN (out_ready), .B (out_valid), .Y (n_129));
  INVX1 g10298(.A (src_ack_async[13]), .Y (n_44));
  INVX1 g10285(.A (src_ack_async[15]), .Y (n_47));
  INVX1 g10288(.A (src_ack_async[9]), .Y (n_40));
  INVX1 g10293(.A (src_ack_async[8]), .Y (n_36));
  INVX1 g10295(.A (src_ack_async[0]), .Y (n_42));
  INVX1 g10297(.A (src_ack_async[11]), .Y (n_34));
  INVX1 g10305(.A (\local_rr_q[0] [0]), .Y (n_68));
  INVX1 g10301(.A (src_ack_async[12]), .Y (n_21));
  INVX1 g10287(.A (src_ack_async[4]), .Y (n_22));
  INVX1 g10282(.A (src_ack_async[14]), .Y (n_32));
  INVX1 g10300(.A (src_ack_async[10]), .Y (n_30));
  INVX1 g10299(.A (src_ack_async[6]), .Y (n_38));
  INVX1 g10284(.A (src_ack_async[2]), .Y (n_28));
  INVX1 g10286(.A (src_ack_async[5]), .Y (n_24));
  INVX1 g10294(.A (src_ack_async[1]), .Y (n_20));
  INVX1 g10283(.A (src_ack_async[7]), .Y (n_26));
  INVX1 g10296(.A (src_ack_async[3]), .Y (n_49));
  MXI2XL g2(.S0 (group_rr_q[1]), .B (group_rr_q[0]), .A (n_109), .Y
       (n_257));
endmodule

