/*
###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64 (host sanitized)
#  Generated on:      Wed Aug 19 15:27:25 2026
#  Design:            aer_traditional
#  Command:           saveNetlist outputs/aer_traditional_postroute.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 19 2026 15:24:04 KST (Aug 19 2026 06:24:04 UTC)
// Verification Directory fv/aer_traditional 
module aer_traditional (
	clk, 
	rst_n, 
	src_req, 
	src_ack, 
	aer_addr, 
	aer_req, 
	aer_ack);
   input clk;
   input rst_n;
   input [15:0] src_req;
   output [15:0] src_ack;
   output [3:0] aer_addr;
   output aer_req;
   input aer_ack;

   // Internal wires
   wire [1:0] state_q;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_15;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_44;
   wire n_47;
   wire n_52;
   wire n_54;
   wire n_56;
   wire n_58;
   wire n_60;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;

   DFFRHQX1 \state_q_reg[0]  (.D(n_88),
	.CK(clk),
	.RN(rst_n),
	.Q(state_q[0]));
   NAND2XL g2761__2398 (.A(n_86),
	.B(n_84),
	.Y(n_88));
   DFFRHQX1 \grant_q_reg[2]  (.D(n_87),
	.CK(clk),
	.RN(rst_n),
	.Q(aer_addr[2]));
   DFFRHQX1 \grant_q_reg[3]  (.D(n_83),
	.CK(clk),
	.RN(rst_n),
	.Q(aer_addr[3]));
   DFFRHQX1 \grant_q_reg[1]  (.D(n_82),
	.CK(clk),
	.RN(rst_n),
	.Q(aer_addr[1]));
   INVXL g2753 (.A(n_85),
	.Y(n_87));
   AOI22X1 g2765__5107 (.A0(n_75),
	.A1(n_18),
	.B0(n_8),
	.B1(state_q[0]),
	.Y(n_86));
   DFFRHQX1 \grant_q_reg[0]  (.D(n_81),
	.CK(clk),
	.RN(rst_n),
	.Q(aer_addr[0]));
   AOI21X1 g2754__6260 (.A0(n_84),
	.A1(aer_addr[2]),
	.B0(n_78),
	.Y(n_85));
   INVXL g2756 (.A(n_80),
	.Y(n_83));
   OAI2BB1X1 g2758__4319 (.A0N(aer_addr[1]),
	.A1N(n_84),
	.B0(n_76),
	.Y(n_82));
   OAI32XL g2757__8428 (.A0(n_84),
	.A1(n_72),
	.A2(src_req[0]),
	.B0(n_79),
	.B1(n_74),
	.Y(n_81));
   AOI22X1 g2759__5526 (.A0(n_79),
	.A1(n_77),
	.B0(n_84),
	.B1(aer_addr[3]),
	.Y(n_80));
   AOI211XL g2760__6783 (.A0(n_77),
	.A1(n_37),
	.B0(n_84),
	.C0(n_71),
	.Y(n_78));
   OR4X1 g2762__3680 (.A(n_84),
	.B(n_69),
	.C(src_req[0]),
	.D(src_req[1]),
	.Y(n_76));
   AOI22X1 g2768__1617 (.A0(n_73),
	.A1(aer_addr[0]),
	.B0(n_70),
	.B1(n_74),
	.Y(n_75));
   INVX1 g2763 (.A(n_84),
	.Y(n_79));
   OAI221XL g2772__2802 (.A0(n_32),
	.A1(aer_addr[3]),
	.B0(n_62),
	.B1(aer_addr[1]),
	.C0(n_21),
	.Y(n_73));
   OR4X2 g2764__1705 (.A(n_68),
	.B(state_q[1]),
	.C(state_q[0]),
	.D(aer_ack),
	.Y(n_84));
   OAI221XL g2769__5122 (.A0(n_71),
	.A1(n_12),
	.B0(n_4),
	.B1(src_req[1]),
	.C0(n_52),
	.Y(n_72));
   OR2X2 g2783__8246 (.A(n_40),
	.B(n_41),
	.Y(n_70));
   AOI21X1 g2766__7098 (.A0(n_39),
	.A1(n_17),
	.B0(n_71),
	.Y(n_69));
   NOR4X1 g2767__6131 (.A(n_38),
	.B(n_71),
	.C(src_req[6]),
	.D(src_req[12]),
	.Y(n_68));
   NOR2XL g2777__1881 (.A(n_58),
	.B(n_63),
	.Y(src_ack[10]));
   NOR2BXL g2779__5115 (.AN(n_64),
	.B(n_60),
	.Y(src_ack[7]));
   NOR2BXL g2790__7482 (.AN(n_64),
	.B(n_63),
	.Y(src_ack[3]));
   AOI221XL g2799__4733 (.A0(n_27),
	.A1(src_req[9]),
	.B0(n_28),
	.B1(src_req[5]),
	.C0(n_33),
	.Y(n_62));
   NOR2BXL g2785__6161 (.AN(n_56),
	.B(n_60),
	.Y(src_ack[15]));
   NOR2XL g2773__9315 (.A(n_58),
	.B(n_60),
	.Y(src_ack[14]));
   NOR2BXL g2787__9945 (.AN(n_56),
	.B(n_54),
	.Y(src_ack[13]));
   NOR2XL g2781__2883 (.A(n_58),
	.B(n_54),
	.Y(src_ack[12]));
   NOR2BXL g2786__2346 (.AN(n_56),
	.B(n_63),
	.Y(src_ack[11]));
   OAI21XL g2770__1666 (.A0(n_31),
	.A1(src_req[8]),
	.B0(n_77),
	.Y(n_52));
   NOR2BXL g2778__7410 (.AN(n_44),
	.B(n_58),
	.Y(src_ack[8]));
   NOR2XL g2784__6417 (.A(n_47),
	.B(n_60),
	.Y(src_ack[6]));
   NOR2BXL g2780__5477 (.AN(n_64),
	.B(n_54),
	.Y(src_ack[5]));
   NOR2XL g2788__2398 (.A(n_47),
	.B(n_54),
	.Y(src_ack[4]));
   NOR2XL g2789__5107 (.A(n_47),
	.B(n_63),
	.Y(src_ack[2]));
   AND2XL g2774__6260 (.A(n_64),
	.B(n_44),
	.Y(src_ack[1]));
   NOR2BXL g2775__4319 (.AN(n_44),
	.B(n_47),
	.Y(src_ack[0]));
   AND2XL g2776__8428 (.A(n_56),
	.B(n_44),
	.Y(src_ack[9]));
   DFFRHQX1 \state_q_reg[1]  (.D(n_30),
	.CK(clk),
	.RN(rst_n),
	.Q(state_q[1]));
   AOI21X1 g2795__5526 (.A0(n_29),
	.A1(n_26),
	.B0(aer_addr[1]),
	.Y(n_41));
   AOI21X1 g2797__6783 (.A0(n_19),
	.A1(n_22),
	.B0(n_5),
	.Y(n_40));
   OAI31X1 g2771__3680 (.A0(n_15),
	.A1(src_req[8]),
	.A2(src_req[9]),
	.B0(n_77),
	.Y(n_39));
   OR4X2 g2782__1617 (.A(n_13),
	.B(n_37),
	.C(src_req[13]),
	.D(src_req[7]),
	.Y(n_38));
   NOR2X1 g2791__2802 (.A(n_36),
	.B(aer_addr[3]),
	.Y(n_64));
   NAND2X1 g2792__1705 (.A(n_35),
	.B(aer_addr[3]),
	.Y(n_58));
   NOR2X1 g2793__5122 (.A(n_36),
	.B(n_34),
	.Y(n_56));
   NAND2X1 g2798__8246 (.A(n_35),
	.B(n_34),
	.Y(n_47));
   INVX1 g2811 (.A(n_25),
	.Y(n_33));
   AOI22X1 g2816__7098 (.A0(n_10),
	.A1(src_req[3]),
	.B0(n_20),
	.B1(src_req[7]),
	.Y(n_32));
   OAI22X1 g2796__6131 (.A0(n_37),
	.A1(n_11),
	.B0(n_2),
	.B1(src_req[9]),
	.Y(n_31));
   OAI2BB1X1 g2802__1881 (.A0N(aer_ack),
	.A1N(state_q[0]),
	.B0(n_9),
	.Y(n_30));
   AOI22X1 g2814__5115 (.A0(n_28),
	.A1(src_req[4]),
	.B0(n_27),
	.B1(src_req[8]),
	.Y(n_29));
   AOI22X1 g2813__7482 (.A0(n_24),
	.A1(src_req[0]),
	.B0(n_23),
	.B1(src_req[12]),
	.Y(n_26));
   AOI22X1 g2812__4733 (.A0(n_24),
	.A1(src_req[1]),
	.B0(n_23),
	.B1(src_req[13]),
	.Y(n_25));
   AOI22X1 g2815__6161 (.A0(n_24),
	.A1(src_req[2]),
	.B0(n_23),
	.B1(src_req[14]),
	.Y(n_22));
   AOI33X1 g2803__9315 (.A0(n_27),
	.A1(aer_addr[1]),
	.A2(src_req[11]),
	.B0(n_20),
	.B1(aer_addr[3]),
	.B2(src_req[15]),
	.Y(n_21));
   AOI22X1 g2808__9945 (.A0(n_28),
	.A1(src_req[6]),
	.B0(n_27),
	.B1(src_req[10]),
	.Y(n_19));
   NAND2X1 g2801__2883 (.A(n_18),
	.B(aer_addr[0]),
	.Y(n_36));
   AND2X2 g2800__2346 (.A(n_18),
	.B(n_74),
	.Y(n_35));
   NOR4BX1 g2805__1666 (.AN(n_17),
	.B(n_71),
	.C(src_req[6]),
	.D(src_req[7]),
	.Y(n_77));
   OAI21XL g2819__7410 (.A0(n_7),
	.A1(state_q[1]),
	.B0(n_9),
	.Y(aer_req));
   AOI2BB1XL g2804__6417 (.A0N(src_req[13]),
	.A1N(src_req[12]),
	.B0(n_37),
	.Y(n_15));
   NAND3BX1 g2807__5477 (.AN(src_req[14]),
	.B(n_17),
	.C(n_3),
	.Y(n_13));
   AOI21XL g2817__2398 (.A0(n_0),
	.A1(src_req[6]),
	.B0(src_req[4]),
	.Y(n_12));
   AOI21X1 g2818__5107 (.A0(n_1),
	.A1(src_req[14]),
	.B0(src_req[12]),
	.Y(n_11));
   INVX1 g2828 (.A(n_63),
	.Y(n_10));
   INVX1 g2821 (.A(n_9),
	.Y(n_18));
   OAI2BB2XL g2820__6260 (.A0N(aer_ack),
	.A1N(state_q[1]),
	.B0(state_q[1]),
	.B1(aer_ack),
	.Y(n_8));
   INVX1 g2822 (.A(n_60),
	.Y(n_20));
   NAND2X1 g2826__4319 (.A(n_7),
	.B(state_q[1]),
	.Y(n_9));
   NOR2X1 g2824__8428 (.A(n_34),
	.B(n_6),
	.Y(n_23));
   OR4X2 g2810__5526 (.A(src_req[0]),
	.B(src_req[1]),
	.C(src_req[3]),
	.D(src_req[2]),
	.Y(n_71));
   NOR2X1 g2829__6783 (.A(aer_addr[3]),
	.B(n_6),
	.Y(n_28));
   NAND2X1 g2831__3680 (.A(n_5),
	.B(aer_addr[2]),
	.Y(n_54));
   NOR2X1 g2832__1617 (.A(n_34),
	.B(aer_addr[2]),
	.Y(n_27));
   OR4X2 g2809__2802 (.A(src_req[8]),
	.B(src_req[9]),
	.C(src_req[11]),
	.D(src_req[10]),
	.Y(n_37));
   NAND2X1 g2833__1705 (.A(n_6),
	.B(aer_addr[1]),
	.Y(n_63));
   NOR2X1 g2823__5122 (.A(aer_addr[3]),
	.B(aer_addr[2]),
	.Y(n_24));
   NOR2X1 g2825__8246 (.A(aer_addr[1]),
	.B(aer_addr[2]),
	.Y(n_44));
   NOR2X1 g2830__7098 (.A(src_req[5]),
	.B(src_req[4]),
	.Y(n_17));
   NAND2X1 g2827__6131 (.A(aer_addr[1]),
	.B(aer_addr[2]),
	.Y(n_60));
   INVX1 g2840 (.A(src_req[2]),
	.Y(n_4));
   INVX1 g2834 (.A(src_req[15]),
	.Y(n_3));
   INVX1 g2839 (.A(aer_addr[1]),
	.Y(n_5));
   INVX1 g2837 (.A(state_q[0]),
	.Y(n_7));
   INVX1 g2843 (.A(aer_addr[3]),
	.Y(n_34));
   INVX1 g2835 (.A(src_req[10]),
	.Y(n_2));
   INVX1 g2841 (.A(src_req[13]),
	.Y(n_1));
   INVX1 g2836 (.A(src_req[5]),
	.Y(n_0));
   INVX1 g2838 (.A(aer_addr[0]),
	.Y(n_74));
   INVX1 g2842 (.A(aer_addr[2]),
	.Y(n_6));
endmodule
