/*
###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID <REMOTE_HOST>)
#  Generated on:      Wed Aug 26 16:59:42 2026
#  Design:            aer_pending_xor1_rank_reuse_sync_core_reset
#  Command:           saveNetlist <REMOTE_WORKSPACE>/pnr/p10xor1_h020v4/outputs/aer_pending_xor1_rank_reuse_sync_core_reset_postroute.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 26 2026 14:51:44 KST (Aug 26 2026 05:51:44 UTC)
// Verification Directory fv/aer_pending_xor1_rank_reuse_sync_core_reset 
module aer_pending_xor1_rank_reuse_sync_core_reset (
	clk, 
	rst_n, 
	src_req_async, 
	src_ack_async, 
	out_addr, 
	out_valid, 
	out_ready);
   input clk;
   input rst_n;
   input [15:0] src_req_async;
   output [15:0] src_ack_async;
   output [3:0] out_addr;
   output out_valid;
   input out_ready;

   // Internal wires
   wire FE_PHN11_rst_n;
   wire FE_OFN11_n_103;
   wire FE_OFN10_n_103;
   wire FE_OFN9_n_90;
   wire FE_OFN4_n_163;
   wire FE_OFN2_n_97;
   wire FE_OFN1_n_92;
   wire [15:0] pending_rank_q;
   wire [3:0] out_rank_q;
   wire [15:0] ack_rank_q;
   wire [15:0] ack_source;
   wire [15:0] req_rank;
   wire [15:0] req_sync_q;
   wire [1:0] reset_release_q;
   wire [15:0] req_meta_q;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_25;
   wire n_29;
   wire n_36;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_52;
   wire n_54;
   wire n_55;
   wire n_57;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_235;
   wire out_valid_q;

   DLY3X1 FE_PHC11_rst_n (.Y(FE_PHN11_rst_n),
	.A(rst_n));
   BUFX2 FE_OFC11_n_103 (.Y(FE_OFN11_n_103),
	.A(n_103));
   BUFX2 FE_OFC10_n_103 (.Y(FE_OFN10_n_103),
	.A(FE_OFN11_n_103));
   BUFX2 FE_OFC9_n_90 (.Y(FE_OFN9_n_90),
	.A(n_90));
   BUFX2 FE_OFC4_n_163 (.Y(FE_OFN4_n_163),
	.A(n_163));
   BUFX2 FE_OFC2_n_97 (.Y(FE_OFN2_n_97),
	.A(n_97));
   BUFX2 FE_OFC1_n_92 (.Y(FE_OFN1_n_92),
	.A(n_92));
   DFFQXL \pending_rank_q_reg[0]  (.Q(pending_rank_q[0]),
	.D(n_167),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[1]  (.Q(pending_rank_q[1]),
	.D(n_189),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[2]  (.Q(pending_rank_q[2]),
	.D(n_178),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[3]  (.Q(pending_rank_q[3]),
	.D(n_166),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[4]  (.Q(pending_rank_q[4]),
	.D(n_175),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[5]  (.Q(pending_rank_q[5]),
	.D(n_181),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[6]  (.Q(pending_rank_q[6]),
	.D(n_180),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[7]  (.Q(pending_rank_q[7]),
	.D(n_183),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[8]  (.Q(pending_rank_q[8]),
	.D(n_184),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[9]  (.Q(pending_rank_q[9]),
	.D(n_187),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[10]  (.Q(pending_rank_q[10]),
	.D(n_173),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[11]  (.Q(pending_rank_q[11]),
	.D(n_188),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[12]  (.Q(pending_rank_q[12]),
	.D(n_171),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[13]  (.Q(pending_rank_q[13]),
	.D(n_170),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[14]  (.Q(pending_rank_q[14]),
	.D(n_168),
	.CK(clk));
   DFFQXL \pending_rank_q_reg[15]  (.Q(pending_rank_q[15]),
	.D(n_169),
	.CK(clk));
   DFFHQX1 \out_rank_q_reg[0]  (.Q(out_rank_q[0]),
	.D(n_165),
	.CK(clk));
   AOI21XL g6835__2398 (.Y(n_189),
	.A0(n_186),
	.A1(n_182),
	.B0(n_136));
   AOI21XL g6847__5107 (.Y(n_188),
	.A0(n_177),
	.A1(n_185),
	.B0(n_87));
   AOI21XL g6848__6260 (.Y(n_187),
	.A0(n_186),
	.A1(n_185),
	.B0(n_133));
   AOI21XL g6836__4319 (.Y(n_184),
	.A0(n_186),
	.A1(n_172),
	.B0(n_130));
   AOI21XL g6846__8428 (.Y(n_183),
	.A0(n_179),
	.A1(n_182),
	.B0(n_85));
   AOI21XL g6837__5526 (.Y(n_181),
	.A0(n_174),
	.A1(n_182),
	.B0(n_135));
   AOI21XL g6838__6783 (.Y(n_180),
	.A0(n_179),
	.A1(n_176),
	.B0(n_121));
   AOI21XL g6833__3680 (.Y(n_178),
	.A0(n_177),
	.A1(n_176),
	.B0(n_118));
   AOI21XL g6832__1617 (.Y(n_175),
	.A0(n_174),
	.A1(n_176),
	.B0(n_124));
   AOI21XL g6841__2802 (.Y(n_173),
	.A0(n_177),
	.A1(n_172),
	.B0(n_119));
   AOI21XL g6842__1705 (.Y(n_171),
	.A0(n_174),
	.A1(n_172),
	.B0(n_125));
   AOI21XL g6843__5122 (.Y(n_170),
	.A0(n_174),
	.A1(n_185),
	.B0(n_132));
   AOI21XL g6840__8246 (.Y(n_169),
	.A0(n_179),
	.A1(n_185),
	.B0(n_86));
   AOI21XL g6844__7098 (.Y(n_168),
	.A0(n_179),
	.A1(n_172),
	.B0(n_122));
   AOI21XL g6834__6131 (.Y(n_167),
	.A0(n_186),
	.A1(n_176),
	.B0(n_128));
   AOI21XL g6845__1881 (.Y(n_166),
	.A0(n_177),
	.A1(n_182),
	.B0(n_88));
   NAND2X1 g6849__5115 (.Y(n_165),
	.A(reset_release_q[1]),
	.B(n_162));
   DFFHQX1 \out_rank_q_reg[1]  (.Q(out_addr[1]),
	.D(n_158),
	.CK(clk));
   OAI21X1 g6850__7482 (.Y(n_176),
	.A0(n_160),
	.A1(n_164),
	.B0(FE_OFN4_n_163));
   OAI21X1 g6851__4733 (.Y(n_172),
	.A0(n_161),
	.A1(n_164),
	.B0(FE_OFN4_n_163));
   AOI22X1 g6853__6161 (.Y(n_162),
	.A0(FE_OFN4_n_163),
	.A1(n_164),
	.B0(out_rank_q[0]),
	.B1(n_159));
   OAI2BB1X1 g6855__9315 (.Y(n_182),
	.A0N(n_161),
	.A1N(n_164),
	.B0(FE_OFN4_n_163));
   OAI2BB1X1 g6854__9945 (.Y(n_185),
	.A0N(n_160),
	.A1N(n_164),
	.B0(FE_OFN4_n_163));
   AOI21X1 g6856__2883 (.Y(n_186),
	.A0(FE_OFN4_n_163),
	.A1(n_156),
	.B0(n_159));
   AOI21X1 g6857__2346 (.Y(n_174),
	.A0(FE_OFN4_n_163),
	.A1(n_153),
	.B0(n_159));
   OAI2BB1X1 g6858__1666 (.Y(n_158),
	.A0N(out_addr[1]),
	.A1N(n_159),
	.B0(n_235));
   AOI21X1 g6860__7410 (.Y(n_179),
	.A0(FE_OFN4_n_163),
	.A1(n_155),
	.B0(n_235));
   AOI21X1 g6859__6417 (.Y(n_177),
	.A0(FE_OFN4_n_163),
	.A1(n_152),
	.B0(n_235));
   NAND2X1 g6861__5477 (.Y(n_164),
	.A(n_149),
	.B(n_151));
   NAND2X1 g6863__5107 (.Y(n_156),
	.A(n_155),
	.B(n_154));
   NAND2X1 g6864__6260 (.Y(n_153),
	.A(n_152),
	.B(n_154));
   AOI32X1 g6865__4319 (.Y(n_151),
	.A0(n_150),
	.A1(n_147),
	.A2(n_146),
	.B0(n_101),
	.B1(n_116));
   OAI2BB1X1 g6866__8428 (.Y(n_154),
	.A0N(n_150),
	.A1N(n_148),
	.B0(n_149));
   NAND2X1 g6868__5526 (.Y(n_148),
	.A(n_147),
	.B(n_145));
   OAI221X1 g6869__6783 (.Y(n_146),
	.A0(n_142),
	.A1(n_120),
	.B0(n_143),
	.B1(n_123),
	.C0(n_145));
   DFFHQX1 \out_rank_q_reg[2]  (.Q(out_addr[2]),
	.D(n_144),
	.CK(clk));
   AOI22X1 g6871__3680 (.Y(n_145),
	.A0(n_127),
	.A1(n_134),
	.B0(n_129),
	.B1(n_137));
   DFFHQX1 \out_rank_q_reg[3]  (.Q(out_addr[3]),
	.D(n_141),
	.CK(clk));
   OAI221X1 g6870__1617 (.Y(n_144),
	.A0(n_108),
	.A1(n_138),
	.B0(n_139),
	.B1(n_140),
	.C0(reset_release_q[1]));
   AOI22X1 g6873__2802 (.Y(n_147),
	.A0(n_143),
	.A1(n_131),
	.B0(n_142),
	.B1(n_126));
   INVX1 g6874 (.Y(n_155),
	.A(n_152));
   MX2XL g6875__1705 (.Y(n_141),
	.A(out_addr[3]),
	.B(n_117),
	.S0(n_140));
   OAI21X1 g6876__5122 (.Y(n_152),
	.A0(n_139),
	.A1(n_150),
	.B0(n_138));
   OAI22X1 g6877__8246 (.Y(n_137),
	.A0(n_136),
	.A1(n_142),
	.B0(n_135),
	.B1(n_143));
   OAI22X1 g6878__7098 (.Y(n_134),
	.A0(n_133),
	.A1(n_142),
	.B0(n_132),
	.B1(n_143));
   OAI22X1 g6879__6131 (.Y(n_131),
	.A0(n_130),
	.A1(n_129),
	.B0(n_128),
	.B1(n_127));
   OAI22X1 g6880__1881 (.Y(n_126),
	.A0(n_125),
	.A1(n_129),
	.B0(n_124),
	.B1(n_127));
   AOI22X1 g6883__5115 (.Y(n_123),
	.A0(n_122),
	.A1(n_127),
	.B0(n_121),
	.B1(n_129));
   AOI22X1 g6884__7482 (.Y(n_120),
	.A0(n_119),
	.A1(n_127),
	.B0(n_118),
	.B1(n_129));
   INVX1 g6882 (.Y(n_160),
	.A(n_161));
   NAND2X1 g6881__4733 (.Y(n_138),
	.A(n_150),
	.B(n_142));
   NAND2XL g6886__6161 (.Y(n_117),
	.A(FE_OFN4_n_163),
	.B(n_129));
   AOI22X1 g6885__9315 (.Y(n_161),
	.A0(n_150),
	.A1(n_127),
	.B0(out_addr[3]),
	.B1(n_116));
   INVX1 g6887 (.Y(n_143),
	.A(n_142));
   OAI2BB1X2 g6888__9945 (.Y(n_142),
	.A0N(n_109),
	.A1N(n_112),
	.B0(n_100));
   INVX1 g6890 (.Y(n_129),
	.A(n_127));
   AOI21X1 g6891__2883 (.Y(n_140),
	.A0(n_116),
	.A1(FE_OFN4_n_163),
	.B0(n_159));
   DFFHQX1 out_valid_q_reg (.Q(out_valid_q),
	.D(n_114),
	.CK(clk));
   NOR2X1 g6892__2346 (.Y(n_127),
	.A(n_111),
	.B(n_110));
   AND2XL g6893__1666 (.Y(n_114),
	.A(reset_release_q[1]),
	.B(n_113));
   OAI21X2 g6897__7410 (.Y(n_159),
	.A0(out_ready),
	.A1(n_36),
	.B0(n_113));
   OAI22X1 g6894__6417 (.Y(n_112),
	.A0(n_111),
	.A1(n_96),
	.B0(out_addr[2]),
	.B1(n_105));
   OAI2BB1X1 g6896__5477 (.Y(n_110),
	.A0N(FE_OFN10_n_103),
	.A1N(n_104),
	.B0(n_109));
   INVX1 g6901 (.Y(n_108),
	.A(FE_OFN4_n_163));
   INVX1 g6900 (.Y(n_116),
	.A(n_150));
   NAND2X1 g6899__2398 (.Y(n_113),
	.A(n_107),
	.B(n_106));
   AND2X1 g6902__5107 (.Y(n_150),
	.A(n_102),
	.B(n_149));
   NOR2BX1 g6903__6260 (.Y(n_163),
	.AN(n_107),
	.B(n_106));
   OAI2BB1X1 g6898__4319 (.Y(n_109),
	.A0N(n_82),
	.A1N(n_99),
	.B0(FE_OFN2_n_97));
   NOR2BX1 g6904__8428 (.Y(n_105),
	.AN(n_104),
	.B(FE_OFN10_n_103));
   AO22XL g6905__5526 (.Y(n_102),
	.A0(n_93),
	.A1(n_101),
	.B0(out_addr[1]),
	.B1(out_rank_q[0]));
   NOR2X1 g6906__6783 (.Y(n_106),
	.A(FE_OFN10_n_103),
	.B(n_100));
   NAND2X1 g6907__3680 (.Y(n_99),
	.A(n_20),
	.B(n_98));
   OR2XL g6908__1617 (.Y(n_104),
	.A(n_95),
	.B(n_98));
   NAND2BX1 g6910__2802 (.Y(n_100),
	.AN(FE_OFN2_n_97),
	.B(n_111));
   AOI21XL g6909__1705 (.Y(n_96),
	.A0(n_95),
	.A1(FE_OFN10_n_103),
	.B0(n_91));
   OAI21X1 g6913__5122 (.Y(n_101),
	.A0(n_79),
	.A1(n_77),
	.B0(n_94));
   OAI211X1 g6911__8246 (.Y(n_149),
	.A0(n_84),
	.A1(n_81),
	.B0(n_2),
	.C0(n_94));
   NOR2X1 g6912__7098 (.Y(n_98),
	.A(out_addr[2]),
	.B(FE_OFN1_n_92));
   NOR2XL g6915__6131 (.Y(n_93),
	.A(n_76),
	.B(n_89));
   NOR2X1 g6914__1881 (.Y(n_111),
	.A(FE_OFN9_n_90),
	.B(FE_OFN1_n_92));
   DFFQXL \ack_rank_q_reg[4]  (.Q(ack_rank_q[4]),
	.D(n_65),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[12]  (.Q(ack_rank_q[12]),
	.D(n_72),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[0]  (.Q(ack_rank_q[0]),
	.D(n_59),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[2]  (.Q(ack_source[3]),
	.D(n_75),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[8]  (.Q(ack_rank_q[8]),
	.D(n_61),
	.CK(clk));
   INVXL g6917 (.Y(n_91),
	.A(FE_OFN9_n_90));
   DFFQXL \ack_rank_q_reg[14]  (.Q(ack_source[15]),
	.D(n_68),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[5]  (.Q(ack_rank_q[5]),
	.D(n_64),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[9]  (.Q(ack_rank_q[9]),
	.D(n_60),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[10]  (.Q(ack_source[11]),
	.D(n_70),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[1]  (.Q(ack_rank_q[1]),
	.D(n_69),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[13]  (.Q(ack_rank_q[13]),
	.D(n_71),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[15]  (.Q(ack_source[14]),
	.D(n_67),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[3]  (.Q(ack_source[2]),
	.D(n_62),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[6]  (.Q(ack_source[7]),
	.D(n_66),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[7]  (.Q(ack_source[6]),
	.D(n_63),
	.CK(clk));
   DFFQXL \ack_rank_q_reg[11]  (.Q(ack_source[10]),
	.D(n_74),
	.CK(clk));
   OAI22X1 g6926__5115 (.Y(n_89),
	.A0(n_88),
	.A1(n_83),
	.B0(n_87),
	.B1(n_80));
   NAND4XL g6920__7482 (.Y(n_92),
	.A(n_125),
	.B(n_86),
	.C(n_122),
	.D(n_132));
   NAND4X1 g6918__4733 (.Y(n_97),
	.A(n_128),
	.B(n_88),
	.C(n_118),
	.D(n_136));
   NAND4XL g6919__6161 (.Y(n_90),
	.A(n_130),
	.B(n_87),
	.C(n_119),
	.D(n_133));
   NAND4XL g6916__9315 (.Y(n_103),
	.A(n_124),
	.B(n_85),
	.C(n_121),
	.D(n_135));
   OAI22X1 g6922__9945 (.Y(n_84),
	.A0(n_136),
	.A1(n_83),
	.B0(n_82),
	.B1(n_132));
   OAI22X1 g6921__2883 (.Y(n_81),
	.A0(n_135),
	.A1(n_78),
	.B0(n_133),
	.B1(n_80));
   OAI22X1 g6923__2346 (.Y(n_79),
	.A0(n_121),
	.A1(n_78),
	.B0(n_82),
	.B1(n_122));
   OAI22X1 g6924__1666 (.Y(n_77),
	.A0(n_118),
	.A1(n_83),
	.B0(n_119),
	.B1(n_80));
   OAI22X1 g6925__7410 (.Y(n_76),
	.A0(n_85),
	.A1(n_78),
	.B0(n_82),
	.B1(n_86));
   AOI211XL g6963__6417 (.Y(n_75),
	.A0(pending_rank_q[2]),
	.A1(n_43),
	.B0(n_18),
	.C0(n_55));
   AOI211XL g6960__5477 (.Y(n_74),
	.A0(pending_rank_q[11]),
	.A1(n_44),
	.B0(n_14),
	.C0(n_55));
   AOI211XL g6961__2398 (.Y(n_72),
	.A0(pending_rank_q[12]),
	.A1(n_54),
	.B0(n_13),
	.C0(n_55));
   AOI211XL g6962__5107 (.Y(n_71),
	.A0(pending_rank_q[13]),
	.A1(n_52),
	.B0(n_19),
	.C0(n_55));
   AOI211XL g6959__6260 (.Y(n_70),
	.A0(pending_rank_q[10]),
	.A1(n_40),
	.B0(n_6),
	.C0(n_55));
   AOI211XL g6964__4319 (.Y(n_69),
	.A0(pending_rank_q[1]),
	.A1(n_41),
	.B0(n_16),
	.C0(n_55));
   AOI211XL g6965__8428 (.Y(n_68),
	.A0(pending_rank_q[14]),
	.A1(n_50),
	.B0(n_4),
	.C0(n_55));
   AOI211XL g6966__5526 (.Y(n_67),
	.A0(pending_rank_q[15]),
	.A1(n_57),
	.B0(n_12),
	.C0(n_55));
   AOI211XL g6971__6783 (.Y(n_66),
	.A0(pending_rank_q[6]),
	.A1(n_29),
	.B0(n_11),
	.C0(n_55));
   AOI211XL g6968__3680 (.Y(n_65),
	.A0(pending_rank_q[4]),
	.A1(n_48),
	.B0(n_9),
	.C0(n_55));
   AOI211XL g6969__1617 (.Y(n_64),
	.A0(pending_rank_q[5]),
	.A1(n_25),
	.B0(n_8),
	.C0(n_55));
   AOI211XL g6970__2802 (.Y(n_63),
	.A0(pending_rank_q[7]),
	.A1(n_49),
	.B0(n_5),
	.C0(n_55));
   AOI211XL g6967__1705 (.Y(n_62),
	.A0(pending_rank_q[3]),
	.A1(n_47),
	.B0(n_17),
	.C0(n_55));
   AOI211XL g6972__5122 (.Y(n_61),
	.A0(pending_rank_q[8]),
	.A1(n_46),
	.B0(n_7),
	.C0(n_55));
   AOI211XL g6973__8246 (.Y(n_60),
	.A0(pending_rank_q[9]),
	.A1(n_42),
	.B0(n_10),
	.C0(n_55));
   AOI211XL g6974__7098 (.Y(n_59),
	.A0(pending_rank_q[0]),
	.A1(n_45),
	.B0(n_15),
	.C0(n_55));
   NOR2XL g6981__6131 (.Y(src_ack_async[14]),
	.A(n_55),
	.B(n_57));
   NOR2XL g6980__1881 (.Y(src_ack_async[12]),
	.A(n_55),
	.B(n_54));
   NOR2XL g6985__5115 (.Y(src_ack_async[13]),
	.A(n_55),
	.B(n_52));
   NOR2XL g6989__7482 (.Y(src_ack_async[15]),
	.A(n_55),
	.B(n_50));
   AOI21X1 g6945__4733 (.Y(n_85),
	.A0(req_rank[7]),
	.A1(n_49),
	.B0(pending_rank_q[7]));
   AOI21X1 g6946__6161 (.Y(n_124),
	.A0(req_sync_q[4]),
	.A1(n_48),
	.B0(pending_rank_q[4]));
   AOI21X1 g6949__9315 (.Y(n_88),
	.A0(req_rank[3]),
	.A1(n_47),
	.B0(pending_rank_q[3]));
   AOI21X1 g6947__9945 (.Y(n_125),
	.A0(req_sync_q[12]),
	.A1(n_54),
	.B0(pending_rank_q[12]));
   AOI21X1 g6948__2883 (.Y(n_86),
	.A0(req_rank[15]),
	.A1(n_57),
	.B0(pending_rank_q[15]));
   AOI21X1 g6943__2346 (.Y(n_130),
	.A0(req_sync_q[8]),
	.A1(n_46),
	.B0(pending_rank_q[8]));
   AOI21X1 g6950__1666 (.Y(n_128),
	.A0(req_sync_q[0]),
	.A1(n_45),
	.B0(pending_rank_q[0]));
   AOI21X1 g6944__7410 (.Y(n_87),
	.A0(req_rank[11]),
	.A1(n_44),
	.B0(pending_rank_q[11]));
   AOI21X1 g6952__6417 (.Y(n_132),
	.A0(req_sync_q[13]),
	.A1(n_52),
	.B0(pending_rank_q[13]));
   AOI21X1 g6953__5477 (.Y(n_118),
	.A0(req_rank[2]),
	.A1(n_43),
	.B0(pending_rank_q[2]));
   AOI21X1 g6954__2398 (.Y(n_133),
	.A0(req_sync_q[9]),
	.A1(n_42),
	.B0(pending_rank_q[9]));
   AOI21X1 g6955__5107 (.Y(n_122),
	.A0(req_rank[14]),
	.A1(n_50),
	.B0(pending_rank_q[14]));
   AOI21X1 g6956__6260 (.Y(n_136),
	.A0(req_sync_q[1]),
	.A1(n_41),
	.B0(pending_rank_q[1]));
   AOI21X1 g6951__4319 (.Y(n_119),
	.A0(req_rank[10]),
	.A1(n_40),
	.B0(pending_rank_q[10]));
   NOR2XL g6987__8428 (.Y(src_ack_async[11]),
	.A(n_55),
	.B(n_40));
   NOR2XL g6978__5526 (.Y(src_ack_async[2]),
	.A(n_55),
	.B(n_47));
   INVXL g6975 (.Y(out_valid),
	.A(n_36));
   NOR2XL g6977__6783 (.Y(src_ack_async[0]),
	.A(n_55),
	.B(n_45));
   NOR2XL g6988__3680 (.Y(src_ack_async[3]),
	.A(n_55),
	.B(n_43));
   NOR2XL g6983__1617 (.Y(src_ack_async[7]),
	.A(n_55),
	.B(n_29));
   NOR2XL g6979__2802 (.Y(src_ack_async[8]),
	.A(n_55),
	.B(n_46));
   NOR2XL g6976__1705 (.Y(src_ack_async[10]),
	.A(n_55),
	.B(n_44));
   NOR2XL g6992__5122 (.Y(src_ack_async[5]),
	.A(n_55),
	.B(n_25));
   NOR2XL g6990__8246 (.Y(src_ack_async[9]),
	.A(n_55),
	.B(n_42));
   NOR2XL g6982__7098 (.Y(src_ack_async[6]),
	.A(n_55),
	.B(n_49));
   NOR2XL g6991__6131 (.Y(src_ack_async[1]),
	.A(n_55),
	.B(n_41));
   NOR2XL g6986__1881 (.Y(src_ack_async[4]),
	.A(n_55),
	.B(n_48));
   AOI21X1 g6993__5115 (.Y(n_107),
	.A0(n_0),
	.A1(out_valid_q),
	.B0(n_55));
   AOI21X1 g6957__7482 (.Y(n_135),
	.A0(req_sync_q[5]),
	.A1(n_25),
	.B0(pending_rank_q[5]));
   AOI21X1 g6958__4733 (.Y(n_121),
	.A0(req_rank[6]),
	.A1(n_29),
	.B0(pending_rank_q[6]));
   NAND2X2 g6984__6161 (.Y(n_36),
	.A(reset_release_q[1]),
	.B(out_valid_q));
   INVX1 g7024 (.Y(n_95),
	.A(n_20));
   INVXL g7000 (.Y(n_19),
	.A(req_sync_q[13]));
   INVXL g7001 (.Y(n_18),
	.A(req_rank[2]));
   INVXL g7022 (.Y(n_17),
	.A(req_rank[3]));
   INVXL g6994 (.Y(n_16),
	.A(req_sync_q[1]));
   INVXL g6995 (.Y(n_15),
	.A(req_sync_q[0]));
   INVXL g6996 (.Y(n_14),
	.A(req_rank[11]));
   INVXL g6997 (.Y(n_13),
	.A(req_sync_q[12]));
   INVXL g6999 (.Y(n_12),
	.A(req_rank[15]));
   INVX2 g7006 (.Y(n_55),
	.A(reset_release_q[1]));
   INVXL g7023 (.Y(n_11),
	.A(req_rank[6]));
   INVXL g7020 (.Y(n_10),
	.A(req_sync_q[9]));
   INVXL g7016 (.Y(n_9),
	.A(req_sync_q[4]));
   INVXL g7017 (.Y(n_8),
	.A(req_sync_q[5]));
   INVXL g7019 (.Y(n_7),
	.A(req_sync_q[8]));
   INVXL g7021 (.Y(n_6),
	.A(req_rank[10]));
   INVXL g7018 (.Y(n_5),
	.A(req_rank[7]));
   INVXL g6998 (.Y(n_4),
	.A(req_rank[14]));
   NAND2X1 g7034__9315 (.Y(n_20),
	.A(n_78),
	.B(n_80));
   DFFHQX1 \req_sync_q_reg[1]  (.Q(req_sync_q[1]),
	.D(req_meta_q[1]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[0]  (.Q(req_sync_q[0]),
	.D(req_meta_q[0]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[9]  (.Q(req_sync_q[9]),
	.D(req_meta_q[9]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[14]  (.Q(req_rank[15]),
	.D(req_meta_q[14]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[5]  (.Q(req_sync_q[5]),
	.D(req_meta_q[5]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[12]  (.Q(req_sync_q[12]),
	.D(req_meta_q[12]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[13]  (.Q(req_sync_q[13]),
	.D(req_meta_q[13]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[15]  (.Q(req_rank[14]),
	.D(req_meta_q[15]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[11]  (.Q(req_rank[10]),
	.D(req_meta_q[11]),
	.CK(clk));
   OAI22XL g7025__9945 (.Y(out_addr[0]),
	.A0(out_addr[1]),
	.A1(n_2),
	.B0(out_rank_q[0]),
	.B1(n_94));
   DFFHQX1 \req_sync_q_reg[4]  (.Q(req_sync_q[4]),
	.D(req_meta_q[4]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[6]  (.Q(req_rank[7]),
	.D(req_meta_q[6]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[3]  (.Q(req_rank[2]),
	.D(req_meta_q[3]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[2]  (.Q(req_rank[3]),
	.D(req_meta_q[2]),
	.CK(clk));
   DFFRHQX1 \reset_release_q_reg[1]  (.Q(reset_release_q[1]),
	.D(reset_release_q[0]),
	.RN(FE_PHN11_rst_n),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[7]  (.Q(req_rank[6]),
	.D(req_meta_q[7]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[8]  (.Q(req_sync_q[8]),
	.D(req_meta_q[8]),
	.CK(clk));
   DFFHQX1 \req_sync_q_reg[10]  (.Q(req_rank[11]),
	.D(req_meta_q[10]),
	.CK(clk));
   NAND2X1 g7052__2883 (.Y(n_83),
	.A(n_1),
	.B(n_139));
   NAND2X1 g7053__2346 (.Y(n_80),
	.A(out_addr[3]),
	.B(n_139));
   NAND2X1 g7054__1666 (.Y(n_78),
	.A(out_addr[2]),
	.B(n_1));
   DFFQXL \req_meta_q_reg[12]  (.Q(req_meta_q[12]),
	.D(src_req_async[12]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[9]  (.Q(req_meta_q[9]),
	.D(src_req_async[9]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[6]  (.Q(req_meta_q[6]),
	.D(src_req_async[6]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[11]  (.Q(req_meta_q[11]),
	.D(src_req_async[11]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[15]  (.Q(req_meta_q[15]),
	.D(src_req_async[15]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[7]  (.Q(req_meta_q[7]),
	.D(src_req_async[7]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[14]  (.Q(req_meta_q[14]),
	.D(src_req_async[14]),
	.CK(clk));
   DFFRHQX1 \reset_release_q_reg[0]  (.Q(reset_release_q[0]),
	.D(1'b1),
	.RN(FE_PHN11_rst_n),
	.CK(clk));
   NAND2X1 g7055__7410 (.Y(n_82),
	.A(out_addr[3]),
	.B(out_addr[2]));
   DFFQXL \req_meta_q_reg[1]  (.Q(req_meta_q[1]),
	.D(src_req_async[1]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[3]  (.Q(req_meta_q[3]),
	.D(src_req_async[3]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[8]  (.Q(req_meta_q[8]),
	.D(src_req_async[8]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[5]  (.Q(req_meta_q[5]),
	.D(src_req_async[5]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[4]  (.Q(req_meta_q[4]),
	.D(src_req_async[4]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[13]  (.Q(req_meta_q[13]),
	.D(src_req_async[13]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[2]  (.Q(req_meta_q[2]),
	.D(src_req_async[2]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[10]  (.Q(req_meta_q[10]),
	.D(src_req_async[10]),
	.CK(clk));
   DFFQXL \req_meta_q_reg[0]  (.Q(req_meta_q[0]),
	.D(src_req_async[0]),
	.CK(clk));
   INVX1 g7066 (.Y(n_1),
	.A(out_addr[3]));
   INVX1 g7075 (.Y(n_2),
	.A(out_rank_q[0]));
   INVX1 g7074 (.Y(n_48),
	.A(ack_rank_q[4]));
   INVX1 g7069 (.Y(n_29),
	.A(ack_source[7]));
   INVX1 g7058 (.Y(n_52),
	.A(ack_rank_q[13]));
   INVX1 g7060 (.Y(n_40),
	.A(ack_source[11]));
   INVX1 g7067 (.Y(n_94),
	.A(out_addr[1]));
   INVX1 g7057 (.Y(n_42),
	.A(ack_rank_q[9]));
   INVX1 g7068 (.Y(n_49),
	.A(ack_source[6]));
   INVX1 g7076 (.Y(n_139),
	.A(out_addr[2]));
   INVX1 g7056 (.Y(n_0),
	.A(out_ready));
   INVX1 g7059 (.Y(n_44),
	.A(ack_source[10]));
   INVX1 g7073 (.Y(n_45),
	.A(ack_rank_q[0]));
   INVX1 g7071 (.Y(n_43),
	.A(ack_source[3]));
   INVX1 g7061 (.Y(n_54),
	.A(ack_rank_q[12]));
   INVX1 g7070 (.Y(n_46),
	.A(ack_rank_q[8]));
   INVX1 g7063 (.Y(n_25),
	.A(ack_rank_q[5]));
   INVX1 g7062 (.Y(n_47),
	.A(ack_source[2]));
   INVX1 g7072 (.Y(n_57),
	.A(ack_source[14]));
   INVX1 g7064 (.Y(n_50),
	.A(ack_source[15]));
   INVX1 g7065 (.Y(n_41),
	.A(ack_rank_q[1]));
   AO21X1 g2 (.Y(n_235),
	.A0(FE_OFN4_n_163),
	.A1(n_154),
	.B0(n_159));
endmodule

