
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 26 2026 14:51:12 KST (Aug 26 2026 05:51:12 UTC)

// Verification Directory fv/aer_pending_gray_rank_iprra_sync_core_reset 

module aer_pending_rank_reuse_core_CODE_STYLE0_SELECTOR_STYLE1(clk,
     rst_n, src_req_async, src_ack_async, out_addr, out_valid,
     out_ready);
  input clk, rst_n, out_ready;
  input [15:0] src_req_async;
  output [15:0] src_ack_async;
  output [3:0] out_addr;
  output out_valid;
  wire clk, rst_n, out_ready;
  wire [15:0] src_req_async;
  wire [15:0] src_ack_async;
  wire [3:0] out_addr;
  wire out_valid;
  wire [15:0] ack_rank_q;
  wire [15:0] ack_source;
  wire [1:0] reset_release_q;
  wire [15:0] req_meta_q;
  wire [15:0] req_sync_q;
  wire [15:0] req_rank;
  wire [3:0] out_rank_q;
  wire [15:0] pending_rank_q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, out_valid_q;
  AND2XL g8099__2398(.A (n_222), .B (ack_rank_q[0]), .Y
       (src_ack_async[0]));
  AND2XL g8100__5107(.A (n_222), .B (ack_source[14]), .Y
       (src_ack_async[14]));
  AND2XL g8101__6260(.A (reset_release_q[1]), .B (ack_rank_q[8]), .Y
       (src_ack_async[12]));
  AND2XL g8102__4319(.A (n_222), .B (ack_source[8]), .Y
       (src_ack_async[8]));
  AND2XL g8103__8428(.A (n_222), .B (ack_source[15]), .Y
       (src_ack_async[15]));
  AND2XL g8104__5526(.A (n_222), .B (ack_rank_q[5]), .Y
       (src_ack_async[7]));
  AND2XL g8105__6783(.A (n_222), .B (ack_rank_q[13]), .Y
       (src_ack_async[11]));
  AND2XL g8106__3680(.A (n_222), .B (ack_rank_q[4]), .Y
       (src_ack_async[6]));
  AND2XL g8107__1617(.A (reset_release_q[1]), .B (ack_rank_q[1]), .Y
       (src_ack_async[1]));
  AND2XL g8108__2802(.A (n_222), .B (out_valid_q), .Y (out_valid));
  AND2XL g8109__1705(.A (n_222), .B (ack_rank_q[9]), .Y
       (src_ack_async[13]));
  AND2XL g8110__5122(.A (n_222), .B (ack_rank_q[12]), .Y
       (src_ack_async[10]));
  AND2XL g8111__8246(.A (n_222), .B (ack_source[4]), .Y
       (src_ack_async[4]));
  AND2XL g8112__7098(.A (reset_release_q[1]), .B (ack_source[3]), .Y
       (src_ack_async[3]));
  AND2XL g8113__6131(.A (n_222), .B (ack_source[9]), .Y
       (src_ack_async[9]));
  AND2XL g8114__1881(.A (n_222), .B (ack_source[2]), .Y
       (src_ack_async[2]));
  AND2XL g8115__5115(.A (n_222), .B (ack_source[5]), .Y
       (src_ack_async[5]));
  DFFHQX1 \req_sync_q_reg[7] (.CK (clk), .D (req_meta_q[7]), .Q
       (req_sync_q[7]));
  DFFHQX1 \req_sync_q_reg[0] (.CK (clk), .D (req_meta_q[0]), .Q
       (req_sync_q[0]));
  DFFHQX1 \req_sync_q_reg[1] (.CK (clk), .D (req_meta_q[1]), .Q
       (req_sync_q[1]));
  DFFHQX1 \req_sync_q_reg[2] (.CK (clk), .D (req_meta_q[2]), .Q
       (req_rank[3]));
  DFFHQX1 \req_sync_q_reg[3] (.CK (clk), .D (req_meta_q[3]), .Q
       (req_rank[2]));
  DFFHQX1 \req_sync_q_reg[4] (.CK (clk), .D (req_meta_q[4]), .Q
       (req_rank[7]));
  DFFHQX1 \req_sync_q_reg[5] (.CK (clk), .D (req_meta_q[5]), .Q
       (req_rank[6]));
  DFFHQX1 \req_sync_q_reg[6] (.CK (clk), .D (req_meta_q[6]), .Q
       (req_sync_q[6]));
  DFFHQX1 \req_sync_q_reg[15] (.CK (clk), .D (req_meta_q[15]), .Q
       (req_rank[10]));
  DFFRHQX1 \reset_release_q_reg[1] (.RN (rst_n), .CK (clk), .D
       (reset_release_q[0]), .Q (n_222));
  DFFHQX1 \req_sync_q_reg[8] (.CK (clk), .D (req_meta_q[8]), .Q
       (req_rank[15]));
  DFFHQX1 \req_sync_q_reg[9] (.CK (clk), .D (req_meta_q[9]), .Q
       (req_rank[14]));
  DFFHQX1 \req_sync_q_reg[10] (.CK (clk), .D (req_meta_q[10]), .Q
       (req_sync_q[10]));
  DFFHQX1 \req_sync_q_reg[11] (.CK (clk), .D (req_meta_q[11]), .Q
       (req_sync_q[11]));
  DFFHQX1 \req_sync_q_reg[12] (.CK (clk), .D (req_meta_q[12]), .Q
       (req_sync_q[12]));
  DFFHQX1 \req_sync_q_reg[13] (.CK (clk), .D (req_meta_q[13]), .Q
       (req_sync_q[13]));
  DFFHQX1 \req_sync_q_reg[14] (.CK (clk), .D (req_meta_q[14]), .Q
       (req_rank[11]));
  NAND2XL g8134__7482(.A (n_223), .B (n_224), .Y (out_addr[1]));
  XOR2XL g8135__4733(.A (out_rank_q[2]), .B (out_addr[3]), .Y
       (out_addr[2]));
  XOR2XL g8136__6161(.A (out_rank_q[1]), .B (out_rank_q[0]), .Y
       (out_addr[0]));
  DFFQXL \req_meta_q_reg[4] (.CK (clk), .D (src_req_async[4]), .Q
       (req_meta_q[4]));
  DFFQXL \req_meta_q_reg[15] (.CK (clk), .D (src_req_async[15]), .Q
       (req_meta_q[15]));
  DFFQXL \req_meta_q_reg[13] (.CK (clk), .D (src_req_async[13]), .Q
       (req_meta_q[13]));
  DFFQXL \req_meta_q_reg[14] (.CK (clk), .D (src_req_async[14]), .Q
       (req_meta_q[14]));
  DFFQXL \req_meta_q_reg[9] (.CK (clk), .D (src_req_async[9]), .Q
       (req_meta_q[9]));
  DFFQXL \req_meta_q_reg[0] (.CK (clk), .D (src_req_async[0]), .Q
       (req_meta_q[0]));
  DFFQXL \req_meta_q_reg[1] (.CK (clk), .D (src_req_async[1]), .Q
       (req_meta_q[1]));
  DFFQXL \req_meta_q_reg[2] (.CK (clk), .D (src_req_async[2]), .Q
       (req_meta_q[2]));
  DFFRHQX1 \reset_release_q_reg[0] (.RN (rst_n), .CK (clk), .D (1'b1),
       .Q (reset_release_q[0]));
  DFFQXL \req_meta_q_reg[5] (.CK (clk), .D (src_req_async[5]), .Q
       (req_meta_q[5]));
  DFFQXL \req_meta_q_reg[6] (.CK (clk), .D (src_req_async[6]), .Q
       (req_meta_q[6]));
  DFFQXL \req_meta_q_reg[11] (.CK (clk), .D (src_req_async[11]), .Q
       (req_meta_q[11]));
  DFFQXL \req_meta_q_reg[8] (.CK (clk), .D (src_req_async[8]), .Q
       (req_meta_q[8]));
  DFFQXL \req_meta_q_reg[10] (.CK (clk), .D (src_req_async[10]), .Q
       (req_meta_q[10]));
  DFFQXL \req_meta_q_reg[12] (.CK (clk), .D (src_req_async[12]), .Q
       (req_meta_q[12]));
  DFFQXL \req_meta_q_reg[7] (.CK (clk), .D (src_req_async[7]), .Q
       (req_meta_q[7]));
  DFFQXL \req_meta_q_reg[3] (.CK (clk), .D (src_req_async[3]), .Q
       (req_meta_q[3]));
  NAND2BX1 g8154__9315(.AN (out_rank_q[2]), .B (out_rank_q[1]), .Y
       (n_223));
  NAND2BX1 g8155__9945(.AN (out_rank_q[1]), .B (out_rank_q[2]), .Y
       (n_224));
  BUFX2 drc_bufs8160(.A (n_222), .Y (reset_release_q[1]));
  DFFHQX1 \ack_rank_q_reg[0] (.CK (clk), .D (n_100), .Q
       (ack_rank_q[0]));
  DFFHQX1 \ack_rank_q_reg[1] (.CK (clk), .D (n_91), .Q (ack_rank_q[1]));
  DFFHQX1 \ack_rank_q_reg[2] (.CK (clk), .D (n_88), .Q (ack_source[3]));
  DFFHQX1 \ack_rank_q_reg[3] (.CK (clk), .D (n_89), .Q (ack_source[2]));
  DFFHQX1 \ack_rank_q_reg[4] (.CK (clk), .D (n_98), .Q (ack_rank_q[4]));
  DFFHQX1 \ack_rank_q_reg[5] (.CK (clk), .D (n_116), .Q
       (ack_rank_q[5]));
  DFFHQX1 \ack_rank_q_reg[6] (.CK (clk), .D (n_93), .Q (ack_source[5]));
  DFFHQX1 \ack_rank_q_reg[7] (.CK (clk), .D (n_99), .Q (ack_source[4]));
  DFFHQX1 \ack_rank_q_reg[8] (.CK (clk), .D (n_97), .Q (ack_rank_q[8]));
  DFFHQX1 \ack_rank_q_reg[9] (.CK (clk), .D (n_94), .Q (ack_rank_q[9]));
  DFFHQX1 \ack_rank_q_reg[10] (.CK (clk), .D (n_95), .Q
       (ack_source[15]));
  DFFHQX1 \ack_rank_q_reg[11] (.CK (clk), .D (n_96), .Q
       (ack_source[14]));
  DFFHQX1 \ack_rank_q_reg[12] (.CK (clk), .D (n_92), .Q
       (ack_rank_q[12]));
  DFFHQX1 \ack_rank_q_reg[13] (.CK (clk), .D (n_90), .Q
       (ack_rank_q[13]));
  DFFHQX1 \ack_rank_q_reg[14] (.CK (clk), .D (n_86), .Q
       (ack_source[9]));
  DFFHQX1 \ack_rank_q_reg[15] (.CK (clk), .D (n_87), .Q
       (ack_source[8]));
  DFFHQX1 \out_rank_q_reg[0] (.CK (clk), .D (n_203), .Q
       (out_rank_q[0]));
  DFFHQX1 \out_rank_q_reg[1] (.CK (clk), .D (n_202), .Q
       (out_rank_q[1]));
  DFFHQX1 \out_rank_q_reg[2] (.CK (clk), .D (n_193), .Q
       (out_rank_q[2]));
  DFFHQX1 \out_rank_q_reg[3] (.CK (clk), .D (n_194), .Q (out_addr[3]));
  DFFHQX1 out_valid_q_reg(.CK (clk), .D (n_192), .Q (out_valid_q));
  DFFHQX1 \pending_rank_q_reg[0] (.CK (clk), .D (n_216), .Q
       (pending_rank_q[0]));
  DFFHQX1 \pending_rank_q_reg[1] (.CK (clk), .D (n_217), .Q
       (pending_rank_q[1]));
  DFFHQX1 \pending_rank_q_reg[2] (.CK (clk), .D (n_220), .Q
       (pending_rank_q[2]));
  DFFHQX1 \pending_rank_q_reg[3] (.CK (clk), .D (n_219), .Q
       (pending_rank_q[3]));
  DFFHQX1 \pending_rank_q_reg[4] (.CK (clk), .D (n_215), .Q
       (pending_rank_q[4]));
  DFFHQX1 \pending_rank_q_reg[5] (.CK (clk), .D (n_218), .Q
       (pending_rank_q[5]));
  DFFHQX1 \pending_rank_q_reg[6] (.CK (clk), .D (n_214), .Q
       (pending_rank_q[6]));
  DFFHQX1 \pending_rank_q_reg[7] (.CK (clk), .D (n_221), .Q
       (pending_rank_q[7]));
  DFFHQX1 \pending_rank_q_reg[8] (.CK (clk), .D (n_213), .Q
       (pending_rank_q[8]));
  DFFHQX1 \pending_rank_q_reg[9] (.CK (clk), .D (n_211), .Q
       (pending_rank_q[9]));
  DFFHQX1 \pending_rank_q_reg[10] (.CK (clk), .D (n_212), .Q
       (pending_rank_q[10]));
  DFFHQX1 \pending_rank_q_reg[11] (.CK (clk), .D (n_208), .Q
       (pending_rank_q[11]));
  DFFHQX1 \pending_rank_q_reg[12] (.CK (clk), .D (n_206), .Q
       (pending_rank_q[12]));
  DFFHQX1 \pending_rank_q_reg[13] (.CK (clk), .D (n_209), .Q
       (pending_rank_q[13]));
  DFFHQX1 \pending_rank_q_reg[14] (.CK (clk), .D (n_210), .Q
       (pending_rank_q[14]));
  DFFHQX1 \pending_rank_q_reg[15] (.CK (clk), .D (n_207), .Q
       (pending_rank_q[15]));
  AOI21X1 g10493__2883(.A0 (n_205), .A1 (n_198), .B0 (n_65), .Y
       (n_221));
  AOI21X1 g10494__2346(.A0 (n_201), .A1 (n_204), .B0 (n_49), .Y
       (n_220));
  AOI21X1 g10495__1666(.A0 (n_205), .A1 (n_201), .B0 (n_48), .Y
       (n_219));
  AOI21XL g10496__7410(.A0 (n_197), .A1 (n_205), .B0 (n_62), .Y
       (n_218));
  AOI21XL g10497__6417(.A0 (n_200), .A1 (n_205), .B0 (n_59), .Y
       (n_217));
  AOI21X1 g10498__5477(.A0 (n_200), .A1 (n_204), .B0 (n_54), .Y
       (n_216));
  AOI21X1 g10499__2398(.A0 (n_197), .A1 (n_204), .B0 (n_61), .Y
       (n_215));
  AOI21X1 g10500__5107(.A0 (n_198), .A1 (n_204), .B0 (n_63), .Y
       (n_214));
  AOI21XL g10501__6260(.A0 (n_199), .A1 (n_200), .B0 (n_60), .Y
       (n_213));
  AOI21X1 g10502__4319(.A0 (n_199), .A1 (n_201), .B0 (n_66), .Y
       (n_212));
  AOI21XL g10503__8428(.A0 (n_196), .A1 (n_200), .B0 (n_64), .Y
       (n_211));
  AOI21X1 g10506__5526(.A0 (n_199), .A1 (n_198), .B0 (n_50), .Y
       (n_210));
  AOI21XL g10507__6783(.A0 (n_196), .A1 (n_197), .B0 (n_52), .Y
       (n_209));
  AOI21X1 g10508__3680(.A0 (n_196), .A1 (n_201), .B0 (n_47), .Y
       (n_208));
  AOI21X1 g10509__1617(.A0 (n_196), .A1 (n_198), .B0 (n_51), .Y
       (n_207));
  AOI21XL g10510__2802(.A0 (n_199), .A1 (n_197), .B0 (n_53), .Y
       (n_206));
  OAI2BB1X1 g10511__1705(.A0N (n_182), .A1N (n_195), .B0 (n_3), .Y
       (n_205));
  OAI31X1 g10512__5122(.A0 (n_184), .A1 (n_181), .A2 (n_191), .B0
       (n_2), .Y (n_204));
  NAND3BXL g10513__8246(.AN (n_195), .B (n_3), .C (n_185), .Y (n_203));
  OAI211X1 g10514__7098(.A0 (n_184), .A1 (n_190), .B0 (n_3), .C0
       (n_189), .Y (n_202));
  OAI21X1 g10515__6131(.A0 (n_180), .A1 (n_190), .B0 (n_2), .Y (n_201));
  OAI2BB1X1 g10517__1881(.A0N (n_179), .A1N (n_190), .B0 (n_2), .Y
       (n_200));
  OAI21X1 g10519__5115(.A0 (n_187), .A1 (n_191), .B0 (n_3), .Y (n_199));
  OAI21X1 g10520__7482(.A0 (n_179), .A1 (n_190), .B0 (n_3), .Y (n_198));
  OAI2BB1X1 g10521__4733(.A0N (n_180), .A1N (n_190), .B0 (n_2), .Y
       (n_197));
  OAI2BB1X1 g10522__6161(.A0N (n_186), .A1N (n_191), .B0 (n_2), .Y
       (n_196));
  NOR2BX1 g10524__9315(.AN (n_191), .B (n_184), .Y (n_195));
  OAI211X1 g10525__9945(.A0 (n_5), .A1 (n_183), .B0 (n_3), .C0 (n_187),
       .Y (n_194));
  OAI211X1 g10526__2883(.A0 (n_179), .A1 (n_184), .B0 (n_2), .C0
       (n_188), .Y (n_193));
  AOI21X1 g10527__2346(.A0 (n_45), .A1 (n_184), .B0 (n_4), .Y (n_192));
  OR4X1 g10528__1666(.A (n_164), .B (n_168), .C (n_173), .D (n_177), .Y
       (n_191));
  NOR4X1 g10529__7410(.A (n_162), .B (n_164), .C (n_168), .D (n_176),
       .Y (n_190));
  NAND2X1 g10530__6417(.A (out_rank_q[1]), .B (n_184), .Y (n_189));
  NAND2X1 g10531__5477(.A (out_rank_q[2]), .B (n_184), .Y (n_188));
  INVX1 g10532(.A (n_186), .Y (n_187));
  NAND2X1 g10533__2398(.A (out_rank_q[0]), .B (n_184), .Y (n_185));
  NOR2X1 g10534__5107(.A (n_182), .B (n_184), .Y (n_186));
  INVX1 g10535(.A (n_184), .Y (n_183));
  NAND2X1 g10536__6260(.A (n_45), .B (n_178), .Y (n_184));
  INVX1 g10537(.A (n_182), .Y (n_181));
  NOR3X1 g10538__4319(.A (n_162), .B (n_168), .C (n_174), .Y (n_182));
  INVX1 g10539(.A (n_179), .Y (n_180));
  NAND4XL g10540__8428(.A (n_65), .B (n_63), .C (n_64), .D (n_167), .Y
       (n_178));
  NOR2BX1 g10541__5526(.AN (n_171), .B (n_175), .Y (n_179));
  OR4X1 g10542__6783(.A (n_159), .B (n_165), .C (n_1), .D (n_169), .Y
       (n_177));
  OR4X1 g10543__3680(.A (n_160), .B (n_163), .C (n_169), .D (n_170), .Y
       (n_176));
  OAI211X1 g10544__1617(.A0 (n_61), .A1 (n_153), .B0 (n_161), .C0
       (n_172), .Y (n_175));
  OAI211X1 g10545__2802(.A0 (n_60), .A1 (n_145), .B0 (n_166), .C0
       (n_171), .Y (n_174));
  INVX1 g10546(.A (n_172), .Y (n_173));
  NOR2X1 g10547__1705(.A (n_158), .B (n_170), .Y (n_172));
  AOI211XL g10548__5122(.A0 (n_101), .A1 (n_147), .B0 (n_159), .C0
       (n_164), .Y (n_171));
  AND4XL g10549__8246(.A (n_47), .B (n_62), .C (n_61), .D (n_151), .Y
       (n_167));
  NOR3X1 g10550__7098(.A (n_65), .B (n_0), .C (n_157), .Y (n_170));
  NOR3X1 g10551__6131(.A (n_48), .B (n_112), .C (n_156), .Y (n_169));
  NOR3X1 g10552__1881(.A (n_47), .B (n_109), .C (n_155), .Y (n_168));
  INVX1 g10553(.A (n_165), .Y (n_166));
  OAI22X1 g10555__5115(.A0 (n_49), .A1 (n_156), .B0 (n_50), .B1
       (n_154), .Y (n_163));
  NOR4X1 g10556__7482(.A (n_64), .B (n_111), .C (n_130), .D (n_148), .Y
       (n_165));
  NOR3X1 g10557__4733(.A (n_51), .B (n_115), .C (n_154), .Y (n_164));
  INVX1 g10558(.A (n_160), .Y (n_161));
  NOR2X1 g10559__6161(.A (n_66), .B (n_155), .Y (n_162));
  NOR2X1 g10560__9315(.A (n_63), .B (n_157), .Y (n_160));
  NOR4X1 g10561__9945(.A (n_62), .B (n_113), .C (n_131), .D (n_153), .Y
       (n_158));
  NOR4BX1 g10562__2883(.AN (n_147), .B (n_52), .C (n_114), .D (n_129),
       .Y (n_159));
  OAI21X1 g10563__2346(.A0 (n_121), .A1 (n_131), .B0 (n_152), .Y
       (n_157));
  OAI21X1 g10564__1666(.A0 (n_119), .A1 (n_128), .B0 (n_150), .Y
       (n_156));
  OAI21X1 g10565__7410(.A0 (n_125), .A1 (n_130), .B0 (n_149), .Y
       (n_155));
  OAI21X1 g10566__6417(.A0 (n_123), .A1 (n_129), .B0 (n_147), .Y
       (n_154));
  INVX1 g10567(.A (n_152), .Y (n_153));
  AND4XL g10568__5477(.A (n_59), .B (n_66), .C (n_60), .D (n_141), .Y
       (n_151));
  AOI21X1 g10569__2398(.A0 (n_133), .A1 (n_139), .B0 (n_146), .Y
       (n_152));
  INVX1 g10571(.A (n_148), .Y (n_149));
  AOI21X1 g10572__5107(.A0 (n_135), .A1 (n_138), .B0 (n_146), .Y
       (n_150));
  OAI21X1 g10573__6260(.A0 (n_132), .A1 (n_140), .B0 (n_144), .Y
       (n_148));
  AOI21X1 g10574__4319(.A0 (n_134), .A1 (n_137), .B0 (n_145), .Y
       (n_147));
  AOI21X1 g10575__8428(.A0 (n_136), .A1 (n_143), .B0 (n_142), .Y
       (n_146));
  INVX1 g10576(.A (n_144), .Y (n_145));
  OAI21X1 g10577__5526(.A0 (n_136), .A1 (n_142), .B0 (n_143), .Y
       (n_144));
  NAND2BX1 g10578__6783(.AN (n_135), .B (n_138), .Y (n_143));
  AND4XL g10579__3680(.A (n_48), .B (n_51), .C (n_52), .D (n_127), .Y
       (n_141));
  NOR2BX1 g10580__1617(.AN (n_132), .B (n_140), .Y (n_142));
  NAND2X1 g10581__2802(.A (n_126), .B (n_135), .Y (n_139));
  NOR2BX1 g10582__1705(.AN (n_134), .B (n_117), .Y (n_140));
  NAND2BXL g10583__5122(.AN (n_132), .B (n_117), .Y (n_137));
  NAND2BX1 g10584__8246(.AN (n_126), .B (n_133), .Y (n_138));
  NOR4X1 g10585__7098(.A (n_38), .B (n_46), .C (n_103), .D (n_117), .Y
       (n_136));
  OAI21X1 g10586__6131(.A0 (n_107), .A1 (n_121), .B0 (n_122), .Y
       (n_135));
  OAI21X1 g10587__1881(.A0 (n_103), .A1 (n_125), .B0 (n_118), .Y
       (n_134));
  OAI21X1 g10588__5115(.A0 (n_108), .A1 (n_119), .B0 (n_120), .Y
       (n_133));
  AOI2BB1X1 g10589__7482(.A0N (n_105), .A1N (n_123), .B0 (n_124), .Y
       (n_132));
  NOR2BX1 g10590__4733(.AN (n_107), .B (n_122), .Y (n_131));
  NOR2BX1 g10591__6161(.AN (n_103), .B (n_118), .Y (n_130));
  AND4XL g10592__9315(.A (n_54), .B (n_49), .C (n_53), .D (n_50), .Y
       (n_127));
  AND2X1 g10593__9945(.A (n_124), .B (n_105), .Y (n_129));
  NOR2BX1 g10594__2883(.AN (n_108), .B (n_120), .Y (n_128));
  OAI211X1 g10608__2346(.A0 (n_39), .A1 (n_223), .B0 (n_67), .C0
       (n_106), .Y (n_126));
  NOR2BX1 g10609__1666(.AN (n_64), .B (n_111), .Y (n_125));
  NAND2BX1 g10610__7410(.AN (n_115), .B (n_51), .Y (n_124));
  NOR2BX1 g10611__6417(.AN (n_52), .B (n_114), .Y (n_123));
  NOR2BX1 g10612__5477(.AN (n_65), .B (n_0), .Y (n_122));
  NOR2BX1 g10613__2398(.AN (n_62), .B (n_113), .Y (n_121));
  NOR2BX1 g10614__5107(.AN (n_48), .B (n_112), .Y (n_120));
  NOR2BX1 g10615__6260(.AN (n_59), .B (n_110), .Y (n_119));
  NOR2BX1 g10616__4319(.AN (n_47), .B (n_109), .Y (n_118));
  OAI211X1 g10620__8428(.A0 (n_41), .A1 (n_223), .B0 (n_55), .C0
       (n_104), .Y (n_117));
  INVX1 g10621(.A (n_102), .Y (n_116));
  INVX1 g10622(.A (n_107), .Y (n_106));
  INVX1 g10623(.A (n_104), .Y (n_105));
  OAI211X1 g10624__5526(.A0 (ack_rank_q[5]), .A1 (n_22), .B0
       (req_sync_q[7]), .C0 (n_3), .Y (n_102));
  NOR2X1 g10625__6783(.A (n_50), .B (n_58), .Y (n_115));
  NOR2BX1 g10626__3680(.AN (n_55), .B (n_53), .Y (n_114));
  NOR2BX1 g10628__1617(.AN (n_67), .B (n_61), .Y (n_113));
  NOR2X1 g10629__2802(.A (n_49), .B (n_69), .Y (n_112));
  AOI21X1 g10630__1705(.A0 (n_42), .A1 (n_38), .B0 (n_60), .Y (n_111));
  AOI21X1 g10631__5122(.A0 (n_40), .A1 (n_42), .B0 (n_54), .Y (n_110));
  NOR2X1 g10632__8246(.A (n_66), .B (n_56), .Y (n_109));
  NAND2X1 g10633__7098(.A (n_53), .B (n_50), .Y (n_101));
  OAI21X1 g10634__6131(.A0 (n_39), .A1 (n_43), .B0 (n_70), .Y (n_108));
  OAI21X1 g10635__1881(.A0 (n_39), .A1 (n_224), .B0 (n_68), .Y (n_107));
  AOI2BB1XL g10636__5115(.A0N (n_41), .A1N (n_224), .B0 (n_58), .Y
       (n_104));
  OAI21X1 g10637__7482(.A0 (n_41), .A1 (n_43), .B0 (n_57), .Y (n_103));
  INVX1 g10638(.A (n_85), .Y (n_100));
  INVX1 g10639(.A (n_84), .Y (n_99));
  INVX1 g10640(.A (n_83), .Y (n_98));
  INVX1 g10641(.A (n_82), .Y (n_97));
  INVX1 g10642(.A (n_81), .Y (n_96));
  INVX1 g10643(.A (n_80), .Y (n_95));
  INVX1 g10644(.A (n_79), .Y (n_94));
  INVX1 g10645(.A (n_78), .Y (n_93));
  INVX1 g10646(.A (n_77), .Y (n_92));
  INVX1 g10647(.A (n_76), .Y (n_91));
  INVX1 g10648(.A (n_75), .Y (n_90));
  INVX1 g10649(.A (n_74), .Y (n_89));
  INVX1 g10650(.A (n_73), .Y (n_88));
  INVX1 g10651(.A (n_72), .Y (n_87));
  INVX1 g10652(.A (n_71), .Y (n_86));
  OAI211X1 g10653__4733(.A0 (ack_rank_q[0]), .A1 (n_36), .B0
       (req_sync_q[0]), .C0 (n_3), .Y (n_85));
  OAI211X1 g10654__6161(.A0 (ack_source[4]), .A1 (n_19), .B0
       (req_rank[7]), .C0 (n_3), .Y (n_84));
  OAI211X1 g10655__9315(.A0 (ack_rank_q[4]), .A1 (n_34), .B0
       (req_sync_q[6]), .C0 (n_2), .Y (n_83));
  OAI211X1 g10656__9945(.A0 (ack_rank_q[8]), .A1 (n_33), .B0
       (req_sync_q[12]), .C0 (n_3), .Y (n_82));
  OAI211X1 g10657__2883(.A0 (ack_source[14]), .A1 (n_29), .B0
       (req_rank[11]), .C0 (n_2), .Y (n_81));
  OAI211X1 g10658__2346(.A0 (ack_source[15]), .A1 (n_17), .B0
       (req_rank[10]), .C0 (n_3), .Y (n_80));
  OAI211X1 g10659__1666(.A0 (ack_rank_q[9]), .A1 (n_16), .B0
       (req_sync_q[13]), .C0 (n_3), .Y (n_79));
  OAI211X1 g10660__7410(.A0 (ack_source[5]), .A1 (n_30), .B0
       (req_rank[6]), .C0 (n_2), .Y (n_78));
  OAI211X1 g10661__6417(.A0 (ack_rank_q[12]), .A1 (n_18), .B0
       (req_sync_q[10]), .C0 (n_2), .Y (n_77));
  OAI211X1 g10662__5477(.A0 (ack_rank_q[1]), .A1 (n_37), .B0
       (req_sync_q[1]), .C0 (n_2), .Y (n_76));
  OAI211X1 g10663__2398(.A0 (ack_rank_q[13]), .A1 (n_21), .B0
       (req_sync_q[11]), .C0 (n_2), .Y (n_75));
  OAI211X1 g10664__5107(.A0 (ack_source[2]), .A1 (n_20), .B0
       (req_rank[3]), .C0 (n_2), .Y (n_74));
  OAI211X1 g10665__6260(.A0 (ack_source[3]), .A1 (n_31), .B0
       (req_rank[2]), .C0 (n_3), .Y (n_73));
  OAI211X1 g10666__4319(.A0 (ack_source[8]), .A1 (n_35), .B0
       (req_rank[15]), .C0 (n_2), .Y (n_72));
  OAI211X1 g10667__8428(.A0 (ack_source[9]), .A1 (n_32), .B0
       (req_rank[14]), .C0 (n_3), .Y (n_71));
  INVX1 g10668(.A (n_69), .Y (n_70));
  NOR2BX1 g10670__5526(.AN (n_40), .B (n_223), .Y (n_69));
  NAND2BX1 g10671__6783(.AN (n_44), .B (n_40), .Y (n_68));
  NAND2BX1 g10672__3680(.AN (n_224), .B (n_40), .Y (n_67));
  AOI21X1 g10673__1617(.A0 (req_rank[10]), .A1 (n_7), .B0
       (pending_rank_q[10]), .Y (n_66));
  AOI21X1 g10674__2802(.A0 (req_rank[7]), .A1 (n_13), .B0
       (pending_rank_q[7]), .Y (n_65));
  AOI21X1 g10675__1705(.A0 (req_sync_q[13]), .A1 (n_6), .B0
       (pending_rank_q[9]), .Y (n_64));
  AOI21X1 g10676__5122(.A0 (req_rank[6]), .A1 (n_27), .B0
       (pending_rank_q[6]), .Y (n_63));
  AOI21X1 g10677__8246(.A0 (req_sync_q[7]), .A1 (n_24), .B0
       (pending_rank_q[5]), .Y (n_62));
  AOI21X1 g10678__7098(.A0 (req_sync_q[6]), .A1 (n_28), .B0
       (pending_rank_q[4]), .Y (n_61));
  AOI21X1 g10679__6131(.A0 (req_sync_q[12]), .A1 (n_12), .B0
       (pending_rank_q[8]), .Y (n_60));
  AOI21X1 g10680__1881(.A0 (req_sync_q[1]), .A1 (n_14), .B0
       (pending_rank_q[1]), .Y (n_59));
  INVX1 g10681(.A (n_56), .Y (n_57));
  NOR2X1 g10682__5115(.A (n_44), .B (n_39), .Y (n_46));
  NOR2BX1 g10683__7482(.AN (n_38), .B (n_44), .Y (n_58));
  NOR2BX1 g10684__4733(.AN (n_38), .B (n_223), .Y (n_56));
  NAND2BX1 g10685__6161(.AN (n_224), .B (n_38), .Y (n_55));
  AOI21X1 g10686__9315(.A0 (req_sync_q[0]), .A1 (n_11), .B0
       (pending_rank_q[0]), .Y (n_54));
  AOI21X1 g10687__9945(.A0 (req_sync_q[10]), .A1 (n_26), .B0
       (pending_rank_q[12]), .Y (n_53));
  AOI21X1 g10688__2883(.A0 (req_sync_q[11]), .A1 (n_8), .B0
       (pending_rank_q[13]), .Y (n_52));
  AOI21X1 g10689__2346(.A0 (req_rank[15]), .A1 (n_25), .B0
       (pending_rank_q[15]), .Y (n_51));
  AOI21X1 g10690__1666(.A0 (req_rank[14]), .A1 (n_10), .B0
       (pending_rank_q[14]), .Y (n_50));
  AOI21X1 g10691__7410(.A0 (req_rank[2]), .A1 (n_15), .B0
       (pending_rank_q[2]), .Y (n_49));
  AOI21X1 g10692__6417(.A0 (req_rank[3]), .A1 (n_9), .B0
       (pending_rank_q[3]), .Y (n_48));
  AOI21X1 g10693__5477(.A0 (req_rank[11]), .A1 (n_23), .B0
       (pending_rank_q[11]), .Y (n_47));
  INVX1 g10694(.A (n_42), .Y (n_43));
  NAND2BX1 g10695__2398(.AN (out_ready), .B (out_valid_q), .Y (n_45));
  NAND2X1 g10696__5107(.A (out_rank_q[2]), .B (out_rank_q[1]), .Y
       (n_44));
  NOR2X1 g10697__6260(.A (out_rank_q[2]), .B (out_rank_q[1]), .Y
       (n_42));
  NAND2X1 g10698__4319(.A (out_addr[3]), .B (out_rank_q[0]), .Y (n_41));
  NOR2X1 g10699__8428(.A (out_addr[3]), .B (out_rank_q[0]), .Y (n_40));
  NAND2X1 g10700__5526(.A (out_rank_q[0]), .B (n_5), .Y (n_39));
  NOR2X1 g10701__6783(.A (out_rank_q[0]), .B (n_5), .Y (n_38));
  INVX1 g10702(.A (pending_rank_q[1]), .Y (n_37));
  INVX1 g10703(.A (pending_rank_q[0]), .Y (n_36));
  INVX1 g10704(.A (pending_rank_q[15]), .Y (n_35));
  INVX1 g10705(.A (pending_rank_q[4]), .Y (n_34));
  INVX1 g10706(.A (pending_rank_q[8]), .Y (n_33));
  INVX1 g10707(.A (pending_rank_q[14]), .Y (n_32));
  INVX1 g10708(.A (pending_rank_q[2]), .Y (n_31));
  INVX1 g10709(.A (pending_rank_q[6]), .Y (n_30));
  INVX1 g10710(.A (pending_rank_q[11]), .Y (n_29));
  INVX1 g10711(.A (ack_rank_q[4]), .Y (n_28));
  INVX1 g10712(.A (ack_source[5]), .Y (n_27));
  INVX1 g10713(.A (ack_rank_q[12]), .Y (n_26));
  INVX1 g10714(.A (ack_source[8]), .Y (n_25));
  INVX1 g10715(.A (ack_rank_q[5]), .Y (n_24));
  INVX1 g10716(.A (ack_source[14]), .Y (n_23));
  INVX1 g10717(.A (pending_rank_q[5]), .Y (n_22));
  INVX1 g10718(.A (pending_rank_q[13]), .Y (n_21));
  INVX1 g10719(.A (pending_rank_q[3]), .Y (n_20));
  INVX1 g10720(.A (pending_rank_q[7]), .Y (n_19));
  INVX1 g10721(.A (pending_rank_q[12]), .Y (n_18));
  INVX1 g10722(.A (pending_rank_q[10]), .Y (n_17));
  INVX1 g10723(.A (pending_rank_q[9]), .Y (n_16));
  INVX1 g10724(.A (ack_source[3]), .Y (n_15));
  INVX1 g10725(.A (ack_rank_q[1]), .Y (n_14));
  INVX1 g10726(.A (ack_source[4]), .Y (n_13));
  INVX1 g10727(.A (ack_rank_q[8]), .Y (n_12));
  INVX1 g10728(.A (ack_rank_q[0]), .Y (n_11));
  INVX1 g10729(.A (ack_source[9]), .Y (n_10));
  INVX1 g10730(.A (ack_source[2]), .Y (n_9));
  INVX1 g10731(.A (ack_rank_q[13]), .Y (n_8));
  INVX1 g10732(.A (ack_source[15]), .Y (n_7));
  INVX1 g10733(.A (ack_rank_q[9]), .Y (n_6));
  INVX1 g10734(.A (out_addr[3]), .Y (n_5));
  INVX1 drc_bufs10740(.A (n_4), .Y (n_3));
  INVX1 drc_bufs10741(.A (n_4), .Y (n_2));
  INVX1 drc_bufs10742(.A (reset_release_q[1]), .Y (n_4));
  NOR4BX1 g2__3680(.AN (n_150), .B (n_59), .C (n_110), .D (n_128), .Y
       (n_1));
  NOR2BX1 g10743__1617(.AN (n_68), .B (n_63), .Y (n_0));
endmodule

module aer_pending_gray_rank_iprra_sync_core_reset(clk, rst_n,
     src_req_async, src_ack_async, out_addr, out_valid, out_ready);
  input clk, rst_n, out_ready;
  input [15:0] src_req_async;
  output [15:0] src_ack_async;
  output [3:0] out_addr;
  output out_valid;
  wire clk, rst_n, out_ready;
  wire [15:0] src_req_async;
  wire [15:0] src_ack_async;
  wire [3:0] out_addr;
  wire out_valid;
  aer_pending_rank_reuse_core_CODE_STYLE0_SELECTOR_STYLE1 core(.clk
       (clk), .rst_n (rst_n), .src_req_async (src_req_async),
       .src_ack_async (src_ack_async), .out_addr (out_addr), .out_valid
       (out_valid), .out_ready (out_ready));
endmodule

