
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 26 2026 14:48:38 KST (Aug 26 2026 05:48:38 UTC)

// Verification Directory fv/aer_improved_cutthrough 

module aer_improved_cutthrough(clk, rst_n, src_req_async,
     src_ack_async, out_addr, out_valid, out_ready);
  input clk, rst_n, out_ready;
  input [15:0] src_req_async;
  output [15:0] src_ack_async;
  output [3:0] out_addr;
  output out_valid;
  wire clk, rst_n, out_ready;
  wire [15:0] src_req_async;
  wire [15:0] src_ack_async;
  wire [3:0] out_addr;
  wire out_valid;
  wire [15:0] pending_q;
  wire [1:0] \local_rr_q[1] ;
  wire [1:0] \local_rr_q[2] ;
  wire [1:0] \local_rr_q[3] ;
  wire [1:0] \local_rr_q[0] ;
  wire [1:0] group_rr_q;
  wire [15:0] req_sync_q;
  wire [15:0] req_meta_q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_254;
  wire n_255;
  DFFRHQX1 \pending_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_229), .Q
       (pending_q[3]));
  DFFRHQX1 \pending_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_227), .Q
       (pending_q[1]));
  DFFRHQX1 \pending_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (pending_q[0]));
  DFFRHQX1 \pending_q_reg[15] (.RN (rst_n), .CK (clk), .D (n_228), .Q
       (pending_q[15]));
  DFFRHQX1 \pending_q_reg[7] (.RN (rst_n), .CK (clk), .D (n_219), .Q
       (pending_q[7]));
  DFFRHQX1 \pending_q_reg[8] (.RN (rst_n), .CK (clk), .D (n_212), .Q
       (pending_q[8]));
  DFFRHQX1 \pending_q_reg[9] (.RN (rst_n), .CK (clk), .D (n_217), .Q
       (pending_q[9]));
  DFFRHQX1 \pending_q_reg[4] (.RN (rst_n), .CK (clk), .D (n_222), .Q
       (pending_q[4]));
  DFFRHQX1 \pending_q_reg[11] (.RN (rst_n), .CK (clk), .D (n_215), .Q
       (pending_q[11]));
  DFFRHQX1 \pending_q_reg[12] (.RN (rst_n), .CK (clk), .D (n_223), .Q
       (pending_q[12]));
  DFFRHQX1 \pending_q_reg[13] (.RN (rst_n), .CK (clk), .D (n_213), .Q
       (pending_q[13]));
  DFFRHQX1 \pending_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_210), .Q
       (pending_q[2]));
  DFFRHQX1 \pending_q_reg[5] (.RN (rst_n), .CK (clk), .D (n_208), .Q
       (pending_q[5]));
  DFFRHQX1 \pending_q_reg[6] (.RN (rst_n), .CK (clk), .D (n_206), .Q
       (pending_q[6]));
  DFFRHQX1 \pending_q_reg[14] (.RN (rst_n), .CK (clk), .D (n_209), .Q
       (pending_q[14]));
  DFFRHQX1 \pending_q_reg[10] (.RN (rst_n), .CK (clk), .D (n_207), .Q
       (pending_q[10]));
  MX2XL g10075__2398(.A (n_232), .B (\local_rr_q[1] [1]), .S0 (n_196),
       .Y (n_234));
  MX2XL g10076__5107(.A (n_232), .B (\local_rr_q[2] [1]), .S0 (n_204),
       .Y (n_233));
  MX2XL g10077__6260(.A (\local_rr_q[3] [1]), .B (n_232), .S0 (n_201),
       .Y (n_231));
  MX2XL g10078__4319(.A (n_232), .B (\local_rr_q[0] [1]), .S0 (n_198),
       .Y (n_230));
  AOI21XL g10095__8428(.A0 (n_214), .A1 (n_226), .B0 (n_69), .Y
       (n_229));
  DFFRHQX1 \out_addr_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_200), .Q
       (out_addr[1]));
  DFFRHQX1 \local_rr_q_reg[2][0] (.RN (rst_n), .CK (clk), .D (n_205),
       .Q (\local_rr_q[2] [0]));
  AOI21XL g10097__5526(.A0 (n_218), .A1 (n_216), .B0 (n_64), .Y
       (n_228));
  AOI21XL g10098__6783(.A0 (n_224), .A1 (n_226), .B0 (n_72), .Y
       (n_227));
  AOI21X1 g10099__3680(.A0 (n_224), .A1 (n_220), .B0 (n_70), .Y
       (n_225));
  AOI21X1 g10100__1617(.A0 (n_221), .A1 (n_211), .B0 (n_65), .Y
       (n_223));
  AOI21X1 g10102__2802(.A0 (n_221), .A1 (n_220), .B0 (n_57), .Y
       (n_222));
  AOI21XL g10103__1705(.A0 (n_218), .A1 (n_226), .B0 (n_62), .Y
       (n_219));
  AOI21XL g10104__5122(.A0 (n_224), .A1 (n_216), .B0 (n_61), .Y
       (n_217));
  AOI21XL g10087__8246(.A0 (n_214), .A1 (n_216), .B0 (n_60), .Y
       (n_215));
  AOI21XL g10105__7098(.A0 (n_221), .A1 (n_216), .B0 (n_66), .Y
       (n_213));
  AOI21X1 g10085__6131(.A0 (n_224), .A1 (n_211), .B0 (n_56), .Y
       (n_212));
  AOI21X1 g10089__1881(.A0 (n_214), .A1 (n_220), .B0 (n_73), .Y
       (n_210));
  AOI21X1 g10096__5115(.A0 (n_218), .A1 (n_211), .B0 (n_67), .Y
       (n_209));
  DFFRHQX1 \out_addr_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_195), .Q
       (out_addr[0]));
  AOI2BB1XL g10101__7482(.A0N (n_192), .A1N (n_193), .B0 (n_63), .Y
       (n_208));
  AOI21X1 g10086__4733(.A0 (n_214), .A1 (n_211), .B0 (n_54), .Y
       (n_207));
  AOI21X1 g10088__6161(.A0 (n_218), .A1 (n_220), .B0 (n_59), .Y
       (n_206));
  MX2XL g10109__9315(.A (n_202), .B (\local_rr_q[2] [0]), .S0 (n_204),
       .Y (n_205));
  MX2XL g10110__9945(.A (\local_rr_q[3] [0]), .B (n_202), .S0 (n_201),
       .Y (n_203));
  MX2XL g10120__2883(.A (out_addr[1]), .B (n_190), .S0 (n_194), .Y
       (n_200));
  MX2XL g10106__2346(.A (n_202), .B (\local_rr_q[0] [0]), .S0 (n_198),
       .Y (n_199));
  MX2XL g10107__1666(.A (n_202), .B (\local_rr_q[1] [0]), .S0 (n_196),
       .Y (n_197));
  MX2XL g10111__7410(.A (out_addr[0]), .B (n_191), .S0 (n_194), .Y
       (n_195));
  INVX1 g10112(.A (n_193), .Y (n_226));
  NOR2X1 g10117__6417(.A (n_189), .B (n_202), .Y (n_216));
  INVX1 g10121(.A (n_192), .Y (n_221));
  XNOR2X1 g10108__5477(.A (n_186), .B (n_191), .Y (n_232));
  NOR2X1 g10126__2398(.A (n_187), .B (n_190), .Y (n_224));
  NAND2X1 g10114__5107(.A (n_188), .B (n_191), .Y (n_193));
  NOR2X1 g10115__6260(.A (n_189), .B (n_191), .Y (n_211));
  NOR2BX1 g10116__4319(.AN (n_188), .B (n_191), .Y (n_220));
  NAND2X1 g10123__8428(.A (n_187), .B (n_186), .Y (n_192));
  NOR2X1 g10122__5526(.A (n_187), .B (n_186), .Y (n_214));
  NOR2X1 g10125__6783(.A (n_131), .B (n_186), .Y (n_218));
  INVX1 g10118(.A (n_191), .Y (n_202));
  INVX1 g10127(.A (n_186), .Y (n_190));
  NAND2X1 g10119__3680(.A (n_148), .B (n_185), .Y (n_191));
  AOI221X1 g10128__1617(.A0 (n_111), .A1 (n_255), .B0 (n_254), .B1
       (n_166), .C0 (n_184), .Y (n_186));
  AOI221X1 g10124__2802(.A0 (n_68), .A1 (n_157), .B0 (\local_rr_q[1]
       [0]), .B1 (n_134), .C0 (n_183), .Y (n_185));
  OAI211X1 g10130__1705(.A0 (n_178), .A1 (n_156), .B0 (n_179), .C0
       (n_182), .Y (n_184));
  OAI211X1 g10129__5122(.A0 (\local_rr_q[3] [0]), .A1 (n_158), .B0
       (n_146), .C0 (n_181), .Y (n_183));
  NOR4X1 g10132__8246(.A (n_150), .B (n_154), .C (n_177), .D (n_180),
       .Y (n_182));
  NOR4BX1 g10131__7098(.AN (n_137), .B (n_174), .C (n_172), .D (n_175),
       .Y (n_181));
  OAI221X1 g10135__6131(.A0 (n_164), .A1 (n_173), .B0 (n_161), .B1
       (n_171), .C0 (n_170), .Y (n_180));
  AOI32X1 g10139__1881(.A0 (\local_rr_q[2] [1]), .A1 (n_145), .A2
       (n_144), .B0 (n_178), .B1 (n_159), .Y (n_179));
  OAI211X1 g10134__5115(.A0 (n_254), .A1 (n_167), .B0 (n_136), .C0
       (n_155), .Y (n_177));
  NOR2XL g10136__7482(.A (\local_rr_q[2] [0]), .B (n_168), .Y (n_175));
  AOI21X1 g10137__4733(.A0 (n_163), .A1 (n_173), .B0 (\local_rr_q[1]
       [0]), .Y (n_174));
  AOI21X1 g10138__6161(.A0 (n_171), .A1 (n_160), .B0 (\local_rr_q[0]
       [0]), .Y (n_172));
  NOR2X1 g10140__9315(.A (n_165), .B (n_162), .Y (n_170));
  OAI211X1 g10141__9945(.A0 (n_2), .A1 (n_194), .B0 (n_196), .C0
       (n_204), .Y (n_169));
  NOR2BX1 g10143__2883(.AN (n_167), .B (n_166), .Y (n_168));
  NOR2BX1 g10144__2346(.AN (n_164), .B (n_163), .Y (n_165));
  NOR2BX1 g10146__1666(.AN (n_161), .B (n_160), .Y (n_162));
  INVX1 g10153(.A (n_158), .Y (n_159));
  INVXL g10154(.A (n_156), .Y (n_157));
  AOI33XL g10142__7410(.A0 (\local_rr_q[0] [1]), .A1 (n_153), .A2
       (n_138), .B0 (\local_rr_q[1] [1]), .B1 (n_151), .B2 (n_141), .Y
       (n_155));
  NOR4X1 g10148__6417(.A (\local_rr_q[0] [1]), .B (n_139), .C (n_140),
       .D (n_152), .Y (n_154));
  OR3X1 g10166__5477(.A (n_96), .B (n_153), .C (n_152), .Y (n_171));
  OR3X1 g10169__2398(.A (n_142), .B (n_151), .C (n_149), .Y (n_173));
  NOR4X1 g10152__5107(.A (\local_rr_q[1] [1]), .B (n_151), .C (n_132),
       .D (n_149), .Y (n_150));
  OAI211X1 g10150__6260(.A0 (n_143), .A1 (n_102), .B0
       (\local_rr_q[3] [0]), .C0 (n_255), .Y (n_148));
  OAI211X1 g10149__4319(.A0 (n_145), .A1 (n_99), .B0 (\local_rr_q[2]
       [0]), .C0 (n_144), .Y (n_146));
  NAND3BXL g10156__8428(.AN (n_143), .B (n_100), .C (n_255), .Y
       (n_156));
  NAND3X1 g10155__5526(.A (n_101), .B (n_90), .C (n_255), .Y (n_158));
  NAND4XL g10170__6783(.A (n_95), .B (n_142), .C (n_133), .D (n_141),
       .Y (n_163));
  OR4X1 g10168__3680(.A (n_94), .B (n_92), .C (n_145), .D (n_135), .Y
       (n_167));
  NAND3BXL g10167__1617(.AN (n_140), .B (n_139), .C (n_138), .Y
       (n_160));
  DFFRHQX1 \out_addr_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_129), .Q
       (out_addr[3]));
  OAI211X1 g10145__2802(.A0 (n_153), .A1 (n_97), .B0 (\local_rr_q[0]
       [0]), .C0 (n_138), .Y (n_137));
  OR4X1 g10151__1705(.A (\local_rr_q[2] [1]), .B (n_145), .C (n_98), .D
       (n_135), .Y (n_136));
  AOI21X1 g10163__5122(.A0 (n_133), .A1 (n_132), .B0 (n_149), .Y
       (n_134));
  NOR3XL g10165__8246(.A (n_93), .B (n_145), .C (n_135), .Y (n_166));
  AND2XL g10158__7098(.A (n_194), .B (n_255), .Y (n_201));
  NAND2X1 g10160__6131(.A (n_194), .B (n_144), .Y (n_204));
  DFFRHQX1 \out_addr_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_127), .Q
       (out_addr[2]));
  NAND2X1 g10159__1881(.A (n_194), .B (n_138), .Y (n_198));
  NAND2X1 g10161__5115(.A (n_194), .B (n_141), .Y (n_196));
  INVX1 g10171(.A (n_138), .Y (n_152));
  INVX1 g10176(.A (n_135), .Y (n_144));
  MX2XL g10179__4733(.A (group_rr_q[0]), .B (n_131), .S0 (n_194), .Y
       (n_130));
  MX2XL g10164__6161(.A (out_addr[3]), .B (n_128), .S0 (n_194), .Y
       (n_129));
  INVX1 g10177(.A (n_141), .Y (n_149));
  NOR2X1 g10172__9315(.A (n_119), .B (n_128), .Y (n_188));
  NAND2X1 g10173__9945(.A (n_120), .B (n_128), .Y (n_189));
  NOR2X1 g10175__2883(.A (n_187), .B (n_128), .Y (n_138));
  MX2XL g10178__2346(.A (out_addr[2]), .B (n_187), .S0 (n_194), .Y
       (n_127));
  NOR2X1 g10181__1666(.A (n_131), .B (n_128), .Y (n_141));
  NAND2X1 g10180__7410(.A (n_131), .B (n_128), .Y (n_135));
  OAI2BB1X1 g10183__6417(.A0N (n_122), .A1N (n_125), .B0 (n_115), .Y
       (n_128));
  INVX1 g10184(.A (n_187), .Y (n_131));
  XNOR2X1 g10185__5477(.A (group_rr_q[0]), .B (n_124), .Y (n_187));
  DFFRHQX1 out_valid_q_reg(.RN (rst_n), .CK (clk), .D (n_121), .Q
       (out_valid));
  OAI21XL g10186__2398(.A0 (n_123), .A1 (n_117), .B0 (n_112), .Y
       (n_125));
  OAI21X1 g10188__5107(.A0 (n_116), .A1 (n_123), .B0 (n_122), .Y
       (n_124));
  NAND2X1 g10189__6260(.A (n_120), .B (n_118), .Y (n_121));
  NOR2X1 g10191__4319(.A (n_119), .B (n_118), .Y (n_194));
  AOI21X1 g10190__8428(.A0 (n_114), .A1 (n_116), .B0 (n_110), .Y
       (n_117));
  NOR3BX1 g10193__5526(.AN (n_116), .B (n_113), .C (n_109), .Y (n_118));
  OA21X1 g10192__6783(.A0 (group_rr_q[1]), .A1 (n_108), .B0 (n_115), .Y
       (n_122));
  OAI2BB1X1 g10194__3680(.A0N (n_114), .A1N (n_113), .B0 (n_112), .Y
       (n_123));
  OAI31X1 g10197__1617(.A0 (\local_rr_q[3] [1]), .A1 (n_143), .A2
       (n_103), .B0 (n_91), .Y (n_111));
  NAND2X1 g10195__2802(.A (group_rr_q[1]), .B (n_110), .Y (n_115));
  NAND2BX1 g10196__1705(.AN (n_114), .B (n_109), .Y (n_112));
  NOR2BX1 g10198__5122(.AN (n_108), .B (n_110), .Y (n_116));
  OAI21X1 g10199__8246(.A0 (group_rr_q[0]), .A1 (n_107), .B0 (n_106),
       .Y (n_109));
  OAI22X1 g10200__7098(.A0 (n_1), .A1 (n_107), .B0 (group_rr_q[0]), .B1
       (n_106), .Y (n_110));
  OAI21X1 g10201__6131(.A0 (group_rr_q[0]), .A1 (n_104), .B0 (n_105),
       .Y (n_113));
  MX2XL g10202__1881(.A (n_105), .B (n_104), .S0 (group_rr_q[0]), .Y
       (n_108));
  INVX1 g10203(.A (n_102), .Y (n_103));
  NOR2X1 g10205__5115(.A (n_101), .B (n_100), .Y (n_102));
  INVX1 g10207(.A (n_98), .Y (n_99));
  NOR2BX1 g10204__7482(.AN (n_96), .B (n_139), .Y (n_97));
  NAND2BXL g10206__4733(.AN (n_153), .B (n_96), .Y (n_140));
  NAND2BX1 g10208__6161(.AN (n_95), .B (n_142), .Y (n_132));
  NAND2X1 g10209__9315(.A (n_94), .B (n_93), .Y (n_98));
  NOR3BX1 g10213__9945(.AN (n_95), .B (n_79), .C (n_85), .Y (n_104));
  NOR3BX1 g10212__2883(.AN (n_139), .B (n_88), .C (n_89), .Y (n_105));
  NOR3BX1 g10210__2346(.AN (n_101), .B (n_86), .C (n_87), .Y (n_107));
  NOR3X1 g10219__1666(.A (n_77), .B (n_83), .C (n_94), .Y (n_106));
  INVXL g10211(.A (n_93), .Y (n_92));
  OAI21X1 g10216__7410(.A0 (\local_rr_q[3] [1]), .A1 (n_81), .B0
       (n_91), .Y (n_143));
  INVX1 g10217(.A (n_90), .Y (n_100));
  INVX1 g10218(.A (n_133), .Y (n_151));
  AOI21X1 g10214__6417(.A0 (\local_rr_q[1] [0]), .A1 (n_78), .B0
       (n_84), .Y (n_142));
  AOI21X1 g10215__5477(.A0 (\local_rr_q[2] [0]), .A1 (n_76), .B0
       (n_82), .Y (n_93));
  AOI22X1 g10220__2398(.A0 (n_5), .A1 (n_89), .B0 (\local_rr_q[0] [1]),
       .B1 (n_88), .Y (n_96));
  AOI22X1 g10221__5107(.A0 (n_4), .A1 (n_87), .B0 (\local_rr_q[3] [1]),
       .B1 (n_86), .Y (n_90));
  AOI22X1 g10223__6260(.A0 (n_3), .A1 (n_85), .B0 (\local_rr_q[1] [0]),
       .B1 (n_84), .Y (n_133));
  MX2XL g10222__4319(.A (n_75), .B (n_74), .S0 (\local_rr_q[0] [1]), .Y
       (n_153));
  MX2X1 g10224__8428(.A (n_83), .B (n_82), .S0 (\local_rr_q[2] [0]), .Y
       (n_145));
  NAND2X1 g10225__5526(.A (\local_rr_q[3] [1]), .B (n_80), .Y (n_91));
  NOR2BX1 g10226__6783(.AN (n_81), .B (n_80), .Y (n_101));
  AOI21X1 g10227__3680(.A0 (\local_rr_q[1] [0]), .A1 (n_79), .B0
       (n_78), .Y (n_95));
  AO21X1 g10228__1617(.A0 (\local_rr_q[2] [0]), .A1 (n_77), .B0 (n_76),
       .Y (n_94));
  NOR2X1 g10229__2802(.A (n_75), .B (n_74), .Y (n_139));
  OAI21X1 g10236__1705(.A0 (n_71), .A1 (n_73), .B0 (n_72), .Y (n_89));
  OAI21X1 g10231__5122(.A0 (n_71), .A1 (n_70), .B0 (n_69), .Y (n_88));
  OAI21X1 g10232__8246(.A0 (n_68), .A1 (n_67), .B0 (n_66), .Y (n_87));
  OAI21X1 g10233__7098(.A0 (n_68), .A1 (n_65), .B0 (n_64), .Y (n_86));
  OAI22X1 g10234__6131(.A0 (\local_rr_q[3] [0]), .A1 (n_67), .B0
       (n_68), .B1 (n_64), .Y (n_80));
  MX2XL g10235__1881(.A (n_65), .B (n_66), .S0 (\local_rr_q[3] [0]), .Y
       (n_81));
  OAI22X1 g10230__5115(.A0 (\local_rr_q[1] [1]), .A1 (n_63), .B0
       (n_58), .B1 (n_62), .Y (n_84));
  OAI22X1 g10243__7482(.A0 (\local_rr_q[0] [0]), .A1 (n_70), .B0
       (n_71), .B1 (n_72), .Y (n_75));
  OAI22X1 g10238__4733(.A0 (\local_rr_q[2] [1]), .A1 (n_61), .B0
       (n_55), .B1 (n_60), .Y (n_82));
  OAI22X1 g10239__6161(.A0 (\local_rr_q[1] [1]), .A1 (n_59), .B0
       (n_58), .B1 (n_57), .Y (n_78));
  OAI22X1 g10240__9315(.A0 (\local_rr_q[0] [0]), .A1 (n_73), .B0
       (n_71), .B1 (n_69), .Y (n_74));
  OAI22X1 g10241__9945(.A0 (\local_rr_q[1] [1]), .A1 (n_57), .B0
       (n_58), .B1 (n_59), .Y (n_85));
  OAI22X1 g10242__2883(.A0 (\local_rr_q[2] [1]), .A1 (n_56), .B0
       (n_55), .B1 (n_54), .Y (n_83));
  OAI22X1 g10237__2346(.A0 (\local_rr_q[2] [1]), .A1 (n_54), .B0
       (n_55), .B1 (n_56), .Y (n_76));
  NAND2X1 g10244__1666(.A (n_63), .B (n_62), .Y (n_79));
  NAND2X1 g10245__7410(.A (n_61), .B (n_60), .Y (n_77));
  AOI21X1 g10277__6417(.A0 (req_sync_q[1]), .A1 (n_32), .B0
       (pending_q[1]), .Y (n_72));
  AOI21X1 g10263__5477(.A0 (req_sync_q[2]), .A1 (n_38), .B0
       (pending_q[2]), .Y (n_73));
  AOI21X1 g10264__2398(.A0 (req_sync_q[8]), .A1 (n_30), .B0
       (pending_q[8]), .Y (n_56));
  AOI21X1 g10265__5107(.A0 (req_sync_q[3]), .A1 (n_26), .B0
       (pending_q[3]), .Y (n_69));
  AOI21X1 g10266__6260(.A0 (req_sync_q[7]), .A1 (n_40), .B0
       (pending_q[7]), .Y (n_62));
  AOI21X1 g10267__4319(.A0 (req_sync_q[11]), .A1 (n_28), .B0
       (pending_q[11]), .Y (n_60));
  AOI21X1 g10268__8428(.A0 (req_sync_q[5]), .A1 (n_46), .B0
       (pending_q[5]), .Y (n_63));
  AOI21X1 g10269__5526(.A0 (req_sync_q[4]), .A1 (n_52), .B0
       (pending_q[4]), .Y (n_57));
  AOI21X1 g10270__6783(.A0 (req_sync_q[15]), .A1 (n_36), .B0
       (pending_q[15]), .Y (n_64));
  AOI21X1 g10271__3680(.A0 (req_sync_q[9]), .A1 (n_42), .B0
       (pending_q[9]), .Y (n_61));
  AOI21X1 g10272__1617(.A0 (req_sync_q[10]), .A1 (n_48), .B0
       (pending_q[10]), .Y (n_54));
  AOI21X1 g10273__2802(.A0 (req_sync_q[13]), .A1 (n_44), .B0
       (pending_q[13]), .Y (n_66));
  AOI21X1 g10274__1705(.A0 (req_sync_q[14]), .A1 (n_24), .B0
       (pending_q[14]), .Y (n_67));
  AOI21X1 g10275__5122(.A0 (req_sync_q[0]), .A1 (n_22), .B0
       (pending_q[0]), .Y (n_70));
  AOI21X1 g10276__8246(.A0 (req_sync_q[12]), .A1 (n_34), .B0
       (pending_q[12]), .Y (n_65));
  AOI21X1 g10262__7098(.A0 (req_sync_q[6]), .A1 (n_50), .B0
       (pending_q[6]), .Y (n_59));
  AOI21X1 g10293__6131(.A0 (pending_q[4]), .A1 (n_52), .B0 (n_20), .Y
       (n_53));
  AOI21X1 g10279__1881(.A0 (pending_q[6]), .A1 (n_50), .B0 (n_17), .Y
       (n_51));
  AOI21X1 g10280__5115(.A0 (pending_q[10]), .A1 (n_48), .B0 (n_9), .Y
       (n_49));
  AOI21X1 g10281__7482(.A0 (pending_q[5]), .A1 (n_46), .B0 (n_10), .Y
       (n_47));
  AOI21X1 g10282__4733(.A0 (pending_q[13]), .A1 (n_44), .B0 (n_18), .Y
       (n_45));
  AOI21X1 g10283__6161(.A0 (pending_q[9]), .A1 (n_42), .B0 (n_7), .Y
       (n_43));
  AOI21X1 g10284__9315(.A0 (pending_q[7]), .A1 (n_40), .B0 (n_16), .Y
       (n_41));
  AOI21X1 g10285__9945(.A0 (pending_q[2]), .A1 (n_38), .B0 (n_21), .Y
       (n_39));
  AOI21X1 g10286__2883(.A0 (pending_q[15]), .A1 (n_36), .B0 (n_14), .Y
       (n_37));
  AOI21X1 g10287__2346(.A0 (pending_q[12]), .A1 (n_34), .B0 (n_13), .Y
       (n_35));
  AOI21X1 g10288__1666(.A0 (pending_q[1]), .A1 (n_32), .B0 (n_15), .Y
       (n_33));
  AOI21X1 g10289__7410(.A0 (pending_q[8]), .A1 (n_30), .B0 (n_8), .Y
       (n_31));
  AOI21X1 g10290__6417(.A0 (pending_q[11]), .A1 (n_28), .B0 (n_6), .Y
       (n_29));
  AOI21X1 g10291__5477(.A0 (pending_q[3]), .A1 (n_26), .B0 (n_19), .Y
       (n_27));
  AOI21X1 g10292__2398(.A0 (pending_q[14]), .A1 (n_24), .B0 (n_12), .Y
       (n_25));
  AOI21X1 g10278__5107(.A0 (pending_q[0]), .A1 (n_22), .B0 (n_11), .Y
       (n_23));
  INVX1 g10317(.A (req_sync_q[2]), .Y (n_21));
  INVX1 g10314(.A (req_sync_q[4]), .Y (n_20));
  INVX1 g10315(.A (req_sync_q[3]), .Y (n_19));
  INVX1 g10316(.A (req_sync_q[13]), .Y (n_18));
  INVX1 g10303(.A (req_sync_q[6]), .Y (n_17));
  INVX1 g10319(.A (req_sync_q[7]), .Y (n_16));
  INVX1 g10296(.A (req_sync_q[1]), .Y (n_15));
  INVX1 g10318(.A (req_sync_q[15]), .Y (n_14));
  INVX1 g10297(.A (req_sync_q[12]), .Y (n_13));
  INVX1 g10294(.A (req_sync_q[14]), .Y (n_12));
  INVX1 g10298(.A (req_sync_q[0]), .Y (n_11));
  INVX1 g10295(.A (req_sync_q[5]), .Y (n_10));
  INVX1 g10300(.A (req_sync_q[10]), .Y (n_9));
  INVX1 g10302(.A (req_sync_q[8]), .Y (n_8));
  INVX1 g10299(.A (req_sync_q[9]), .Y (n_7));
  INVX1 g10301(.A (req_sync_q[11]), .Y (n_6));
  DFFRHQX1 \req_sync_q_reg[14] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[14]), .Q (req_sync_q[14]));
  DFFRHQX1 \req_sync_q_reg[5] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[5]), .Q (req_sync_q[5]));
  DFFRHQX1 \req_sync_q_reg[12] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[12]), .Q (req_sync_q[12]));
  DFFRHQX1 \req_sync_q_reg[0] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[0]), .Q (req_sync_q[0]));
  DFFRHQX1 \req_sync_q_reg[9] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[9]), .Q (req_sync_q[9]));
  DFFRHQX1 \req_sync_q_reg[11] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[11]), .Q (req_sync_q[11]));
  DFFRHQX1 \req_sync_q_reg[6] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[6]), .Q (req_sync_q[6]));
  DFFRHQX1 \req_sync_q_reg[4] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[4]), .Q (req_sync_q[4]));
  DFFRHQX1 \req_sync_q_reg[3] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[3]), .Q (req_sync_q[3]));
  DFFRHQX1 \req_sync_q_reg[2] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[2]), .Q (req_sync_q[2]));
  DFFRHQX1 \req_sync_q_reg[7] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[7]), .Q (req_sync_q[7]));
  OAI22X1 g10329__6260(.A0 (\local_rr_q[0] [1]), .A1 (\local_rr_q[0]
       [0]), .B0 (n_5), .B1 (n_71), .Y (n_161));
  DFFRHQX1 \req_sync_q_reg[13] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[13]), .Q (req_sync_q[13]));
  OAI22X1 g10326__4319(.A0 (\local_rr_q[3] [1]), .A1 (\local_rr_q[3]
       [0]), .B0 (n_4), .B1 (n_68), .Y (n_178));
  DFFRHQX1 \req_sync_q_reg[15] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[15]), .Q (req_sync_q[15]));
  OAI22X1 g10328__8428(.A0 (\local_rr_q[1] [0]), .A1 (\local_rr_q[1]
       [1]), .B0 (n_3), .B1 (n_58), .Y (n_164));
  DFFRHQX1 \req_sync_q_reg[10] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[10]), .Q (req_sync_q[10]));
  DFFRHQX1 \req_sync_q_reg[8] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[8]), .Q (req_sync_q[8]));
  DFFRHQX1 \req_sync_q_reg[1] (.RN (rst_n), .CK (clk), .D
       (req_meta_q[1]), .Q (req_sync_q[1]));
  AOI22X1 g10330__6783(.A0 (n_2), .A1 (group_rr_q[0]), .B0
       (group_rr_q[1]), .B1 (n_1), .Y (n_114));
  INVX1 g10339(.A (n_119), .Y (n_120));
  DFFRHQX1 \req_meta_q_reg[1] (.RN (rst_n), .CK (clk), .D
       (src_req_async[1]), .Q (req_meta_q[1]));
  DFFRHQX1 \req_meta_q_reg[10] (.RN (rst_n), .CK (clk), .D
       (src_req_async[10]), .Q (req_meta_q[10]));
  DFFRHQX1 \req_meta_q_reg[2] (.RN (rst_n), .CK (clk), .D
       (src_req_async[2]), .Q (req_meta_q[2]));
  DFFRHQX1 \req_meta_q_reg[0] (.RN (rst_n), .CK (clk), .D
       (src_req_async[0]), .Q (req_meta_q[0]));
  DFFRHQX1 \req_meta_q_reg[8] (.RN (rst_n), .CK (clk), .D
       (src_req_async[8]), .Q (req_meta_q[8]));
  DFFRHQX1 \req_meta_q_reg[11] (.RN (rst_n), .CK (clk), .D
       (src_req_async[11]), .Q (req_meta_q[11]));
  DFFRHQX1 \req_meta_q_reg[13] (.RN (rst_n), .CK (clk), .D
       (src_req_async[13]), .Q (req_meta_q[13]));
  NOR2BX1 g10348__3680(.AN (out_valid), .B (out_ready), .Y (n_119));
  DFFRHQX1 \req_meta_q_reg[3] (.RN (rst_n), .CK (clk), .D
       (src_req_async[3]), .Q (req_meta_q[3]));
  DFFRHQX1 \req_meta_q_reg[9] (.RN (rst_n), .CK (clk), .D
       (src_req_async[9]), .Q (req_meta_q[9]));
  DFFRHQX1 \req_meta_q_reg[7] (.RN (rst_n), .CK (clk), .D
       (src_req_async[7]), .Q (req_meta_q[7]));
  DFFRHQX1 \req_meta_q_reg[6] (.RN (rst_n), .CK (clk), .D
       (src_req_async[6]), .Q (req_meta_q[6]));
  DFFRHQX1 \req_meta_q_reg[15] (.RN (rst_n), .CK (clk), .D
       (src_req_async[15]), .Q (req_meta_q[15]));
  DFFRHQX1 \req_meta_q_reg[4] (.RN (rst_n), .CK (clk), .D
       (src_req_async[4]), .Q (req_meta_q[4]));
  DFFRHQX1 \req_meta_q_reg[14] (.RN (rst_n), .CK (clk), .D
       (src_req_async[14]), .Q (req_meta_q[14]));
  DFFRHQX1 \req_meta_q_reg[12] (.RN (rst_n), .CK (clk), .D
       (src_req_async[12]), .Q (req_meta_q[12]));
  DFFRHQX1 \req_meta_q_reg[5] (.RN (rst_n), .CK (clk), .D
       (src_req_async[5]), .Q (req_meta_q[5]));
  MXI2XL g2(.A (n_55), .B (\local_rr_q[2] [1]), .S0 (\local_rr_q[2]
       [0]), .Y (n_254));
  DFFRX1 \ack_q_reg[7] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (src_ack_async[7]), .QN (n_40));
  DFFRX1 \local_rr_q_reg[3][1] (.RN (rst_n), .CK (clk), .D (n_231), .Q
       (\local_rr_q[3] [1]), .QN (n_4));
  DFFRX1 \ack_q_reg[5] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (src_ack_async[5]), .QN (n_46));
  DFFRX1 \ack_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_39), .Q
       (src_ack_async[2]), .QN (n_38));
  DFFRX1 \ack_q_reg[13] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (src_ack_async[13]), .QN (n_44));
  DFFRX1 \local_rr_q_reg[1][0] (.RN (rst_n), .CK (clk), .D (n_197), .Q
       (\local_rr_q[1] [0]), .QN (n_3));
  DFFRX1 \group_rr_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_169), .Q
       (group_rr_q[1]), .QN (n_2));
  DFFRX1 \group_rr_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_130), .Q
       (group_rr_q[0]), .QN (n_1));
  DFFRX1 \ack_q_reg[10] (.RN (rst_n), .CK (clk), .D (n_49), .Q
       (src_ack_async[10]), .QN (n_48));
  DFFRX1 \ack_q_reg[12] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (src_ack_async[12]), .QN (n_34));
  DFFRX1 \local_rr_q_reg[2][1] (.RN (rst_n), .CK (clk), .D (n_233), .Q
       (\local_rr_q[2] [1]), .QN (n_55));
  DFFRX1 \local_rr_q_reg[0][0] (.RN (rst_n), .CK (clk), .D (n_199), .Q
       (\local_rr_q[0] [0]), .QN (n_71));
  DFFRX1 \ack_q_reg[14] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (src_ack_async[14]), .QN (n_24));
  DFFRX1 \ack_q_reg[9] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (src_ack_async[9]), .QN (n_42));
  DFFRX1 \ack_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_23), .Q
       (src_ack_async[0]), .QN (n_22));
  DFFRX1 \ack_q_reg[11] (.RN (rst_n), .CK (clk), .D (n_29), .Q
       (src_ack_async[11]), .QN (n_28));
  DFFRX1 \ack_q_reg[15] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (src_ack_async[15]), .QN (n_36));
  DFFRX1 \ack_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_27), .Q
       (src_ack_async[3]), .QN (n_26));
  DFFRX1 \ack_q_reg[6] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (src_ack_async[6]), .QN (n_50));
  DFFRX1 \ack_q_reg[8] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (src_ack_async[8]), .QN (n_30));
  DFFRX1 \ack_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (src_ack_async[1]), .QN (n_32));
  DFFRX1 \local_rr_q_reg[0][1] (.RN (rst_n), .CK (clk), .D (n_230), .Q
       (\local_rr_q[0] [1]), .QN (n_5));
  DFFRX1 \ack_q_reg[4] (.RN (rst_n), .CK (clk), .D (n_53), .Q
       (src_ack_async[4]), .QN (n_52));
  DFFRX1 \local_rr_q_reg[1][1] (.RN (rst_n), .CK (clk), .D (n_234), .Q
       (\local_rr_q[1] [1]), .QN (n_58));
  DFFRX1 \local_rr_q_reg[3][0] (.RN (rst_n), .CK (clk), .D (n_203), .Q
       (\local_rr_q[3] [0]), .QN (n_68));
  NOR2BX1 g10504(.AN (n_128), .B (n_131), .Y (n_255));
endmodule

