/*
###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID <REMOTE_HOST>)
#  Generated on:      Fri Aug 21 03:19:59 2026
#  Design:            aer_pending_direct_gray_sync_core_reset
#  Command:           saveNetlist <REMOTE_HOME>/aer_2026/p8dgscr_pnr_180nm_v2/outputs/p8dgscr_pnr/aer_pending_direct_gray_sync_core_reset_postroute.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 21 2026 02:45:47 KST (Aug 20 2026 17:45:47 UTC)
// Verification Directory fv/aer_pending_direct_gray_sync_core_reset 
module aer_pending_direct_gray_sync_core_reset (
	clk, 
	rst_n, 
	src_req_async, 
	src_ack_async, 
	out_addr, 
	out_valid, 
	out_ready);
   input clk;
   input rst_n;
   input [15:0] src_req_async;
   output [15:0] src_ack_async;
   output [3:0] out_addr;
   output out_valid;
   input out_ready;

   // Internal wires
   wire FE_PHN82_req_meta_q_15;
   wire FE_PHN81_req_meta_q_0;
   wire FE_PHN80_reset_release_q_0;
   wire FE_PHN79_req_meta_q_4;
   wire FE_PHN78_req_meta_q_8;
   wire FE_PHN77_req_meta_q_2;
   wire FE_PHN76_req_meta_q_1;
   wire FE_PHN75_req_meta_q_11;
   wire FE_PHN74_req_meta_q_6;
   wire FE_PHN73_req_meta_q_12;
   wire FE_PHN72_req_meta_q_9;
   wire FE_PHN71_req_meta_q_3;
   wire FE_PHN70_req_meta_q_14;
   wire FE_PHN69_req_meta_q_13;
   wire FE_PHN68_reset_release_q_0;
   wire FE_PHN67_n_24;
   wire FE_PHN66_n_29;
   wire FE_PHN65_n_35;
   wire FE_PHN64_n_20;
   wire FE_PHN63_n_33;
   wire FE_PHN62_n_31;
   wire FE_PHN61_n_30;
   wire FE_PHN60_n_26;
   wire FE_PHN59_n_25;
   wire FE_PHN58_n_28;
   wire FE_PHN57_pending_q_12;
   wire FE_PHN56_pending_q_8;
   wire FE_PHN55_pending_q_0;
   wire FE_PHN54_pending_q_10;
   wire FE_PHN53_pending_q_14;
   wire FE_PHN52_pending_q_5;
   wire FE_PHN51_pending_q_1;
   wire FE_PHN50_pending_q_3;
   wire FE_PHN49_pending_q_6;
   wire FE_PHN48_pending_q_7;
   wire FE_PHN47_req_meta_q_5;
   wire FE_PHN46_req_meta_q_7;
   wire FE_PHN45_req_meta_q_10;
   wire FE_PHN44_req_meta_q_1;
   wire FE_PHN43_req_meta_q_12;
   wire FE_PHN42_req_meta_q_4;
   wire FE_PHN41_req_meta_q_14;
   wire FE_PHN40_req_meta_q_11;
   wire FE_PHN39_req_meta_q_2;
   wire FE_PHN38_req_meta_q_6;
   wire FE_PHN37_req_meta_q_3;
   wire FE_PHN36_req_meta_q_8;
   wire FE_PHN35_req_meta_q_0;
   wire FE_PHN34_req_meta_q_13;
   wire FE_PHN33_req_meta_q_9;
   wire FE_PHN32_out_valid_q;
   wire FE_PHN31_n_34;
   wire FE_PHN30_n_27;
   wire FE_PHN29_n_21;
   wire FE_PHN28_n_32;
   wire FE_PHN27_n_22;
   wire FE_PHN26_n_23;
   wire FE_PHN25_out_addr_2;
   wire FE_PHN24_rst_n;
   wire FE_PHN23_out_addr_0;
   wire FE_PHN22_out_addr_3;
   wire FE_PHN21_out_addr_1;
   wire FE_PHN20_req_meta_q_15;
   wire FE_PHN19_req_meta_q_5;
   wire FE_PHN18_reset_release_q_0;
   wire FE_PHN17_req_meta_q_7;
   wire FE_PHN16_req_meta_q_8;
   wire FE_PHN15_req_meta_q_6;
   wire FE_PHN14_req_meta_q_0;
   wire FE_PHN13_req_meta_q_12;
   wire FE_PHN12_req_meta_q_5;
   wire FE_PHN11_req_meta_q_1;
   wire FE_PHN10_req_meta_q_14;
   wire FE_PHN9_req_meta_q_3;
   wire FE_PHN8_req_meta_q_2;
   wire FE_PHN7_req_meta_q_15;
   wire FE_PHN6_req_meta_q_9;
   wire FE_PHN5_req_meta_q_13;
   wire FE_PHN4_req_meta_q_10;
   wire FE_PHN3_req_meta_q_4;
   wire FE_PHN2_req_meta_q_11;
   wire FE_PHN1_rst_n;
   wire CTS_1;
   wire FE_OFN0_reset_release_q_1;
   wire [15:0] pending_q;
   wire [3:0] epoch_gray_q;
   wire [15:0] ack_q;
   wire [15:0] req_sync_q;
   wire [1:0] reset_release_q;
   wire [15:0] req_meta_q;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_38;
   wire n_54;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_197;
   wire n_237;
   wire out_valid_q;

   BUFX3 FE_PHC82_req_meta_q_15 (.A(FE_PHN82_req_meta_q_15),
	.Y(FE_PHN7_req_meta_q_15));
   BUFX3 FE_PHC81_req_meta_q_0 (.A(FE_PHN14_req_meta_q_0),
	.Y(FE_PHN81_req_meta_q_0));
   BUFX3 FE_PHC80_reset_release_q_0 (.A(FE_PHN18_reset_release_q_0),
	.Y(FE_PHN80_reset_release_q_0));
   BUFX3 FE_PHC79_req_meta_q_4 (.A(FE_PHN3_req_meta_q_4),
	.Y(FE_PHN79_req_meta_q_4));
   BUFX3 FE_PHC78_req_meta_q_8 (.A(FE_PHN16_req_meta_q_8),
	.Y(FE_PHN78_req_meta_q_8));
   BUFX3 FE_PHC77_req_meta_q_2 (.A(FE_PHN8_req_meta_q_2),
	.Y(FE_PHN77_req_meta_q_2));
   BUFX3 FE_PHC76_req_meta_q_1 (.A(FE_PHN11_req_meta_q_1),
	.Y(FE_PHN76_req_meta_q_1));
   BUFX3 FE_PHC75_req_meta_q_11 (.A(FE_PHN2_req_meta_q_11),
	.Y(FE_PHN75_req_meta_q_11));
   BUFX3 FE_PHC74_req_meta_q_6 (.A(FE_PHN15_req_meta_q_6),
	.Y(FE_PHN74_req_meta_q_6));
   BUFX3 FE_PHC73_req_meta_q_12 (.A(FE_PHN13_req_meta_q_12),
	.Y(FE_PHN73_req_meta_q_12));
   BUFX3 FE_PHC72_req_meta_q_9 (.A(FE_PHN6_req_meta_q_9),
	.Y(FE_PHN72_req_meta_q_9));
   BUFX3 FE_PHC71_req_meta_q_3 (.A(FE_PHN9_req_meta_q_3),
	.Y(FE_PHN71_req_meta_q_3));
   BUFX3 FE_PHC70_req_meta_q_14 (.A(FE_PHN10_req_meta_q_14),
	.Y(FE_PHN70_req_meta_q_14));
   BUFX3 FE_PHC69_req_meta_q_13 (.A(FE_PHN5_req_meta_q_13),
	.Y(FE_PHN69_req_meta_q_13));
   CLKBUFX1 FE_PHC68_reset_release_q_0 (.A(FE_PHN80_reset_release_q_0),
	.Y(FE_PHN68_reset_release_q_0));
   BUFX3 FE_PHC67_n_24 (.A(n_24),
	.Y(FE_PHN67_n_24));
   BUFX3 FE_PHC66_n_29 (.A(n_29),
	.Y(FE_PHN66_n_29));
   BUFX3 FE_PHC65_n_35 (.A(n_35),
	.Y(FE_PHN65_n_35));
   BUFX3 FE_PHC64_n_20 (.A(n_20),
	.Y(FE_PHN64_n_20));
   BUFX3 FE_PHC63_n_33 (.A(n_33),
	.Y(FE_PHN63_n_33));
   BUFX3 FE_PHC62_n_31 (.A(FE_PHN62_n_31),
	.Y(n_31));
   BUFX3 FE_PHC61_n_30 (.A(n_30),
	.Y(FE_PHN61_n_30));
   BUFX3 FE_PHC60_n_26 (.A(n_26),
	.Y(FE_PHN60_n_26));
   BUFX3 FE_PHC59_n_25 (.A(n_25),
	.Y(FE_PHN59_n_25));
   BUFX3 FE_PHC58_n_28 (.A(n_28),
	.Y(FE_PHN58_n_28));
   BUFX3 FE_PHC57_pending_q_12 (.A(pending_q[12]),
	.Y(FE_PHN57_pending_q_12));
   BUFX3 FE_PHC56_pending_q_8 (.A(pending_q[8]),
	.Y(FE_PHN56_pending_q_8));
   BUFX3 FE_PHC55_pending_q_0 (.A(pending_q[0]),
	.Y(FE_PHN55_pending_q_0));
   BUFX3 FE_PHC54_pending_q_10 (.A(pending_q[10]),
	.Y(FE_PHN54_pending_q_10));
   BUFX3 FE_PHC53_pending_q_14 (.A(pending_q[14]),
	.Y(FE_PHN53_pending_q_14));
   BUFX3 FE_PHC52_pending_q_5 (.A(pending_q[5]),
	.Y(FE_PHN52_pending_q_5));
   BUFX3 FE_PHC51_pending_q_1 (.A(pending_q[1]),
	.Y(FE_PHN51_pending_q_1));
   BUFX3 FE_PHC50_pending_q_3 (.A(pending_q[3]),
	.Y(FE_PHN50_pending_q_3));
   BUFX3 FE_PHC49_pending_q_6 (.A(FE_PHN49_pending_q_6),
	.Y(pending_q[6]));
   BUFX3 FE_PHC48_pending_q_7 (.A(pending_q[7]),
	.Y(FE_PHN48_pending_q_7));
   BUFX3 FE_PHC47_req_meta_q_5 (.A(req_meta_q[5]),
	.Y(FE_PHN47_req_meta_q_5));
   BUFX8 FE_PHC46_req_meta_q_7 (.A(req_meta_q[7]),
	.Y(FE_PHN46_req_meta_q_7));
   CLKBUFX1 FE_PHC45_req_meta_q_10 (.A(FE_PHN4_req_meta_q_10),
	.Y(FE_PHN45_req_meta_q_10));
   CLKBUFX1 FE_PHC44_req_meta_q_1 (.A(FE_PHN76_req_meta_q_1),
	.Y(FE_PHN44_req_meta_q_1));
   CLKBUFX1 FE_PHC43_req_meta_q_12 (.A(FE_PHN73_req_meta_q_12),
	.Y(FE_PHN43_req_meta_q_12));
   CLKBUFX1 FE_PHC42_req_meta_q_4 (.A(FE_PHN79_req_meta_q_4),
	.Y(FE_PHN42_req_meta_q_4));
   CLKBUFX1 FE_PHC41_req_meta_q_14 (.A(FE_PHN70_req_meta_q_14),
	.Y(FE_PHN41_req_meta_q_14));
   CLKBUFX1 FE_PHC40_req_meta_q_11 (.A(FE_PHN75_req_meta_q_11),
	.Y(FE_PHN40_req_meta_q_11));
   CLKBUFX1 FE_PHC39_req_meta_q_2 (.A(FE_PHN77_req_meta_q_2),
	.Y(FE_PHN39_req_meta_q_2));
   CLKBUFX1 FE_PHC38_req_meta_q_6 (.A(FE_PHN74_req_meta_q_6),
	.Y(FE_PHN38_req_meta_q_6));
   CLKBUFX1 FE_PHC37_req_meta_q_3 (.A(FE_PHN71_req_meta_q_3),
	.Y(FE_PHN37_req_meta_q_3));
   BUFX3 FE_PHC36_req_meta_q_8 (.A(FE_PHN78_req_meta_q_8),
	.Y(FE_PHN36_req_meta_q_8));
   CLKBUFX1 FE_PHC35_req_meta_q_0 (.A(FE_PHN81_req_meta_q_0),
	.Y(FE_PHN35_req_meta_q_0));
   CLKBUFX1 FE_PHC34_req_meta_q_13 (.A(FE_PHN69_req_meta_q_13),
	.Y(FE_PHN34_req_meta_q_13));
   CLKBUFX1 FE_PHC33_req_meta_q_9 (.A(FE_PHN72_req_meta_q_9),
	.Y(FE_PHN33_req_meta_q_9));
   BUFX3 FE_PHC32_out_valid_q (.A(out_valid_q),
	.Y(FE_PHN32_out_valid_q));
   BUFX3 FE_PHC31_n_34 (.A(n_34),
	.Y(FE_PHN31_n_34));
   BUFX3 FE_PHC30_n_27 (.A(n_27),
	.Y(FE_PHN30_n_27));
   BUFX3 FE_PHC29_n_21 (.A(n_21),
	.Y(FE_PHN29_n_21));
   BUFX3 FE_PHC28_n_32 (.A(n_32),
	.Y(FE_PHN28_n_32));
   BUFX3 FE_PHC27_n_22 (.A(n_22),
	.Y(FE_PHN27_n_22));
   BUFX3 FE_PHC26_n_23 (.A(n_23),
	.Y(FE_PHN26_n_23));
   BUFX3 FE_PHC25_out_addr_2 (.A(out_addr[2]),
	.Y(FE_PHN25_out_addr_2));
   BUFX3 FE_PHC24_rst_n (.A(rst_n),
	.Y(FE_PHN24_rst_n));
   BUFX3 FE_PHC23_out_addr_0 (.A(out_addr[0]),
	.Y(FE_PHN23_out_addr_0));
   BUFX3 FE_PHC22_out_addr_3 (.A(out_addr[3]),
	.Y(FE_PHN22_out_addr_3));
   BUFX3 FE_PHC21_out_addr_1 (.A(out_addr[1]),
	.Y(FE_PHN21_out_addr_1));
   CLKBUFX1 FE_PHC20_req_meta_q_15 (.A(FE_PHN7_req_meta_q_15),
	.Y(FE_PHN20_req_meta_q_15));
   BUFX3 FE_PHC19_req_meta_q_5 (.A(FE_PHN47_req_meta_q_5),
	.Y(FE_PHN19_req_meta_q_5));
   BUFX3 FE_PHC18_reset_release_q_0 (.A(reset_release_q[0]),
	.Y(FE_PHN18_reset_release_q_0));
   CLKBUFX1 FE_PHC17_req_meta_q_7 (.A(FE_PHN46_req_meta_q_7),
	.Y(FE_PHN17_req_meta_q_7));
   BUFX8 FE_PHC16_req_meta_q_8 (.A(req_meta_q[8]),
	.Y(FE_PHN16_req_meta_q_8));
   BUFX4 FE_PHC15_req_meta_q_6 (.A(req_meta_q[6]),
	.Y(FE_PHN15_req_meta_q_6));
   BUFX8 FE_PHC14_req_meta_q_0 (.A(req_meta_q[0]),
	.Y(FE_PHN14_req_meta_q_0));
   CLKBUFX3 FE_PHC13_req_meta_q_12 (.A(req_meta_q[12]),
	.Y(FE_PHN13_req_meta_q_12));
   CLKBUFX1 FE_PHC12_req_meta_q_5 (.A(FE_PHN19_req_meta_q_5),
	.Y(FE_PHN12_req_meta_q_5));
   CLKBUFX3 FE_PHC11_req_meta_q_1 (.A(req_meta_q[1]),
	.Y(FE_PHN11_req_meta_q_1));
   CLKBUFX4 FE_PHC10_req_meta_q_14 (.A(req_meta_q[14]),
	.Y(FE_PHN10_req_meta_q_14));
   BUFX4 FE_PHC9_req_meta_q_3 (.A(req_meta_q[3]),
	.Y(FE_PHN9_req_meta_q_3));
   CLKBUFX8 FE_PHC8_req_meta_q_2 (.A(req_meta_q[2]),
	.Y(FE_PHN8_req_meta_q_2));
   BUFX12 FE_PHC7_req_meta_q_15 (.A(req_meta_q[15]),
	.Y(FE_PHN82_req_meta_q_15));
   BUFX8 FE_PHC6_req_meta_q_9 (.A(req_meta_q[9]),
	.Y(FE_PHN6_req_meta_q_9));
   CLKBUFX8 FE_PHC5_req_meta_q_13 (.A(req_meta_q[13]),
	.Y(FE_PHN5_req_meta_q_13));
   BUFX3 FE_PHC4_req_meta_q_10 (.A(req_meta_q[10]),
	.Y(FE_PHN4_req_meta_q_10));
   BUFX3 FE_PHC3_req_meta_q_4 (.A(req_meta_q[4]),
	.Y(FE_PHN3_req_meta_q_4));
   BUFX3 FE_PHC2_req_meta_q_11 (.A(req_meta_q[11]),
	.Y(FE_PHN2_req_meta_q_11));
   DLY2X1 FE_PHC1_rst_n (.A(FE_PHN24_rst_n),
	.Y(FE_PHN1_rst_n));
   CLKBUFX20 CTS_ccl_a_buf_00001 (.A(clk),
	.Y(CTS_1));
   CLKBUFX2 FE_OFC0_reset_release_q_1 (.A(reset_release_q[1]),
	.Y(FE_OFN0_reset_release_q_1));
   DFFHQX1 \pending_q_reg[0]  (.D(n_165),
	.CK(CTS_1),
	.Q(pending_q[0]));
   DFFHQX1 \pending_q_reg[2]  (.D(n_170),
	.CK(CTS_1),
	.Q(pending_q[2]));
   DFFHQX1 \pending_q_reg[4]  (.D(n_167),
	.CK(CTS_1),
	.Q(pending_q[4]));
   DFFHQX1 \pending_q_reg[6]  (.D(n_174),
	.CK(CTS_1),
	.Q(FE_PHN49_pending_q_6));
   DFFHQX1 \pending_q_reg[8]  (.D(n_176),
	.CK(CTS_1),
	.Q(pending_q[8]));
   DFFHQX1 \pending_q_reg[10]  (.D(n_171),
	.CK(CTS_1),
	.Q(pending_q[10]));
   DFFHQX1 \pending_q_reg[12]  (.D(n_177),
	.CK(CTS_1),
	.Q(pending_q[12]));
   DFFHQX1 \pending_q_reg[14]  (.D(n_173),
	.CK(CTS_1),
	.Q(pending_q[14]));
   DFFHQX1 \pending_q_reg[5]  (.D(n_159),
	.CK(CTS_1),
	.Q(pending_q[5]));
   DFFHQX1 \pending_q_reg[3]  (.D(n_157),
	.CK(CTS_1),
	.Q(pending_q[3]));
   DFFHQX1 \pending_q_reg[1]  (.D(n_156),
	.CK(CTS_1),
	.Q(pending_q[1]));
   DFFHQX1 \pending_q_reg[9]  (.D(n_155),
	.CK(CTS_1),
	.Q(pending_q[9]));
   DFFHQX1 \pending_q_reg[13]  (.D(n_162),
	.CK(CTS_1),
	.Q(pending_q[13]));
   DFFHQX1 \pending_q_reg[7]  (.D(n_160),
	.CK(CTS_1),
	.Q(pending_q[7]));
   DFFHQX1 \pending_q_reg[11]  (.D(n_154),
	.CK(CTS_1),
	.Q(pending_q[11]));
   DFFHQX1 \pending_q_reg[15]  (.D(n_163),
	.CK(CTS_1),
	.Q(pending_q[15]));
   AOI21XL g5746__2398 (.A0(n_175),
	.A1(n_166),
	.B0(n_124),
	.Y(n_177));
   AOI21XL g5747__5107 (.A0(n_175),
	.A1(n_164),
	.B0(n_110),
	.Y(n_176));
   AOI21XL g5757__6260 (.A0(n_169),
	.A1(n_172),
	.B0(n_137),
	.Y(n_174));
   AOI21XL g5749__4319 (.A0(n_175),
	.A1(n_172),
	.B0(n_130),
	.Y(n_173));
   AOI21XL g5745__8428 (.A0(n_175),
	.A1(n_168),
	.B0(n_129),
	.Y(n_171));
   AOI21XL g5755__5526 (.A0(n_169),
	.A1(n_168),
	.B0(n_135),
	.Y(n_170));
   AOI21XL g5754__6783 (.A0(n_169),
	.A1(n_166),
	.B0(n_120),
	.Y(n_167));
   AOI21XL g5756__3680 (.A0(n_169),
	.A1(n_164),
	.B0(n_114),
	.Y(n_165));
   AOI21XL g5750__1617 (.A0(n_161),
	.A1(n_172),
	.B0(n_133),
	.Y(n_163));
   AOI21XL g5748__2802 (.A0(n_161),
	.A1(n_166),
	.B0(n_122),
	.Y(n_162));
   AOI21XL g5758__1705 (.A0(n_158),
	.A1(n_172),
	.B0(n_141),
	.Y(n_160));
   AOI21XL g5751__5122 (.A0(n_158),
	.A1(n_166),
	.B0(n_127),
	.Y(n_159));
   AOI21XL g5753__8246 (.A0(n_158),
	.A1(n_168),
	.B0(n_140),
	.Y(n_157));
   AOI21XL g5752__7098 (.A0(n_158),
	.A1(n_164),
	.B0(n_116),
	.Y(n_156));
   AOI21XL g5744__6131 (.A0(n_161),
	.A1(n_164),
	.B0(n_112),
	.Y(n_155));
   AOI21XL g5743__1881 (.A0(n_161),
	.A1(n_168),
	.B0(n_132),
	.Y(n_154));
   DFFHQX1 \out_addr_q_reg[0]  (.D(n_150),
	.CK(CTS_1),
	.Q(out_addr[0]));
   OAI21XL g5760__5115 (.A0(n_153),
	.A1(n_151),
	.B0(FE_OFN0_reset_release_q_1),
	.Y(n_175));
   OAI21XL g5764__7482 (.A0(n_153),
	.A1(n_147),
	.B0(FE_OFN0_reset_release_q_1),
	.Y(n_169));
   OAI21XL g5761__4733 (.A0(n_149),
	.A1(n_151),
	.B0(FE_OFN0_reset_release_q_1),
	.Y(n_161));
   OAI2BB2X1 g5762__6161 (.A0N(FE_PHN23_out_addr_0),
	.A1N(n_148),
	.B0(n_149),
	.B1(n_148),
	.Y(n_150));
   OAI21XL g5763__9315 (.A0(n_149),
	.A1(n_147),
	.B0(FE_OFN0_reset_release_q_1),
	.Y(n_158));
   INVX1 g5765 (.A(n_149),
	.Y(n_153));
   MXI2X1 g5766__9945 (.S0(n_146),
	.B(epoch_gray_q[0]),
	.A(n_144),
	.Y(n_149));
   OAI22X1 g5767__2883 (.A0(n_143),
	.A1(n_151),
	.B0(n_145),
	.B1(n_147),
	.Y(n_146));
   AOI22X1 g5768__2346 (.A0(n_139),
	.A1(n_144),
	.B0(n_142),
	.B1(epoch_gray_q[0]),
	.Y(n_145));
   AOI22X1 g5769__1666 (.A0(n_131),
	.A1(n_144),
	.B0(n_134),
	.B1(epoch_gray_q[0]),
	.Y(n_143));
   OAI221XL g5770__7410 (.A0(n_138),
	.A1(n_141),
	.B0(n_136),
	.B1(n_140),
	.C0(n_128),
	.Y(n_142));
   OAI221XL g5771__6417 (.A0(n_138),
	.A1(n_137),
	.B0(n_136),
	.B1(n_135),
	.C0(n_121),
	.Y(n_139));
   OAI221XL g5772__5477 (.A0(n_138),
	.A1(n_133),
	.B0(n_136),
	.B1(n_132),
	.C0(n_123),
	.Y(n_134));
   OAI221XL g5773__2398 (.A0(n_138),
	.A1(n_130),
	.B0(n_136),
	.B1(n_129),
	.C0(n_126),
	.Y(n_131));
   AOI2BB1XL g5779__5107 (.A0N(n_125),
	.A1N(n_127),
	.B0(n_118),
	.Y(n_128));
   AOI2BB1XL g5780__6260 (.A0N(n_125),
	.A1N(n_124),
	.B0(n_111),
	.Y(n_126));
   AOI2BB1XL g5781__4319 (.A0N(n_125),
	.A1N(n_122),
	.B0(n_113),
	.Y(n_123));
   AOI2BB1XL g5778__8428 (.A0N(n_125),
	.A1N(n_120),
	.B0(n_115),
	.Y(n_121));
   AOI21X1 g5782__5526 (.A0(n_138),
	.A1(FE_OFN0_reset_release_q_1),
	.B0(n_237),
	.Y(n_172));
   AOI21X1 g5775__6783 (.A0(n_117),
	.A1(FE_OFN0_reset_release_q_1),
	.B0(n_237),
	.Y(n_164));
   DFFHQX1 \out_addr_q_reg[1]  (.D(n_109),
	.CK(CTS_1),
	.Q(out_addr[1]));
   AOI21X1 g5777__3680 (.A0(n_125),
	.A1(FE_OFN0_reset_release_q_1),
	.B0(n_237),
	.Y(n_166));
   AOI21X1 g5776__1617 (.A0(n_136),
	.A1(FE_OFN0_reset_release_q_1),
	.B0(n_237),
	.Y(n_168));
   NOR2X1 g5783__2802 (.A(n_117),
	.B(n_116),
	.Y(n_118));
   NOR2X1 g5784__1705 (.A(n_117),
	.B(n_114),
	.Y(n_115));
   NOR2XL g5785__5122 (.A(n_117),
	.B(n_112),
	.Y(n_113));
   NOR2XL g5786__8246 (.A(n_117),
	.B(n_110),
	.Y(n_111));
   OAI2BB2X1 g5787__7098 (.A0N(FE_PHN21_out_addr_1),
	.A1N(n_148),
	.B0(n_108),
	.B1(n_148),
	.Y(n_109));
   NAND2X1 g5788__6131 (.A(n_108),
	.B(n_106),
	.Y(n_117));
   NAND2X1 g5789__1881 (.A(n_108),
	.B(n_107),
	.Y(n_125));
   OR2X2 g5790__5115 (.A(n_108),
	.B(n_107),
	.Y(n_136));
   OR2X2 g5791__7482 (.A(n_108),
	.B(n_106),
	.Y(n_138));
   OAI2BB2X1 g5792__4733 (.A0N(epoch_gray_q[1]),
	.A1N(n_105),
	.B0(n_105),
	.B1(epoch_gray_q[1]),
	.Y(n_108));
   DFFHQX1 \out_addr_q_reg[2]  (.D(n_104),
	.CK(CTS_1),
	.Q(out_addr[2]));
   AOI22X1 g5794__6161 (.A0(n_107),
	.A1(n_91),
	.B0(n_106),
	.B1(n_92),
	.Y(n_105));
   OAI2BB2X1 g5795__9315 (.A0N(FE_PHN25_out_addr_2),
	.A1N(n_148),
	.B0(n_106),
	.B1(n_148),
	.Y(n_104));
   INVX1 g5798 (.A(n_106),
	.Y(n_107));
   DFFHQX1 \epoch_gray_q_reg[3]  (.D(n_101),
	.CK(CTS_1),
	.Q(epoch_gray_q[3]));
   OAI2BB2X1 g5799__9945 (.A0N(epoch_gray_q[2]),
	.A1N(n_103),
	.B0(n_103),
	.B1(epoch_gray_q[2]),
	.Y(n_106));
   INVX1 g5802 (.A(n_98),
	.Y(n_102));
   INVX1 g5806 (.A(n_97),
	.Y(n_101));
   INVX1 g5807 (.A(n_95),
	.Y(n_100));
   INVX1 g5808 (.A(n_94),
	.Y(n_99));
   AOI22X1 g5803__2883 (.A0(n_96),
	.A1(n_62),
	.B0(n_237),
	.B1(epoch_gray_q[0]),
	.Y(n_98));
   AOI22X1 g5809__2346 (.A0(n_96),
	.A1(n_72),
	.B0(n_237),
	.B1(epoch_gray_q[3]),
	.Y(n_97));
   AOI22X1 g5810__1666 (.A0(n_96),
	.A1(n_79),
	.B0(n_237),
	.B1(epoch_gray_q[2]),
	.Y(n_95));
   AOI22X1 g5811__7410 (.A0(n_96),
	.A1(n_74),
	.B0(n_237),
	.B1(epoch_gray_q[1]),
	.Y(n_94));
   DFFHQX1 \out_addr_q_reg[3]  (.D(n_90),
	.CK(CTS_1),
	.Q(out_addr[3]));
   OAI21XL g5812__6417 (.A0(n_38),
	.A1(out_ready),
	.B0(n_89),
	.Y(n_93));
   OAI22X1 g5813__5477 (.A0(n_151),
	.A1(n_68),
	.B0(n_147),
	.B1(n_70),
	.Y(n_92));
   OAI22X1 g5814__2398 (.A0(n_151),
	.A1(n_75),
	.B0(n_147),
	.B1(n_67),
	.Y(n_91));
   AOI22X1 g5816__5107 (.A0(n_147),
	.A1(n_85),
	.B0(n_151),
	.B1(n_86),
	.Y(n_103));
   OAI2BB2XL g5815__6260 (.A0N(FE_PHN22_out_addr_3),
	.A1N(n_148),
	.B0(n_151),
	.B1(n_148),
	.Y(n_90));
   INVXL g5818 (.A(n_96),
	.Y(n_89));
   NOR2X1 g5819__8428 (.A(n_148),
	.B(n_54),
	.Y(n_96));
   INVX1 g5820 (.A(n_151),
	.Y(n_147));
   OAI21XL g5821__5526 (.A0(n_83),
	.A1(epoch_gray_q[3]),
	.B0(n_87),
	.Y(n_151));
   OAI22X1 g5824__6783 (.A0(n_87),
	.A1(n_82),
	.B0(n_5),
	.B1(out_ready),
	.Y(n_148));
   OAI22X1 g5825__3680 (.A0(n_76),
	.A1(epoch_gray_q[2]),
	.B0(n_77),
	.B1(n_84),
	.Y(n_86));
   OAI22X1 g5826__1617 (.A0(n_80),
	.A1(epoch_gray_q[2]),
	.B0(n_81),
	.B1(n_84),
	.Y(n_85));
   INVX1 g5829 (.A(n_82),
	.Y(n_83));
   NAND2X1 g5832__2802 (.A(n_81),
	.B(n_80),
	.Y(n_87));
   OAI2BB2X1 g5827__1705 (.A0N(n_84),
	.A1N(n_78),
	.B0(n_78),
	.B1(n_84),
	.Y(n_79));
   NAND2X1 g5831__5122 (.A(n_77),
	.B(n_76),
	.Y(n_82));
   AOI22X1 g5835__8246 (.A0(n_65),
	.A1(n_69),
	.B0(n_66),
	.B1(epoch_gray_q[1]),
	.Y(n_75));
   OAI2BB2X1 g5823__7098 (.A0N(epoch_gray_q[1]),
	.A1N(n_73),
	.B0(n_73),
	.B1(epoch_gray_q[1]),
	.Y(n_74));
   OAI2BB2X1 g5828__6131 (.A0N(epoch_gray_q[3]),
	.A1N(n_71),
	.B0(n_71),
	.B1(epoch_gray_q[3]),
	.Y(n_72));
   AOI22X1 g5830__1881 (.A0(n_58),
	.A1(n_69),
	.B0(n_59),
	.B1(epoch_gray_q[1]),
	.Y(n_70));
   AOI22X1 g5833__5115 (.A0(n_63),
	.A1(n_69),
	.B0(n_64),
	.B1(epoch_gray_q[1]),
	.Y(n_68));
   AOI22X1 g5834__7482 (.A0(n_60),
	.A1(n_69),
	.B0(n_61),
	.B1(epoch_gray_q[1]),
	.Y(n_67));
   NOR2X1 g5836__4733 (.A(n_66),
	.B(n_65),
	.Y(n_81));
   NOR2X1 g5837__6161 (.A(n_64),
	.B(n_63),
	.Y(n_80));
   OAI21XL g5839__9315 (.A0(n_57),
	.A1(epoch_gray_q[0]),
	.B0(n_73),
	.Y(n_62));
   NOR2X1 g5838__9945 (.A(n_61),
	.B(n_60),
	.Y(n_77));
   NOR2X1 g5841__2883 (.A(n_59),
	.B(n_58),
	.Y(n_76));
   NOR3X1 g5842__2346 (.A(n_56),
	.B(n_69),
	.C(epoch_gray_q[0]),
	.Y(n_78));
   NAND2X1 g5862__1666 (.A(n_116),
	.B(n_114),
	.Y(n_58));
   NAND2X1 g5855__7410 (.A(n_112),
	.B(n_110),
	.Y(n_63));
   NAND2X1 g5856__6417 (.A(n_122),
	.B(n_124),
	.Y(n_65));
   NAND2X1 g5857__5477 (.A(n_132),
	.B(n_129),
	.Y(n_64));
   NAND2X1 g5858__2398 (.A(n_127),
	.B(n_120),
	.Y(n_60));
   NAND2X1 g5859__5107 (.A(n_133),
	.B(n_130),
	.Y(n_66));
   NAND2X1 g5860__6260 (.A(n_141),
	.B(n_137),
	.Y(n_61));
   NAND2X1 g5861__4319 (.A(n_140),
	.B(n_135),
	.Y(n_59));
   NAND3X1 g5840__8428 (.A(n_57),
	.B(n_69),
	.C(n_144),
	.Y(n_71));
   DFFTRX1 \ack_q_reg[3]  (.D(FE_PHN58_n_28),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[3]),
	.QN(n_6));
   DFFTRX1 \ack_q_reg[2]  (.D(FE_PHN28_n_32),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[2]),
	.QN(n_13));
   DFFTRX1 \ack_q_reg[9]  (.D(FE_PHN27_n_22),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[9]),
	.QN(n_17));
   DFFTRX1 \ack_q_reg[13]  (.D(FE_PHN31_n_34),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[13]),
	.QN(n_11));
   DFFTRX1 \ack_q_reg[14]  (.D(FE_PHN61_n_30),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[14]),
	.QN(n_8));
   NAND2X1 g5867__5526 (.A(n_57),
	.B(epoch_gray_q[0]),
	.Y(n_73));
   DFFTRX1 \ack_q_reg[0]  (.D(FE_PHN65_n_35),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[0]),
	.QN(n_1));
   DFFTRX1 \ack_q_reg[1]  (.D(FE_PHN63_n_33),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[1]),
	.QN(n_7));
   DFFTRX1 \ack_q_reg[10]  (.D(FE_PHN64_n_20),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[10]),
	.QN(n_16));
   DFFTRX1 \ack_q_reg[4]  (.D(FE_PHN26_n_23),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[4]),
	.QN(n_15));
   DFFTRX1 \ack_q_reg[15]  (.D(FE_PHN29_n_21),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[15]),
	.QN(n_14));
   DFFTRX1 \ack_q_reg[8]  (.D(FE_PHN67_n_24),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[8]),
	.QN(n_12));
   DFFTRX1 \ack_q_reg[12]  (.D(FE_PHN66_n_29),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[12]),
	.QN(n_10));
   DFFTRX1 \ack_q_reg[7]  (.D(FE_PHN60_n_26),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[7]),
	.QN(n_0));
   DFFTRX1 \ack_q_reg[6]  (.D(FE_PHN59_n_25),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[6]),
	.QN(n_4));
   DFFTRX1 \ack_q_reg[11]  (.D(FE_PHN30_n_27),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[11]),
	.QN(n_3));
   DFFTRX1 \ack_q_reg[5]  (.D(n_31),
	.CK(CTS_1),
	.RN(FE_OFN0_reset_release_q_1),
	.Q(ack_q[5]),
	.QN(n_2));
   INVX1 g5876 (.A(n_57),
	.Y(n_56));
   NOR2BXL g5901__6783 (.AN(ack_q[9]),
	.B(n_54),
	.Y(src_ack_async[9]));
   NOR2BXL g5891__3680 (.AN(ack_q[7]),
	.B(n_54),
	.Y(src_ack_async[7]));
   NOR2BXL g5903__1617 (.AN(ack_q[1]),
	.B(n_54),
	.Y(src_ack_async[1]));
   NOR2BXL g5889__2802 (.AN(ack_q[8]),
	.B(n_54),
	.Y(src_ack_async[8]));
   NOR2BXL g5890__1705 (.AN(ack_q[14]),
	.B(n_54),
	.Y(src_ack_async[14]));
   NOR2BXL g5892__5122 (.AN(ack_q[11]),
	.B(n_54),
	.Y(src_ack_async[11]));
   NOR2BXL g5887__8246 (.AN(ack_q[2]),
	.B(n_54),
	.Y(src_ack_async[2]));
   AOI2BB1X1 g5869__7098 (.A0N(ack_q[15]),
	.A1N(req_sync_q[15]),
	.B0(pending_q[15]),
	.Y(n_133));
   AOI2BB1X1 g5870__6131 (.A0N(ack_q[14]),
	.A1N(req_sync_q[14]),
	.B0(FE_PHN53_pending_q_14),
	.Y(n_130));
   AOI2BB1X1 g5871__1881 (.A0N(ack_q[13]),
	.A1N(req_sync_q[13]),
	.B0(pending_q[13]),
	.Y(n_122));
   AOI2BB1X1 g5872__5115 (.A0N(ack_q[12]),
	.A1N(req_sync_q[12]),
	.B0(FE_PHN57_pending_q_12),
	.Y(n_124));
   AOI2BB1X1 g5873__7482 (.A0N(ack_q[10]),
	.A1N(req_sync_q[10]),
	.B0(FE_PHN54_pending_q_10),
	.Y(n_129));
   AOI2BB1X1 g5874__4733 (.A0N(ack_q[9]),
	.A1N(req_sync_q[9]),
	.B0(pending_q[9]),
	.Y(n_112));
   AOI2BB1X1 g5875__6161 (.A0N(ack_q[8]),
	.A1N(req_sync_q[8]),
	.B0(FE_PHN56_pending_q_8),
	.Y(n_110));
   AOI2BB1X1 g5877__9315 (.A0N(ack_q[3]),
	.A1N(req_sync_q[3]),
	.B0(FE_PHN50_pending_q_3),
	.Y(n_140));
   AOI2BB1X1 g5878__9945 (.A0N(ack_q[5]),
	.A1N(req_sync_q[5]),
	.B0(FE_PHN52_pending_q_5),
	.Y(n_127));
   AOI2BB1X1 g5868__2883 (.A0N(ack_q[11]),
	.A1N(req_sync_q[11]),
	.B0(pending_q[11]),
	.Y(n_132));
   NOR2BXL g5888__2346 (.AN(ack_q[0]),
	.B(n_54),
	.Y(src_ack_async[0]));
   NOR2BXL g5895__1666 (.AN(ack_q[5]),
	.B(n_54),
	.Y(src_ack_async[5]));
   NOR2BXL g5899__7410 (.AN(ack_q[3]),
	.B(n_54),
	.Y(src_ack_async[3]));
   NOR2BXL g5898__6417 (.AN(ack_q[15]),
	.B(n_54),
	.Y(src_ack_async[15]));
   NOR2BXL g5894__5477 (.AN(ack_q[6]),
	.B(n_54),
	.Y(src_ack_async[6]));
   NOR2BXL g5897__2398 (.AN(ack_q[4]),
	.B(n_54),
	.Y(src_ack_async[4]));
   NOR2BXL g5900__5107 (.AN(ack_q[13]),
	.B(n_54),
	.Y(src_ack_async[13]));
   NOR2BXL g5896__6260 (.AN(ack_q[10]),
	.B(n_54),
	.Y(src_ack_async[10]));
   INVXL g5886 (.A(n_38),
	.Y(out_valid));
   NOR2BXL g5893__4319 (.AN(ack_q[12]),
	.B(n_54),
	.Y(src_ack_async[12]));
   AOI2BB1X1 g5880__8428 (.A0N(ack_q[2]),
	.A1N(req_sync_q[2]),
	.B0(pending_q[2]),
	.Y(n_135));
   AOI2BB1XL g5879__5526 (.A0N(ack_q[4]),
	.A1N(req_sync_q[4]),
	.B0(pending_q[4]),
	.Y(n_120));
   AOI2BB1X1 g5884__6783 (.A0N(ack_q[6]),
	.A1N(req_sync_q[6]),
	.B0(pending_q[6]),
	.Y(n_137));
   AOI2BB1X1 g5883__3680 (.A0N(ack_q[0]),
	.A1N(req_sync_q[0]),
	.B0(FE_PHN55_pending_q_0),
	.Y(n_114));
   AOI2BB1X1 g5882__1617 (.A0N(ack_q[1]),
	.A1N(req_sync_q[1]),
	.B0(FE_PHN51_pending_q_1),
	.Y(n_116));
   AOI2BB1X1 g5881__2802 (.A0N(ack_q[7]),
	.A1N(req_sync_q[7]),
	.B0(FE_PHN48_pending_q_7),
	.Y(n_141));
   XOR2X1 g5885__1705 (.A(n_197),
	.B(n_19),
	.Y(n_57));
   AOI21XL g5911__5122 (.A0(n_1),
	.A1(FE_PHN55_pending_q_0),
	.B0(req_sync_q[0]),
	.Y(n_35));
   AOI21XL g5904__8246 (.A0(n_11),
	.A1(pending_q[13]),
	.B0(req_sync_q[13]),
	.Y(n_34));
   AOI21XL g5905__7098 (.A0(n_7),
	.A1(FE_PHN51_pending_q_1),
	.B0(req_sync_q[1]),
	.Y(n_33));
   AOI21XL g5906__6131 (.A0(n_13),
	.A1(pending_q[2]),
	.B0(req_sync_q[2]),
	.Y(n_32));
   AOI21XL g5907__1881 (.A0(n_2),
	.A1(FE_PHN52_pending_q_5),
	.B0(req_sync_q[5]),
	.Y(FE_PHN62_n_31));
   AOI21XL g5908__5115 (.A0(n_8),
	.A1(FE_PHN53_pending_q_14),
	.B0(req_sync_q[14]),
	.Y(n_30));
   AOI21XL g5909__7482 (.A0(n_10),
	.A1(FE_PHN57_pending_q_12),
	.B0(req_sync_q[12]),
	.Y(n_29));
   AOI21XL g5910__4733 (.A0(n_6),
	.A1(FE_PHN50_pending_q_3),
	.B0(req_sync_q[3]),
	.Y(n_28));
   NAND2X1 g5902__6161 (.A(FE_PHN32_out_valid_q),
	.B(FE_OFN0_reset_release_q_1),
	.Y(n_38));
   AOI21XL g5919__9315 (.A0(n_3),
	.A1(pending_q[11]),
	.B0(req_sync_q[11]),
	.Y(n_27));
   AOI21XL g5913__9945 (.A0(n_0),
	.A1(FE_PHN48_pending_q_7),
	.B0(req_sync_q[7]),
	.Y(n_26));
   AOI21XL g5914__2883 (.A0(n_4),
	.A1(pending_q[6]),
	.B0(req_sync_q[6]),
	.Y(n_25));
   AOI21XL g5915__2346 (.A0(n_12),
	.A1(FE_PHN56_pending_q_8),
	.B0(req_sync_q[8]),
	.Y(n_24));
   AOI21XL g5912__1666 (.A0(n_15),
	.A1(pending_q[4]),
	.B0(req_sync_q[4]),
	.Y(n_23));
   AOI21XL g5916__7410 (.A0(n_17),
	.A1(pending_q[9]),
	.B0(req_sync_q[9]),
	.Y(n_22));
   AOI21XL g5917__6417 (.A0(n_14),
	.A1(pending_q[15]),
	.B0(req_sync_q[15]),
	.Y(n_21));
   AOI21XL g5918__5477 (.A0(n_16),
	.A1(FE_PHN54_pending_q_10),
	.B0(req_sync_q[10]),
	.Y(n_20));
   INVX1 g5922 (.A(FE_OFN0_reset_release_q_1),
	.Y(n_54));
   DFFX1 \req_sync_q_reg[12]  (.D(FE_PHN43_req_meta_q_12),
	.CK(CTS_1),
	.Q(UNCONNECTED),
	.QN(req_sync_q[12]));
   DFFX1 \req_sync_q_reg[2]  (.D(FE_PHN39_req_meta_q_2),
	.CK(CTS_1),
	.Q(UNCONNECTED0),
	.QN(req_sync_q[2]));
   DFFX1 \req_sync_q_reg[0]  (.D(FE_PHN35_req_meta_q_0),
	.CK(CTS_1),
	.Q(UNCONNECTED1),
	.QN(req_sync_q[0]));
   DFFX1 \req_sync_q_reg[7]  (.D(FE_PHN17_req_meta_q_7),
	.CK(CTS_1),
	.Q(UNCONNECTED2),
	.QN(req_sync_q[7]));
   DFFX1 \req_sync_q_reg[9]  (.D(FE_PHN33_req_meta_q_9),
	.CK(CTS_1),
	.Q(UNCONNECTED3),
	.QN(req_sync_q[9]));
   DFFX1 \req_sync_q_reg[8]  (.D(FE_PHN36_req_meta_q_8),
	.CK(CTS_1),
	.Q(UNCONNECTED4),
	.QN(req_sync_q[8]));
   DFFX1 \req_sync_q_reg[13]  (.D(FE_PHN34_req_meta_q_13),
	.CK(CTS_1),
	.Q(UNCONNECTED5),
	.QN(req_sync_q[13]));
   DFFX1 \req_sync_q_reg[3]  (.D(FE_PHN37_req_meta_q_3),
	.CK(CTS_1),
	.Q(UNCONNECTED6),
	.QN(req_sync_q[3]));
   DFFX1 \req_sync_q_reg[1]  (.D(FE_PHN44_req_meta_q_1),
	.CK(CTS_1),
	.Q(UNCONNECTED7),
	.QN(req_sync_q[1]));
   AOI22X1 g5941__2398 (.A0(n_84),
	.A1(epoch_gray_q[1]),
	.B0(n_69),
	.B1(epoch_gray_q[2]),
	.Y(n_19));
   DFFX1 \req_sync_q_reg[6]  (.D(FE_PHN38_req_meta_q_6),
	.CK(CTS_1),
	.Q(UNCONNECTED8),
	.QN(req_sync_q[6]));
   DFFX1 \req_sync_q_reg[14]  (.D(FE_PHN41_req_meta_q_14),
	.CK(CTS_1),
	.Q(UNCONNECTED9),
	.QN(req_sync_q[14]));
   DFFX1 \req_sync_q_reg[4]  (.D(FE_PHN42_req_meta_q_4),
	.CK(CTS_1),
	.Q(UNCONNECTED10),
	.QN(req_sync_q[4]));
   DFFX1 \req_sync_q_reg[15]  (.D(FE_PHN20_req_meta_q_15),
	.CK(CTS_1),
	.Q(UNCONNECTED11),
	.QN(req_sync_q[15]));
   DFFX1 \req_sync_q_reg[5]  (.D(FE_PHN12_req_meta_q_5),
	.CK(CTS_1),
	.Q(UNCONNECTED12),
	.QN(req_sync_q[5]));
   DFFRHQX1 \reset_release_q_reg[1]  (.D(FE_PHN68_reset_release_q_0),
	.CK(CTS_1),
	.RN(FE_PHN1_rst_n),
	.Q(reset_release_q[1]));
   DFFX1 \req_sync_q_reg[11]  (.D(FE_PHN40_req_meta_q_11),
	.CK(CTS_1),
	.Q(UNCONNECTED13),
	.QN(req_sync_q[11]));
   DFFX1 \req_sync_q_reg[10]  (.D(FE_PHN45_req_meta_q_10),
	.CK(CTS_1),
	.Q(UNCONNECTED14),
	.QN(req_sync_q[10]));
   DFFHQX1 \req_meta_q_reg[2]  (.D(src_req_async[2]),
	.CK(CTS_1),
	.Q(req_meta_q[2]));
   DFFHQX1 \req_meta_q_reg[13]  (.D(src_req_async[13]),
	.CK(CTS_1),
	.Q(req_meta_q[13]));
   DFFHQX1 \req_meta_q_reg[4]  (.D(src_req_async[4]),
	.CK(CTS_1),
	.Q(req_meta_q[4]));
   DFFHQX1 \req_meta_q_reg[6]  (.D(src_req_async[6]),
	.CK(CTS_1),
	.Q(req_meta_q[6]));
   DFFHQX1 \req_meta_q_reg[12]  (.D(src_req_async[12]),
	.CK(CTS_1),
	.Q(req_meta_q[12]));
   DFFHQX1 \req_meta_q_reg[11]  (.D(src_req_async[11]),
	.CK(CTS_1),
	.Q(req_meta_q[11]));
   DFFHQX1 \req_meta_q_reg[5]  (.D(src_req_async[5]),
	.CK(CTS_1),
	.Q(req_meta_q[5]));
   DFFHQX1 \req_meta_q_reg[9]  (.D(src_req_async[9]),
	.CK(CTS_1),
	.Q(req_meta_q[9]));
   DFFHQX1 \req_meta_q_reg[3]  (.D(src_req_async[3]),
	.CK(CTS_1),
	.Q(req_meta_q[3]));
   DFFHQX1 \req_meta_q_reg[0]  (.D(src_req_async[0]),
	.CK(CTS_1),
	.Q(req_meta_q[0]));
   DFFHQX1 \req_meta_q_reg[1]  (.D(src_req_async[1]),
	.CK(CTS_1),
	.Q(req_meta_q[1]));
   DFFHQX1 \req_meta_q_reg[10]  (.D(src_req_async[10]),
	.CK(CTS_1),
	.Q(req_meta_q[10]));
   DFFHQX1 \req_meta_q_reg[7]  (.D(src_req_async[7]),
	.CK(CTS_1),
	.Q(req_meta_q[7]));
   DFFHQX1 \req_meta_q_reg[14]  (.D(src_req_async[14]),
	.CK(CTS_1),
	.Q(req_meta_q[14]));
   DFFHQX1 \req_meta_q_reg[8]  (.D(src_req_async[8]),
	.CK(CTS_1),
	.Q(req_meta_q[8]));
   DFFRHQX1 \reset_release_q_reg[0]  (.D(1'b1),
	.CK(CTS_1),
	.RN(FE_PHN1_rst_n),
	.Q(reset_release_q[0]));
   DFFHQX1 \req_meta_q_reg[15]  (.D(src_req_async[15]),
	.CK(CTS_1),
	.Q(req_meta_q[15]));
   MXI2XL g2 (.S0(epoch_gray_q[3]),
	.B(n_144),
	.A(epoch_gray_q[0]),
	.Y(n_197));
   DFFX1 \epoch_gray_q_reg[0]  (.D(n_102),
	.CK(CTS_1),
	.Q(epoch_gray_q[0]),
	.QN(n_144));
   DFFX1 \epoch_gray_q_reg[1]  (.D(n_99),
	.CK(CTS_1),
	.Q(epoch_gray_q[1]),
	.QN(n_69));
   DFFX1 out_valid_q_reg (.D(n_93),
	.CK(CTS_1),
	.Q(out_valid_q),
	.QN(n_5));
   DFFX1 \epoch_gray_q_reg[2]  (.D(n_100),
	.CK(CTS_1),
	.Q(epoch_gray_q[2]),
	.QN(n_84));
   NOR2BX1 g6100 (.AN(n_148),
	.B(n_54),
	.Y(n_237));
endmodule

