create_clock -name clk -period 10.000 -waveform {0.000 5.000} [get_ports clk]
set_clock_uncertainty -setup 0.200 [get_clocks clk]
set_clock_uncertainty -hold 0.020 [get_clocks clk]
set_false_path -from [get_ports src_req_async*]
set_input_delay 1.000 -clock clk [get_ports out_ready]
set_input_delay -min 0.100 -max 1.000 -clock clk [get_ports rst_n]
set_output_delay 1.000 -clock clk [get_ports {src_ack_async* out_addr* out_valid}]
set_max_transition 0.500 [current_design]
set_max_fanout 16 [current_design]
set_max_delay 0.800 -from [get_pins -hierarchical *req_meta_q_reg*/Q] -to [get_pins -hierarchical *req_sync_q_reg*/D]
set_max_delay 1.000 -from [get_pins -hierarchical *reset_release_q_reg*/Q] -to [get_pins -hierarchical *reset_release_q_reg*/D]
